In [1]:
!pip install requests

Requirement already satisfied: requests in D:\guvi\Lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in D:\guvi\Lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in D:\guvi\Lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in D:\guvi\Lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in D:\guvi\Lib\site-packages (from requests) (2026.1.4)

In [2]:
# Import requests library to call API (get data from internet)
import requests

# Import time library to add delay (avoid API blocking)
import time

# Create an empty list to store all records from all pages
records = []

# Base API URL (main endpoint)
base_url = "https://api.coingecko.com/api/v3/coins/markets"

# Loop through pages 1 to 5
for page in range(1, 6):

    # Parameters to send with API request
    params = {
        "vs_currency": "inr",              # Get prices in INR
        "order": "market_cap_desc",       # Sort by highest market cap
        "per_page": 250,                  # Get 250 records per page
        "page": page,                     # Current page number
        "sparkline": "false"              # Disable sparkline data
    }

    # Flag to check if request is successful
    success = False

    # Counter to track number of retry attempts
    attempts = 0

    # Retry loop: runs until success OR max 3 attempts reached
    while not success and attempts < 3:

        # Send GET request to API with parameters
        response = requests.get(base_url, params=params)

        # Check if request is successful (status code 200)
        if response.status_code == 200:

            # Convert response data into JSON format
            data = response.json()

            # Add all records from this page into main list
            records.extend(data)

            # Print success message
            print(f"Page {page} fetched ✅")

            # Mark as successful to stop retry loop
            success = True

        else:
            # Increase retry attempt count
            attempts += 1

            # Print error message with attempt number
            print(f"Error on page {page} ❌ (Attempt {attempts})")

            # Wait 5 seconds before retrying
            time.sleep(5)

    # Wait 2 seconds before moving to next page (avoid API rate limit)
    time.sleep(5)

# Print total number of records collected
print(f"\nTotal records collected: {len(records)}")

Page 1 fetched ✅
Page 2 fetched ✅
Page 3 fetched ✅
Error on page 4 ❌ (Attempt 1)
Error on page 4 ❌ (Attempt 2)
Error on page 4 ❌ (Attempt 3)
Error on page 5 ❌ (Attempt 1)
Error on page 5 ❌ (Attempt 2)
Page 5 fetched ✅

Total records collected: 1000

In [14]:
# Convert records list into DataFrame
import pandas as pd
df = pd.DataFrame(records)
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,7029893.00,140724637054110,1,1.407246e+14,5.639521e+12,7094595.00,...,2.001572e+07,2.100000e+07,11187013.00,-37.16023,2025-10-06T18:57:42.558Z,3993.420000,1.759369e+05,2013-07-05T00:00:00.000Z,None,2026-04-14T14:02:07.379Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,222636.00,26871383861167,2,2.687138e+13,2.657246e+12,225729.00,...,1.206910e+08,NaN,431946.00,-48.45731,2025-08-24T19:21:03.333Z,28.130000,7.913204e+05,2015-10-20T00:00:00.000Z,"{'times': 41.34983766580072, 'currency': 'btc'...",2026-04-14T14:02:03.919Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,93.14,17200267954974,3,1.770945e+13,9.020261e+12,95.17,...,1.901414e+11,NaN,105.52,-11.75962,2025-01-25T16:51:57.989Z,36.860000,1.526076e+02,2015-03-02T00:00:00.000Z,None,2026-04-14T14:02:07.609Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,129.65,7965142008935,4,1.296952e+13,2.837850e+11,130.87,...,9.998569e+10,1.000000e+11,313.99,-58.70770,2025-07-21T15:02:00.541Z,0.159343,8.126696e+04,2013-08-16T00:00:00.000Z,None,2026-04-14T14:02:07.623Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,57937.00,7897882229222,5,7.897882e+12,1.404209e+11,58539.00,...,1.363563e+08,2.000000e+08,121422.00,-52.28422,2025-10-13T08:41:24.131Z,2.580000,2.241421e+06,2017-10-19T00:00:00.000Z,None,2026-04-14T14:02:07.138Z

In [15]:
# Select only required columns
filtered_df = df[[
    "id",
    "symbol",
    "name",
    "current_price",
    "market_cap",
    "market_cap_rank",
    "total_volume",
    "circulating_supply",
    "total_supply",
    "ath",
    "atl",
    "last_updated"
]]

# Convert 'last_updated' to only DATE (remove time)
filtered_df["last_updated"] = pd.to_datetime(filtered_df["last_updated"]).dt.date

# Show first 5 rows
print(filtered_df.head())

# Save to CSV file
filtered_df.to_csv("cryptocurrencies.csv", index=False)

print("Filtered data saved ✅")

            id symbol      name  current_price       market_cap  \
0      bitcoin    btc   Bitcoin     7029893.00  140724637054110
1     ethereum    eth  Ethereum      222636.00   26871383861167
2       tether   usdt    Tether          93.14   17200267954974
3       ripple    xrp       XRP         129.65    7965142008935
4  binancecoin    bnb       BNB       57937.00    7897882229222

   market_cap_rank  total_volume  circulating_supply  total_supply  \
0                1  5.639521e+12        2.001572e+07  2.001572e+07
1                2  2.657246e+12        1.206910e+08  1.206910e+08
2                3  9.020261e+12        1.846744e+11  1.901414e+11
3                4  2.837850e+11        6.140553e+10  9.998569e+10
4                5  1.404209e+11        1.363563e+08  1.363563e+08

           ath          atl last_updated
0  11187013.00  3993.420000   2026-04-14
1    431946.00    28.130000   2026-04-14
2       105.52    36.860000   2026-04-14
3       313.99     0.159343   2026-04-14
4    121422.00     2.580000   2026-04-14
Filtered data saved ✅

C:\Users\HeY!\AppData\Local\Temp\ipykernel_21532\677050108.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["last_updated"] = pd.to_datetime(filtered_df["last_updated"]).dt.date

In [34]:
#Path C:\Users\HeY!\Project_1
import requests
import pandas as pd

# Change coin here
coin_id = "bitcoin"

# Dynamic URL 
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"

response = requests.get(url)
data = response.json()

# Convert to DataFrame
df_bitcoin = pd.DataFrame(data["prices"], columns=["timestamp", "price_inr"])

# Convert timestamp → date
df_bitcoin["date"] = pd.to_datetime( df_bitcoin["timestamp"], unit="ms").dt.date

# Add coin_id
df_bitcoin["coin_id"] = coin_id

# Final columns
df_bitcoin =  df_bitcoin[["coin_id", "date", "price_inr"]]

df_bitcoin.head()

   coin_id        date     price_inr
0  bitcoin  2025-04-15  7.271600e+06
1  bitcoin  2025-04-16  7.171573e+06
2  bitcoin  2025-04-17  7.201187e+06
3  bitcoin  2025-04-18  7.251703e+06
4  bitcoin  2025-04-19  7.209254e+06

In [35]:
#Path C:\Users\HeY!\Project_1
import requests
import pandas as pd

# Change coin here
coin_id = "ethereum"

# Dynamic URL 
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"

response = requests.get(url)
data = response.json()

# Convert to DataFrame
df_ethereum = pd.DataFrame(data["prices"], columns=["timestamp", "price_inr"])

# Convert timestamp → date
df_ethereum["date"] = pd.to_datetime( df_ethereum["timestamp"], unit="ms").dt.date

# Add coin_id
df_ethereum["coin_id"] = coin_id

# Final columns
df_ethereum =  df_ethereum[["coin_id", "date", "price_inr"]]

df_ethereum.head()

    coin_id        date      price_inr
0  ethereum  2025-04-15  139502.269181
1  ethereum  2025-04-16  136118.340300
2  ethereum  2025-04-17  135084.250075
3  ethereum  2025-04-18  135202.856452
4  ethereum  2025-04-19  135687.422766

In [36]:
#Path C:\Users\HeY!\Project_1
import requests
import pandas as pd

# Change coin here
coin_id = "tether"

# Dynamic URL 
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=inr&days=365"

response = requests.get(url)
data = response.json()

# Convert to DataFrame
df_tether = pd.DataFrame(data["prices"], columns=["timestamp", "price_inr"])

# Convert timestamp → date
df_tether["date"] = pd.to_datetime( df_tether["timestamp"], unit="ms").dt.date

# Add coin_id
df_tether["coin_id"] = coin_id

# Final columns
df_tether =  df_tether[["coin_id", "date", "price_inr"]]

df_tether.head()

  coin_id        date  price_inr
0  tether  2025-04-15  86.024832
1  tether  2025-04-16  85.722129
2  tether  2025-04-17  85.620824
3  tether  2025-04-18  85.384061
4  tether  2025-04-19  85.370372

In [37]:
#concat coins
import pandas as pd

# Combine all dataframes
combined_df = pd.concat([df_bitcoin, df_ethereum, df_tether]).reset_index(drop=True)

# Save as CSV file
combined_df.to_csv("crypto_prices.csv", index=False)

print("crypto_prices.csv saved successfully ✅")

crypto_prices.csv saved successfully ✅

In [31]:
import pandas as pd

# Load data
oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

# Convert to datetime
oil_df["Date"] = pd.to_datetime(oil_df["Date"])

# Filter from Jan 2020
oil_df = oil_df[oil_df["Date"] >= "2020-01-01"]

# Rename columns
oil_df = oil_df.rename(columns={"Date": "date", "Price": "price_usd"})

# ✅ Convert USD → INR
oil_df["price_inr"] = oil_df["price_usd"] * 83

# Keep required columns
oil_df = oil_df[["date", "price_inr"]]

# Save CSV
oil_df.to_csv("oil_prices.csv", index=False)

print("Oil data in INR saved ✅")

Oil data in INR saved ✅

In [35]:
import pandas as pd
oil_df=pd.read_csv(r'C:\Users\HeY!\Project_1\oil_prices.csv')
oil_df.tail()

            date   price_inr
1559  2026-03-30 8689.270000
1560  2026-03-31 8537.380000
1561  2026-04-01 8457.700000
1562  2026-04-02 9398.090000
1563  2026-04-06 9462.830000

In [1]:
import sys
print(sys.executable)

D:\guvi\python.exe

In [2]:
import sys
!{sys.executable} -m pip install yfinance --user

Requirement already satisfied: yfinance in C:\Users\HeY!\AppData\Roaming\Python\Python313\site-packages (1.2.2)
Requirement already satisfied: pandas>=1.3.0 in D:\guvi\Lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in D:\guvi\Lib\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in D:\guvi\Lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in D:\guvi\Lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in D:\guvi\Lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in D:\guvi\Lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in D:\guvi\Lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in D:\guvi\Lib\site-packages (from yfinance) (4.0.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in D:\guvi\Lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi>=0.15 in C:\Users\HeY!\AppData\Roaming\Python\Python313\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in D:\guvi\Lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in D:\guvi\Lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: soupsieve>1.2 in D:\guvi\Lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=2.0.0 in C:\Users\HeY!\AppData\Roaming\Python\Python313\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in D:\guvi\Lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.1.4)
Requirement already satisfied: rich in D:\guvi\Lib\site-packages (from curl_cffi>=0.15->yfinance) (13.9.4)
Requirement already satisfied: pycparser in D:\guvi\Lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\guvi\Lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in D:\guvi\Lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in D:\guvi\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in D:\guvi\Lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in D:\guvi\Lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in D:\guvi\Lib\site-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in D:\guvi\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in D:\guvi\Lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in D:\guvi\Lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.0)

In [3]:
import yfinance as yf

In [4]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-04-06"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker            ^GSPC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

In [9]:
stock_1 = stocks_df['^GSPC'].reset_index()

# Add ticker column
stock_1["ticker"] = "^GSPC"

stock_1.head()

Price,Date,Open,High,Low,Close,Volume,ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC

In [10]:
stock_2 = stocks_df['^IXIC'].reset_index()

# Add ticker column
stock_2["ticker"] = "^IXIC"

stock_2.head()

Price,Date,Open,High,Low,Close,Volume,ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^IXIC
1,2020-01-02,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09,^IXIC
2,2020-01-03,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09,^IXIC
3,2020-01-06,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09,^IXIC
4,2020-01-07,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09,^IXIC

In [12]:
stock_3 = stocks_df['^NSEI'].reset_index()

# Add ticker column
stock_3["ticker"] = "^NSEI"

stock_3.head()

Price,Date,Open,High,Low,Close,Volume,ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0,^NSEI

In [15]:
final_stocks = pd.concat([stock_1, stock_2, stock_3], ignore_index=True)
final_stocks.to_csv("stock_prices.csv", index=False)
final_stocks

Price,Date,Open,High,Low,Close,Volume,ticker
0,2020-01-01,NaN,NaN,NaN,NaN,NaN,^GSPC
1,2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09,^GSPC
2,2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09,^GSPC
3,2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09,^GSPC
4,2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09,^GSPC
...,...,...,...,...,...,...,...
4861,2026-03-27,23173.550781,23186.099609,22804.550781,22819.599609,6.126000e+05,^NSEI
4862,2026-03-30,22549.650391,22714.099609,22283.849609,22331.400391,6.986000e+05,^NSEI
4863,2026-03-31,NaN,NaN,NaN,NaN,NaN,^NSEI
4864,2026-04-01,22899.000000,22941.300781,22618.599609,22679.400391,5.180000e+05,^NSEI
4865,2026-04-02,22383.400391,22782.300781,22182.550781,22713.099609,4.951000e+05,^NSEI

In [4]:
!pip install mysql-connector-python pandas

Requirement already satisfied: mysql-connector-python in D:\guvi\Lib\site-packages (9.6.0)
Requirement already satisfied: pandas in D:\guvi\Lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in D:\guvi\Lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\guvi\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in D:\guvi\Lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in D:\guvi\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in D:\guvi\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
# Import MySQL connector (connect Python with MySQL)
import mysql.connector

# Step 1: Connect to MySQL server
conn = mysql.connector.connect(
    host="localhost",   # your system
    user="root",        # MySQL username
    password="12345"    # your MySQL password
)

# Step 2: Create cursor (used to run SQL queries)
cursor = conn.cursor()

print("Connected successfully ✅")

Connected successfully ✅

In [6]:
# Create database
cursor.execute("CREATE DATABASE IF NOT EXISTS market_analysis")

# Select (use) that database
cursor.execute("USE market_analysis")

print("Database ready ✅")

Database ready ✅

In [3]:
# Create cryptocurrencies table
cursor.execute("""
CREATE TABLE IF NOT EXISTS cryptocurrencies (
    id VARCHAR(50) PRIMARY KEY,
    symbol VARCHAR(10),
    name VARCHAR(100),
    current_price DECIMAL(18,6),
    market_cap BIGINT,
    market_cap_rank INT,
    total_volume BIGINT,
    circulating_supply DECIMAL(20,6),
    total_supply DECIMAL(20,6),
    ath DECIMAL(18,6),
    atl DECIMAL(18,6),
    date DATE
)
""")

print("Table created ✅")

Table created ✅

In [4]:
# Create crypto_prices table
cursor.execute("""
CREATE TABLE IF NOT EXISTS crypto_prices (
    coin_id VARCHAR(50),      -- coin name like bitcoin, ethereum
    date DATE,                -- date of price
    price_inr DECIMAL(18,6)   -- price in INR
)
""")

print("crypto_prices table created ✅")

crypto_prices table created ✅

In [5]:
# Create oil_prices table
cursor.execute("""
CREATE TABLE IF NOT EXISTS oil_prices (
    date DATE PRIMARY KEY,    -- unique date
    price_inr DECIMAL(18,6)   -- oil price in INR
)
""")

print("oil_prices table created ✅")

oil_prices table created ✅

In [6]:
# Create stock_prices table
cursor.execute("""
CREATE TABLE IF NOT EXISTS stock_prices (
    date DATE,                -- trading date
    open DECIMAL(18,6),       -- opening price
    high DECIMAL(18,6),       -- highest price
    low DECIMAL(18,6),        -- lowest price
    close DECIMAL(18,6),      -- closing price
    volume BIGINT,            -- trading volume
    ticker VARCHAR(20)        -- stock index (^GSPC, ^IXIC, ^NSEI)
)
""")

print("stock_prices table created ✅")

stock_prices table created ✅

In [7]:
cursor.execute("SHOW TABLES")

for table in cursor:
    print(table)

('crypto_prices',)
('cryptocurrencies',)
('oil_prices',)
('stock_prices',)

In [9]:
import pandas as pd
df = pd.read_csv("cryptocurrencies.csv")

# Rename column to match SQL table
df.rename(columns={"last_updated": "date"}, inplace=True)

In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv("cryptocurrencies.csv")

# Rename column
df.rename(columns={"last_updated": "date"}, inplace=True)

# 🔥 Convert ALL nan / NaN / empty → None
df = df.replace({np.nan: None, "nan": None, "": None})

In [13]:
df = df[
    [
        "id", "symbol", "name", "current_price", "market_cap",
        "market_cap_rank", "total_volume", "circulating_supply",
        "total_supply", "ath", "atl", "date"
    ]
]

In [14]:
for _, row in df.iterrows():
    values = tuple(None if str(x).lower() == "nan" else x for x in row)

    cursor.execute("""
        INSERT IGNORE INTO cryptocurrencies 
        (id, symbol, name, current_price, market_cap, market_cap_rank,
         total_volume, circulating_supply, total_supply, ath, atl, date)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """, values)

conn.commit()

print("Inserted successfully ✅")

Inserted successfully ✅

In [15]:
cursor.execute("SELECT COUNT(*) FROM cryptocurrencies")
print(cursor.fetchall())

[(1000,)]

In [16]:
import pandas as pd
import numpy as np

# Step 1: Load CSV file
df = pd.read_csv("crypto_prices.csv")

# Step 2: Clean data (VERY IMPORTANT)
df = df.replace({np.nan: None, "nan": None, "": None})

# Step 3: Ensure correct column order
df = df[["coin_id", "date", "price_inr"]]

# Step 4: Insert into MySQL
data = []

for _, row in df.iterrows():
    # Convert any 'nan' string to None
    values = tuple(None if str(x).lower() == "nan" else x for x in row)
    data.append(values)

cursor.executemany("""
    INSERT INTO crypto_prices (coin_id, date, price_inr)
    VALUES (%s, %s, %s)
""", data)

# Step 5: Save changes
conn.commit()

print("crypto_prices inserted ✅")

crypto_prices inserted ✅

In [17]:
import pandas as pd
import numpy as np

# Step 1: Load CSV
df = pd.read_csv("oil_prices.csv")

# Step 2: Clean data
df = df.replace({np.nan: None, "nan": None, "": None})

# Step 3: Ensure column order
df = df[["date", "price_inr"]]

# Step 4: Insert
data = []

for _, row in df.iterrows():
    values = tuple(None if str(x).lower() == "nan" else x for x in row)
    data.append(values)

cursor.executemany("""
    INSERT IGNORE INTO oil_prices (date, price_inr)
    VALUES (%s, %s)
""", data)

# Step 5: Commit
conn.commit()

print("oil_prices inserted ✅")

oil_prices inserted ✅

In [18]:
import pandas as pd

df = pd.read_csv("stock_prices.csv")

# Fix column names
df.rename(columns={
    "Date": "date",
    "Open": "open",
    "High": "high",
    "Low": "low",
    "Close": "close",
    "Volume": "volume"
}, inplace=True)

df.to_csv("stock_prices.csv", index=False)

print("Columns fixed ✅")

Columns fixed ✅

In [19]:
import pandas as pd
import numpy as np

# Step 1: Load CSV
df = pd.read_csv("stock_prices.csv")

# Step 2: Clean data
df = df.replace({np.nan: None, "nan": None, "": None})

# Step 3: Ensure correct column order
df = df[["date", "open", "high", "low", "close", "volume", "ticker"]]

# Step 4: Insert
data = []

for _, row in df.iterrows():
    values = tuple(None if str(x).lower() == "nan" else x for x in row)
    data.append(values)

cursor.executemany("""
    INSERT INTO stock_prices (date, open, high, low, close, volume, ticker)
    VALUES (%s, %s, %s, %s, %s, %s, %s)
""", data)

# Step 5: Commit
conn.commit()

print("stock_prices inserted ✅")

stock_prices inserted ✅

In [20]:
cursor.execute("SELECT COUNT(*) FROM crypto_prices")
print("crypto_prices:", cursor.fetchall())

cursor.execute("SELECT COUNT(*) FROM oil_prices")
print("oil_prices:", cursor.fetchall())

cursor.execute("SELECT COUNT(*) FROM stock_prices")
print("stock_prices:", cursor.fetchall())

crypto_prices: [(1098,)]
oil_prices: [(1564,)]
stock_prices: [(4866,)]

In [ ]:
#1️⃣ cryptocurrencies

In [25]:
#Top 3 cryptocurrencies by market cap
cursor.execute("""
SELECT name, market_cap
FROM cryptocurrencies
ORDER BY market_cap DESC
LIMIT 3
""")

for row in cursor.fetchall():
    print(row)

('Bitcoin', 140724637054110)
('Ethereum', 26871383861167)
('Tether', 17200267954974)

In [31]:
#List all coins where circulating supply exceeds 90% of total supply.
cursor.execute("""
SELECT name, circulating_supply, total_supply
FROM cryptocurrencies
WHERE circulating_supply >= 0.9 * total_supply
""")

# Fetch and print results
for row in cursor.fetchall():
    print(row)

('1INCH', Decimal('1404568058.661079'), Decimal('1499999999.997000'))
('4', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('69420', Decimal('62502297000.000000'), Decimal('69420000000.000000'))
('A7A5', Decimal('39202265328.270740'), Decimal('39202265328.270740'))
('Aave', Decimal('15164786.532628'), Decimal('16000000.000000'))
('Act I The AI Prophecy', Decimal('948241537.069214'), Decimal('948241537.069214'))
('heyAura', Decimal('147900000.000000'), Decimal('150000000.000000'))
('Aegis YUSD', Decimal('36512404.354581'), Decimal('36512404.354581'))
('Aergo', Decimal('472499995.768921'), Decimal('500000000.000000'))
('affine', Decimal('2891495.101057'), Decimal('2891495.101057'))
('AgentFun.AI', Decimal('100000000.000000'), Decimal('100000000.000000'))
('AUSD', Decimal('216456853.000000'), Decimal('216456853.000000'))
('AhaToken', Decimal('7257848898.024749'), Decimal('7673122637.674749'))
('AI Companions', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('AI Rig Complex', Decimal('999983305.919110'), Decimal('999983305.919110'))
('AIntivirus', Decimal('999781763.940798'), Decimal('999781763.940798'))
('AIOZ Network', Decimal('1244656772.648920'), Decimal('1247355924.257783'))
('aixbt', Decimal('994658423.101021'), Decimal('1000000000.000000'))
('Akash Network', Decimal('262860807.734932'), Decimal('291763270.479454'))
('Algorand', Decimal('8902478568.839878'), Decimal('8902698655.360626'))
('Alien Worlds', Decimal('6537103708.803401'), Decimal('6968254177.040300'))
('Alloy Tether', Decimal('50000005.000000'), Decimal('50000005.000000'))
('Alpha Fi', Decimal('9904201.024087'), Decimal('10000000.000000'))
('Alphabet Class A (Ondo Tokenized Stock)', Decimal('86207.289214'), Decimal('86207.289214'))
('Altura Vault Tokens', Decimal('13112890.853799'), Decimal('13112890.853799'))
('America Party', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('ANDY ETH', Decimal('1000000000000.000000'), Decimal('1000000000000.000000'))
('ANDY70B', Decimal('965383606.160000'), Decimal('965383606.160000'))
('Ankr Network', Decimal('10000000000.000000'), Decimal('10000000000.000000'))
('Anzen USDz', Decimal('10040151.877908'), Decimal('10040151.877908'))
('Anzens USDA', Decimal('10081677.000000'), Decimal('10081677.000000'))
('Ape and Pepe', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('ApeCoin', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('AINFT', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('APES', Decimal('900000000.000000'), Decimal('900000000.000000'))
('Apex', Decimal('4223743.400832'), Decimal('4223743.400832'))
('Apollo Diversified Credit Securitize Fund', Decimal('120944.900877'), Decimal('120944.900877'))
('Apu Apustaja', Decimal('337890271346.088800'), Decimal('337890271346.088800'))
('apxUSD', Decimal('144278625.000000'), Decimal('144278625.000000'))
('apyUSD', Decimal('42399760.001207'), Decimal('42399760.001207'))
('Ardor', Decimal('998466231.000000'), Decimal('998466231.000000'))
('ARK', Decimal('195862486.000000'), Decimal('195862486.000000'))
('Arweave', Decimal('65652466.000000'), Decimal('65652466.000000'))
('AscendEx', Decimal('742983477.862000'), Decimal('742983477.862000'))
('Astar', Decimal('8582267587.000000'), Decimal('8674501695.000000'))
('Aster USDF', Decimal('118618294.167929'), Decimal('118618294.167929'))
('AtomOne', Decimal('128591692.631730'), Decimal('140399604.291730'))
('Bounce', Decimal('7340402.318294'), Decimal('7641028.818628'))
('Avalanche', Decimal('431771961.177212'), Decimal('463441061.177212'))
('Avant USD', Decimal('125923421.115805'), Decimal('125923421.115805'))
('Axelar', Decimal('1152309972.336408'), Decimal('1237318566.936183'))
('B3 (Base)', Decimal('100000000000.000000'), Decimal('100000000000.000000'))
('Baby Doge Coin', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('Bald', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Balsa MM Fund', Decimal('131288708.209859'), Decimal('131288708.209859'))
('Banana For Scale', Decimal('10000000000.000000'), Decimal('10000000000.000000'))
('Bancor Network', Decimal('108966189.032846'), Decimal('108966189.032846'))
('Band', Decimal('174178596.251852'), Decimal('174844069.126574'))
('BankrCoin', Decimal('99999999999.999980'), Decimal('99999999999.999980'))
('Brett', Decimal('9909607465.149370'), Decimal('9909607465.149370'))
('BasedHype', Decimal('10000000000.000000'), Decimal('10000000000.000000'))
('Basic Attention', Decimal('1495724656.952606'), Decimal('1500000000.000000'))
('BCGame Coin', Decimal('9989368360.422651'), Decimal('9989368360.422651'))
('BENQI', Decimal('7200000000.000000'), Decimal('7200000000.000000'))
('Bertram The Pomeranian', Decimal('978043021.771680'), Decimal('978043021.771680'))
('BFUSD', Decimal('1320000000.000000'), Decimal('1320000000.000000'))
('币安人生 (BinanceLife)', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Big Dog Fink', Decimal('148939223653.982800'), Decimal('148939223653.982800'))
('BIM', Decimal('30000000.000000'), Decimal('30000000.000000'))
('BUSD', Decimal('40026297.125946'), Decimal('40026297.125946'))
('BNB', Decimal('136356333.560000'), Decimal('136356333.560000'))
('Bitcoin', Decimal('20015718.000000'), Decimal('20015718.000000'))
('Bitcoin Cash', Decimal('20021034.271651'), Decimal('20021312.396651'))
('Bitcoin SV', Decimal('20014875.000000'), Decimal('20014903.125000'))
('Bitgert', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('BitTorrent', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('BlackRock USD Institutional Digital Liquidity Fund', Decimal('2494070874.510449'), Decimal('2494070874.510449'))
('Blockchain Capital', Decimal('9112111.000000'), Decimal('9112111.000000'))
('Stacks', Decimal('1841080701.569110'), Decimal('1841080701.569110'))
('BLOCKv', Decimal('2625758669.039750'), Decimal('2625758669.039750'))
('Blur', Decimal('2776548356.307078'), Decimal('3000000000.000000'))
('KOGE', Decimal('3379998.560000'), Decimal('3379998.560000'))
('Boba Network', Decimal('493599306.000000'), Decimal('500000000.000000'))
('Bonk', Decimal('87994740199998.560000'), Decimal('87994740199998.700000'))
('BOOK OF MEME', Decimal('68999659569.000000'), Decimal('68999659569.000000'))
('BORA', Decimal('1152750000.000000'), Decimal('1205750000.000000'))
('Brazilian Digital', Decimal('265482681.162169'), Decimal('265482681.162169'))
('Bucket Protocol BUCK Stablecoin', Decimal('26126074.990016'), Decimal('26126074.990016'))
('BUILDon', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('BurnedFi', Decimal('12349506.150823'), Decimal('12349506.150823'))
('Buttcoin', Decimal('999983802.704271'), Decimal('999983802.704271'))
('Maya Protocol', Decimal('100000000.000000'), Decimal('100000000.000000'))
('Canton', Decimal('38309740365.304100'), Decimal('38309740365.304100'))
('Cap USD', Decimal('93434470.635976'), Decimal('93434470.635976'))
('Carrot', Decimal('145878.848196'), Decimal('145878.848196'))
('Cartesi', Decimal('910176531.790014'), Decimal('1000000000.000000'))
('CASH', Decimal('123263493.301935'), Decimal('123263493.301935'))
('cat in a dogs world', Decimal('88888888888.880000'), Decimal('88888888888.880000'))
('CATX', Decimal('1000000000000.000000'), Decimal('1000000000000.000000'))
('lium', Decimal('3865629.891758'), Decimal('3865629.891758'))
('Shentu', Decimal('157764712.000000'), Decimal('158019422.000000'))
('Cheems Token', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('Chiliz', Decimal('10302217361.000000'), Decimal('10302217361.000000'))
('Chutes', Decimal('4797360.063902'), Decimal('4797360.063902'))
('Circle Internet Group (Ondo Tokenized Stock)', Decimal('1563736.537196'), Decimal('1563736.537196'))
('Cobak', Decimal('99187817.000000'), Decimal('100000000.000000'))
('CoinEx', Decimal('2526659417.790000'), Decimal('2526659417.790000'))
('Comedian', Decimal('999961859.270000'), Decimal('999961859.270000'))
('CommonWealth', Decimal('900496853.987374'), Decimal('999999341.549563'))
('Compound', Decimal('9668189.278361'), Decimal('10000000.000000'))
('Compounding OpenDollar', Decimal('27997409.207495'), Decimal('27997409.207495'))
('Conflux', Decimal('5189835932.130000'), Decimal('5201143742.260000'))
('Constellation', Decimal('3844784199.531072'), Decimal('3844784199.531072'))
('ConstitutionDAO', Decimal('5066444892.014003'), Decimal('5066444892.014003'))
('Cosmos Hub', Decimal('503326279.529955'), Decimal('503326279.529955'))
('COTI', Decimal('2766904758.804905'), Decimal('2766930361.469526'))
('CREPE', Decimal('690000000000.000000'), Decimal('690000000000.000000'))
('Crob Mob', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Crown BRLV', Decimal('221616077.652830'), Decimal('221616077.652830'))
('crvUSD', Decimal('265635827.475571'), Decimal('265635827.475571'))
('Cygnus Finance Global USD', Decimal('75287408.277595'), Decimal('75287408.277595'))
('Dacxi', Decimal('10000000000.000000'), Decimal('10000000000.000000'))
('Dai', Decimal('4372315348.239364'), Decimal('4372315348.239364'))
('DAI on PulseChain', Decimal('44359137455.629230'), Decimal('44359137455.629230'))
('DAO Maker', Decimal('250926000.000000'), Decimal('277627380.530000'))
('Dash', Decimal('12660739.150986'), Decimal('12661466.965075'))
('Data Universe', Decimal('4562330.175590'), Decimal('4562330.175590'))
('DEAPCOIN', Decimal('27526332268.328957'), Decimal('29892900001.328957'))
('Decred', Decimal('17369594.330539'), Decimal('17370609.573965'))
('Defi.money', Decimal('9994958.759827'), Decimal('9994958.759827'))
('Degen', Decimal('36965730333.000000'), Decimal('36965730333.000000'))
('Decentralized Social', Decimal('10532253.885400'), Decimal('10808492.685400'))
('Dialectic USD Vault', Decimal('10171196.079638'), Decimal('10171196.079638'))
('Diem', Decimal('37884.667138'), Decimal('37884.667138'))
('DigiByte', Decimal('18238946201.496450'), Decimal('18240271342.887190'))
('Dippy', Decimal('3790623.568753'), Decimal('3790623.568753'))
('dKargo', Decimal('5000000000.000000'), Decimal('5000000000.000000'))
('Dog (Bitcoin)', Decimal('100000000000.000000'), Decimal('100000000000.000000'))
('Dogecoin', Decimal('153827196383.705200'), Decimal('169538903126.579100'))
('Dogelon Mars', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('dogwifhat', Decimal('998926392.000000'), Decimal('998926392.000000'))
('DOVU', Decimal('10000000000.000000'), Decimal('10000000000.000000'))
('Dupe', Decimal('999940626.244102'), Decimal('999940626.244102'))
('DUSK', Decimal('500000000.000000'), Decimal('500000000.000000'))
('EarthMeta', Decimal('2016000000.000000'), Decimal('2100000000.000000'))
('eBTC', Decimal('505.382105'), Decimal('505.382105'))
('eCash', Decimal('20014717172580.000000'), Decimal('20014717172580.000000'))
('Ekubo Protocol', Decimal('10000000.000000'), Decimal('10000000.000000'))
('Ellipsis [OLD]', Decimal('698445817.390559'), Decimal('723701571.799789'))
('MultiversX', Decimal('29722099.000000'), Decimal('29722099.000000'))
('ELYSIA', Decimal('6803300704.688000'), Decimal('6803300704.688000'))
('Ember Third Eye', Decimal('10163619.097560'), Decimal('10163619.097560'))
('Enjin Coin', Decimal('1948806435.357634'), Decimal('1981248183.689344'))
('Enosys Loans CDP', Decimal('9577283.477430'), Decimal('9577283.477430'))
('Epic Chain', Decimal('33600000.000000'), Decimal('33600000.000000'))
('eSui Dollar', Decimal('11893755.179959'), Decimal('11893755.179959'))
('Ethena USDe', Decimal('5828297803.804168'), Decimal('5828297803.804168'))
('Ethereum', Decimal('120690991.774998'), Decimal('120690991.774998'))
('Ethereum Classic', Decimal('156289683.260869'), Decimal('156300304.047786'))
('EthereumPoW', Decimal('107818717.000000'), Decimal('107818717.000000'))
('Eurite', Decimal('50968932.999901'), Decimal('50968932.999901'))
('EURC', Decimal('359821529.346091'), Decimal('359821529.346091'))
('eUSD', Decimal('10000000.000000'), Decimal('10000000.000000'))
('Spiko EU T-Bills Money Market Fund', Decimal('755715411.202020'), Decimal('755715411.202020'))
('IQ', Decimal('25604026163.928990'), Decimal('25604026163.928990'))
('Everything', Decimal('99999997999.870000'), Decimal('99999997999.870000'))
('EXOD', Decimal('10446000.000000'), Decimal('10446000.000000'))
('Falcon USD', Decimal('1789549457.493094'), Decimal('1789549457.493094'))
('FAR Labs', Decimal('4872783829.673780'), Decimal('5000000000.000000'))
('Fartcoin', Decimal('999978724.439821'), Decimal('999978724.439821'))
('Fidelity Digital Dollar', Decimal('49851102.590000'), Decimal('49851102.590000'))
('Fidelity Digital Interest Token', Decimal('152491819.700000'), Decimal('152491819.700000'))
('Figure Heloc', Decimal('16729421014.127000'), Decimal('16729421014.127000'))
('First Digital USD', Decimal('404985187.012190'), Decimal('404985187.012190'))
('FLOKI', Decimal('9653695614876.000000'), Decimal('10000000000000.000000'))
('Flow', Decimal('1654179373.087993'), Decimal('1654179373.087993'))
('Foom', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('Frankencoin', Decimal('30606084.564901'), Decimal('30606084.564901'))
('Legacy Frax Dollar', Decimal('275935184.010268'), Decimal('275935184.010268'))
('Frax (prev. FXS)', Decimal('95404815.132180'), Decimal('99681495.591134'))
('Frax USD', Decimal('133578561.515116'), Decimal('133578561.515116'))
('Freedom Dollar', Decimal('9600000.000000'), Decimal('9600000.000000'))
('Freedom of Money', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Freysa AI', Decimal('8189700000.000000'), Decimal('8189700000.000000'))
('Fuzzybear', Decimal('317770791933.930850'), Decimal('320999751125.999900'))
('f(x) USD Saving', Decimal('28186763.661973'), Decimal('28186763.661973'))
('GALA', Decimal('47625678087.081970'), Decimal('47625678106.081980'))
('Gama Token', Decimal('100027884.000000'), Decimal('100027884.000000'))
('Gas', Decimal('65093580.544273'), Decimal('65093580.544273'))
('Gate', Decimal('115180573.048858'), Decimal('115180573.048858'))
('Gauntlet USD Alpha', Decimal('73240414.010000'), Decimal('1600835.545626'))
('GEKKO', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('Gemini Dollar', Decimal('43729224.600000'), Decimal('43729224.600000'))
('Get AI', Decimal('547000000.000000'), Decimal('547000000.000000'))
('GHO', Decimal('584000000.000000'), Decimal('584000000.000000'))
('Giggle Fund', Decimal('1000000.000000'), Decimal('1000000.000000'))
('Global Dollar', Decimal('2159590280.873681'), Decimal('2159590280.873681'))
('GoMining Token', Decimal('404989915.541096'), Decimal('404989915.541096'))
('GMX', Decimal('10384074.653081'), Decimal('10384074.653081'))
('Golem', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Gradients', Decimal('4291536.552580'), Decimal('4291536.552580'))
('Green', Decimal('47726369991.753420'), Decimal('47726369991.753420'))
('GRIFFAIN', Decimal('999851010.335152'), Decimal('999851010.335152'))
('GRX Chain', Decimal('9512395.000000'), Decimal('9998039.000000'))
('哈基米 (Hajimi)', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Hanu Yokia', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('Harmony', Decimal('14870211425.762917'), Decimal('14870212769.762917'))
('Circle USYC', Decimal('2393041089.101221'), Decimal('2393041089.101221'))
('PRIME', Decimal('345863783.528667'), Decimal('345863783.528667'))
('Synthetix', Decimal('344516234.457288'), Decimal('344939867.555663'))
('Helder', Decimal('197555047.998026'), Decimal('3477441.998026'))
('Lista USD', Decimal('76305077.213994'), Decimal('76305077.213994'))
('Helium', Decimal('184214185.859461'), Decimal('184214185.859461'))
('Hermetica USDh', Decimal('9455964.021808'), Decimal('9455964.021808'))
('Hermez Network', Decimal('11065762.534833'), Decimal('11065762.534833'))
('Hex Trust USD', Decimal('44120878.570000'), Decimal('44120878.570000'))
('Hive Dollar', Decimal('33282723.723000'), Decimal('33282723.723000'))
('Holo', Decimal('177619433541.141300'), Decimal('177619433541.141300'))
('Honey', Decimal('25445227.020679'), Decimal('25445308.404754'))
('HOPR', Decimal('665881229.543035'), Decimal('689040019.283035'))
('HorseCoin', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Hosky', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('HTX DAO', Decimal('99999999999999.999999'), Decimal('99999999999999.999999'))
('Hydration', Decimal('5918174822.000000'), Decimal('6422921278.131422'))
('Hydrated Dollar', Decimal('11606627.924633'), Decimal('11606627.924633'))
('Hypurr Fun', Decimal('995962.396258'), Decimal('995962.396258'))
('ICON', Decimal('1095854136.663419'), Decimal('1108792274.218095'))
('infiniFi Locked iUSD (1week)', Decimal('24416356.238539'), Decimal('24416356.238539'))
('InfiniFi USD', Decimal('106594176.060378'), Decimal('106594176.060378'))
('InfinitiCoin', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Injective', Decimal('100000000.000000'), Decimal('100000000.000000'))
('Intel (Ondo Tokenized Stock)', Decimal('163308.783254'), Decimal('163308.783254'))
('Internet Computer', Decimal('550845062.085922'), Decimal('550845062.085922'))
('Inverse Finance', Decimal('708233.890569'), Decimal('727000.000000'))
('Invesco QQQ ETF (Ondo Tokenized ETF)', Decimal('47294.510866'), Decimal('47294.510866'))
('IOST', Decimal('32719700864.000000'), Decimal('32719700864.000000'))
('IOTA', Decimal('4381322863.000000'), Decimal('4863768893.000000'))
('iota', Decimal('4122398.539871'), Decimal('4122398.539871'))
('IoTeX', Decimal('9441368592.000000'), Decimal('9441368597.000000'))
('iShares Bitcoin Trust (Ondo Tokenized)', Decimal('831768.690827'), Decimal('831768.690827'))
('iShares Core MSCI Emerging Markets ETF (Ondo Tokenized ETF)', Decimal('119682.409418'), Decimal('119682.409418'))
('iShares Core S&P Total US Stock Market ETF (Ondo Tokenized ETF)', Decimal('75256.021956'), Decimal('75256.021956'))
('iShares MSCI EAFE ETF (Ondo Tokenized ETF)', Decimal('104328.181395'), Decimal('104328.181395'))
('iShares Silver Trust (Ondo Tokenized Stock)', Decimal('472341.427629'), Decimal('472341.427629'))
('iShares TIPS Bond ETF (Ondo Tokenized ETF)', Decimal('100160.461516'), Decimal('100160.461516'))
('IXS', Decimal('180000000.000000'), Decimal('180000000.000000'))
('Janus Henderson Anemoy AAA CLO Fund', Decimal('390574834.714133'), Decimal('390574834.714133'))
('Janus Henderson Anemoy Treasury Fund', Decimal('1292789400.280565'), Decimal('1292789400.280565'))
('JasmyCoin', Decimal('49444999677.590270'), Decimal('50000000000.000000'))
('Jelly-My-Jelly', Decimal('999999099.340000'), Decimal('999999099.340000'))
('Joe Coin', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('JupUSD', Decimal('79262147.710698'), Decimal('79262147.710698'))
('JUST', Decimal('8815108090.312735'), Decimal('8815108090.312735'))
('just a frog', Decimal('999966806.937156'), Decimal('999966806.937156'))
('Kaia', Decimal('5856641747.106198'), Decimal('5856641936.044253'))
('Kaspa', Decimal('27326836350.155420'), Decimal('27361693809.960180'))
('Kava', Decimal('1082847242.000000'), Decimal('1082847242.000000'))
('Kekius Maximus', Decimal('1000000000.000000'), Decimal('1000000000.000000'))
('Kelp Gain', Decimal('12849.715823'), Decimal('12849.715823'))
('Kinesis Gold', Decimal('2386227.834200'), Decimal('2386227.834200'))
('Kinesis Silver', Decimal('3777096.933600'), Decimal('3777096.933600'))
('Kled AI', Decimal('999790681.276780'), Decimal('999790681.276780'))
('Klever', Decimal('9026596500.112520'), Decimal('9026596500.112520'))
('KuCoin', Decimal('134655021.735567'), Decimal('142155021.735567'))
('Kusama', Decimal('18057806.180894'), Decimal('18057806.180894'))
('LandWolf', Decimal('902159505150.000000'), Decimal('902159505150.000000'))
('LCX', Decimal('940989527.000000'), Decimal('934077156.428630'))
('LEO Token', Decimal('920845344.900000'), Decimal('985239504.000000'))

In [34]:
#3rd query result (coins within 10% of ATH)
cursor.execute("""
SELECT name, current_price, ath
FROM cryptocurrencies
WHERE current_price >= 0.9 * ath
""")

for row in cursor.fetchall():
    print(row)

('ADI', Decimal('401.650000'), Decimal('421.780000'))
('AUSD', Decimal('93.090000'), Decimal('95.190000'))
('AIntivirus', Decimal('2.860000'), Decimal('2.890000'))
('Alloy Tether', Decimal('93.000000'), Decimal('95.210000'))
('Alphabet Class A (Ondo Tokenized Stock)', Decimal('30431.000000'), Decimal('31792.000000'))
('Altura Vault Tokens', Decimal('98.030000'), Decimal('101.060000'))
('Anzen USDz', Decimal('92.390000'), Decimal('94.820000'))
('APES', Decimal('7.060000'), Decimal('7.130000'))
('Apollo Diversified Credit Securitize Fund', Decimal('101746.000000'), Decimal('104019.000000'))
('Aster USDF', Decimal('93.000000'), Decimal('95.080000'))
('Avant USD', Decimal('93.060000'), Decimal('95.130000'))
('Balsa MM Fund', Decimal('7.630000'), Decimal('7.790000'))
('BFUSD', Decimal('93.070000'), Decimal('95.160000'))
('bitcastle Token', Decimal('18.680000'), Decimal('18.940000'))
('BlackRock USD Institutional Digital Liquidity Fund', Decimal('93.080000'), Decimal('95.200000'))
('Blockchain Capital', Decimal('7703.390000'), Decimal('7883.410000'))
('CASH', Decimal('93.070000'), Decimal('97.190000'))
('Compounding OpenDollar', Decimal('97.290000'), Decimal('99.470000'))
('Crown BRLV', Decimal('18.710000'), Decimal('19.040000'))
('crvUSD', Decimal('93.110000'), Decimal('96.910000'))
('Cygnus Finance Global USD', Decimal('92.660000'), Decimal('94.810000'))
('Dai', Decimal('93.050000'), Decimal('95.190000'))
('Defi.money', Decimal('92.840000'), Decimal('95.250000'))
('Diem', Decimal('110246.000000'), Decimal('109218.000000'))
('eBTC', Decimal('7003828.000000'), Decimal('7079451.000000'))
('Ember Third Eye', Decimal('95.930000'), Decimal('102.000000'))
('Enosys Loans CDP', Decimal('93.710000'), Decimal('101.340000'))
('eSui Dollar', Decimal('93.070000'), Decimal('97.480000'))
('Ethena USDe', Decimal('93.120000'), Decimal('95.140000'))
('Eurite', Decimal('109.840000'), Decimal('111.980000'))
('EURC', Decimal('109.860000'), Decimal('111.940000'))
('eUSD', Decimal('93.090000'), Decimal('95.200000'))
('Spiko EU T-Bills Money Market Fund', Decimal('115.320000'), Decimal('117.500000'))
('Everything', Decimal('0.081563'), Decimal('0.082704'))
('Falcon USD', Decimal('92.940000'), Decimal('95.000000'))
('Felix feUSD', Decimal('92.790000'), Decimal('95.130000'))
('Fidelity Digital Dollar', Decimal('93.110000'), Decimal('95.180000'))
('Fidelity Digital Interest Token', Decimal('93.060000'), Decimal('95.200000'))
('Figure Heloc', Decimal('95.820000'), Decimal('98.330000'))
('First Digital USD', Decimal('93.110000'), Decimal('100.070000'))
('Frankencoin', Decimal('119.150000'), Decimal('121.140000'))
('Legacy Frax Dollar', Decimal('92.270000'), Decimal('94.770000'))
('Frax USD', Decimal('93.080000'), Decimal('95.240000'))
('Freedom Dollar', Decimal('93.130000'), Decimal('95.260000'))
('The Game Company', Decimal('18.750000'), Decimal('19.440000'))
('Gauntlet USD Alpha', Decimal('98.850000'), Decimal('101.040000'))
('GHO', Decimal('93.070000'), Decimal('95.120000'))
('GUSD', Decimal('93.010000'), Decimal('95.900000'))
('Circle USYC', Decimal('103.650000'), Decimal('106.250000'))
('Hermetica USDh', Decimal('93.160000'), Decimal('95.250000'))
('Hydrated Dollar', Decimal('92.850000'), Decimal('95.200000'))
('infiniFi Locked iUSD (1week)', Decimal('108.310000'), Decimal('111.360000'))
('Invesco QQQ ETF (Ondo Tokenized ETF)', Decimal('58022.000000'), Decimal('58922.000000'))
('iShares Bitcoin Trust (Ondo Tokenized)', Decimal('3980.110000'), Decimal('4022.870000'))
('iShares Core S&P Total US Stock Market ETF (Ondo Tokenized ETF)', Decimal('14070.790000'), Decimal('14297.590000'))
('iShares MSCI EAFE ETF (Ondo Tokenized ETF)', Decimal('9720.150000'), Decimal('9839.570000'))
('iShares TIPS Bond ETF (Ondo Tokenized ETF)', Decimal('10553.080000'), Decimal('10799.320000'))
('Janus Henderson Anemoy AAA CLO Fund', Decimal('95.900000'), Decimal('97.970000'))
('Janus Henderson Anemoy Treasury Fund', Decimal('102.440000'), Decimal('104.660000'))
('JupUSD', Decimal('93.070000'), Decimal('95.860000'))
('JUSD', Decimal('93.140000'), Decimal('95.170000'))
('LEO Token', Decimal('940.750000'), Decimal('963.610000'))
('BOLD', Decimal('93.230000'), Decimal('95.590000'))
('Liquity USD', Decimal('93.420000'), Decimal('97.620000'))
('Main Street Yield', Decimal('96.720000'), Decimal('98.950000'))
('MegaUSD', Decimal('93.010000'), Decimal('95.130000'))
('MemeCore', Decimal('265.570000'), Decimal('278.970000'))
('MetaMask USD', Decimal('93.100000'), Decimal('96.530000'))
('Micron Technology (Ondo Tokenized Stock)', Decimal('40136.000000'), Decimal('44204.000000'))
('Midas mAPOLLO', Decimal('100.870000'), Decimal('103.040000'))
('Midas mEDGE', Decimal('102.880000'), Decimal('105.160000'))
('Midas mF-ONE', Decimal('100.170000'), Decimal('102.370000'))
('Midas mHYPER', Decimal('101.440000'), Decimal('103.630000'))
('Midas msyrupUSDp', Decimal('97.550000'), Decimal('99.630000'))
('Midas mTBILL', Decimal('98.430000'), Decimal('100.530000'))
('MAI', Decimal('92.680000'), Decimal('98.030000'))
('MimboGameGroup', Decimal('0.280608'), Decimal('0.293933'))
('MNEE USD Stablecoin', Decimal('93.170000'), Decimal('95.210000'))
('Monerium EUR emoney [OLD]', Decimal('109.880000'), Decimal('111.950000'))
('Monerium EUR emoney', Decimal('109.990000'), Decimal('112.350000'))
('Nest Alpha Vault (LP)', Decimal('88.800000'), Decimal('94.200000'))
('Nest Basis Vault', Decimal('98.300000'), Decimal('100.470000'))
('Noble Dollar (USDN)', Decimal('93.090000'), Decimal('95.800000'))
('Noon USN', Decimal('93.190000'), Decimal('102.700000'))
('Neutrl USD', Decimal('93.060000'), Decimal('95.620000'))
('NVIDIA (Ondo Tokenized Stock)', Decimal('17910.400000'), Decimal('18732.020000'))
('Ondo U.S. Dollar Token', Decimal('93.080000'), Decimal('95.200000'))
('Ondo US Dollar Yield', Decimal('104.780000'), Decimal('108.220000'))
('Onchain Yield Coin', Decimal('101.720000'), Decimal('103.970000'))
('OUSG', Decimal('10696.000000'), Decimal('10933.430000'))
('P2P Protocol', Decimal('49.740000'), Decimal('51.390000'))
('Palm USD', Decimal('93.110000'), Decimal('95.160000'))
('Pax Dollar', Decimal('93.090000'), Decimal('99.130000'))
('PayPal USD', Decimal('93.110000'), Decimal('100.800000'))
('Pentagon Chain', Decimal('3743.940000'), Decimal('3805.070000'))
('Pleasing USD', Decimal('92.940000'), Decimal('95.470000'))
('Precious Metals USD', Decimal('92.400000'), Decimal('95.670000'))
('Predictions', Decimal('101.980000'), Decimal('111.640000'))
('PUMPCADE', Decimal('2.860000'), Decimal('2.950000'))
('PumpMeme', Decimal('111.620000'), Decimal('112.870000'))
('RaveDAO', Decimal('1532.020000'), Decimal('1562.290000'))
('Re Protocol reUSD', Decimal('99.820000'), Decimal('101.950000'))
('Ring USD', Decimal('93.140000'), Decimal('97.090000'))
('Ripple USD', Decimal('93.100000'), Decimal('95.220000'))
('Ryze', Decimal('14.400000'), Decimal('15.070000'))
('Securitize Tokenized AAA CLO Fund', Decimal('94167.000000'), Decimal('96245.000000'))
('EUR CoinVertible', Decimal('109.870000'), Decimal('111.880000'))
('SP500 xStock', Decimal('64381.000000'), Decimal('65475.000000'))
('SPDR S&P 500 ETF (Ondo Tokenized ETF)', Decimal('64592.000000'), Decimal('65693.000000'))
('Spiko Digital Assets Cash & Carry Fund', Decimal('94.310000'), Decimal('96.260000'))
('Spiko US T-Bills Money Market Fund', Decimal('100.550000'), Decimal('102.770000'))
('Stable Coin', Decimal('93.080000'), Decimal('95.200000'))
('StandX DUSD', Decimal('93.090000'), Decimal('95.110000'))
('Superfortune', Decimal('58.820000'), Decimal('59.080000'))
('Superstate Short Duration U.S. Government Securities Fund (USTB)', Decimal('1028.670000'), Decimal('1051.020000'))
('Sygnum FIUSD Liquidity Fund', Decimal('1102063.000000'), Decimal('1126526.000000'))
('The9bit', Decimal('2.440000'), Decimal('2.630000'))
('Theo Short Duration US Treasury Fund', Decimal('95.000000'), Decimal('98.660000'))
('Tradable Singapore Fintech SSL', Decimal('93.080000'), Decimal('95.200000'))
('Unity USD', Decimal('93.140000'), Decimal('96.150000'))
('USAT', Decimal('93.150000'), Decimal('95.260000'))
('USDC', Decimal('93.080000'), Decimal('95.180000'))
('USD CoinVertible', Decimal('93.030000'), Decimal('100.530000'))
('USD1', Decimal('93.050000'), Decimal('95.160000'))
('USDa', Decimal('91.500000'), Decimal('93.780000'))
('USDD', Decimal('93.280000'), Decimal('95.170000'))
('USDGO', Decimal('93.080000'), Decimal('95.190000'))
('USDKG', Decimal('93.090000'), Decimal('95.230000'))
('USDtb', Decimal('93.150000'), Decimal('95.660000'))
('USDu', Decimal('93.140000'), Decimal('95.140000'))
('USTBL', Decimal('97.710000'), Decimal('99.930000'))
('USX', Decimal('93.060000'), Decimal('95.560000'))
('VanEck Treasury Fund', Decimal('93.110000'), Decimal('95.200000'))
('VCRED', Decimal('93.070000'), Decimal('95.070000'))
('Worldwide USD', Decimal('93.010000'), Decimal('95.100000'))
('WYDE: End Hunger', Decimal('0.092066'), Decimal('0.092841'))
('Yield Optimizer USD', Decimal('100.350000'), Decimal('102.570000'))
('YLDS', Decimal('93.090000'), Decimal('95.180000'))
('Zama', Decimal('3.480000'), Decimal('3.820000'))

In [36]:
#Find the average market cap rank of coins with volume above $1B
cursor.execute("""
SELECT name, total_volume
FROM cryptocurrencies
ORDER BY total_volume DESC
LIMIT 10
""")

for row in cursor.fetchall():
    print(row)

('Tether', 9020260876145)
('Bitcoin', 5639520659546)
('Ethereum', 2657245525720)
('USDC', 1926199489804)
('Solana', 465637572196)
('XRP', 283785036162)
('Dogecoin', 199425581284)
('USD1', 147918877099)
('BNB', 140420868514)
('RaveDAO', 68357774705)

In [39]:
# 5.Get the most recently updated coin.
cursor.execute("""
SELECT name, current_price, date
FROM cryptocurrencies
WHERE date = (SELECT MAX(date) FROM cryptocurrencies)
""")

for row in cursor.fetchall():
    print(row)

('0x Protocol', Decimal('9.990000'), datetime.date(2026, 4, 14))
('1INCH', Decimal('8.940000'), datetime.date(2026, 4, 14))
('4', Decimal('1.076000'), datetime.date(2026, 4, 14))
('A7A5', Decimal('1.160000'), datetime.date(2026, 4, 14))
('Aave', Decimal('9412.770000'), datetime.date(2026, 4, 14))
('Abelian', Decimal('9.040000'), datetime.date(2026, 4, 14))
('Achain', Decimal('1.210000'), datetime.date(2026, 4, 14))
('Across Protocol', Decimal('4.000000'), datetime.date(2026, 4, 14))
('Act I The AI Prophecy', Decimal('1.220000'), datetime.date(2026, 4, 14))
('heyAura', Decimal('7.090000'), datetime.date(2026, 4, 14))
('ADI', Decimal('401.650000'), datetime.date(2026, 4, 14))
('Aegis YUSD', Decimal('92.950000'), datetime.date(2026, 4, 14))
('aelf', Decimal('7.410000'), datetime.date(2026, 4, 14))
('Aergo', Decimal('5.110000'), datetime.date(2026, 4, 14))
('Aerodrome Finance', Decimal('36.010000'), datetime.date(2026, 4, 14))
('Aethir', Decimal('0.576438'), datetime.date(2026, 4, 14))
('affine', Decimal('1856.650000'), datetime.date(2026, 4, 14))
('AgentFun.AI', Decimal('57.450000'), datetime.date(2026, 4, 14))
('AUSD', Decimal('93.090000'), datetime.date(2026, 4, 14))
('AhaToken', Decimal('0.143935'), datetime.date(2026, 4, 14))
('AI Analysis Token', Decimal('22.950000'), datetime.date(2026, 4, 14))
('AI Companions', Decimal('2.500000'), datetime.date(2026, 4, 14))
('AI Rig Complex', Decimal('6.800000'), datetime.date(2026, 4, 14))
('DeAgentAI', Decimal('10.410000'), datetime.date(2026, 4, 14))
('AIntivirus', Decimal('2.860000'), datetime.date(2026, 4, 14))
('AIOZ Network', Decimal('5.370000'), datetime.date(2026, 4, 14))
('aixbt', Decimal('2.320000'), datetime.date(2026, 4, 14))
('Akash Network', Decimal('42.290000'), datetime.date(2026, 4, 14))
('Alchemist AI', Decimal('6.030000'), datetime.date(2026, 4, 14))
('Alchemix', Decimal('484.750000'), datetime.date(2026, 4, 14))
('Alchemy Pay', Decimal('0.566028'), datetime.date(2026, 4, 14))
('ALEO', Decimal('4.570000'), datetime.date(2026, 4, 14))
('Algorand', Decimal('10.400000'), datetime.date(2026, 4, 14))
('Alien Worlds', Decimal('0.153557'), datetime.date(2026, 4, 14))
('Allora', Decimal('10.510000'), datetime.date(2026, 4, 14))
('Alloy Tether', Decimal('93.000000'), datetime.date(2026, 4, 14))
('Alpha Fi', Decimal('96.480000'), datetime.date(2026, 4, 14))
('Alphabet Class A (Ondo Tokenized Stock)', Decimal('30431.000000'), datetime.date(2026, 4, 14))
('AltLayer', Decimal('0.635041'), datetime.date(2026, 4, 14))
('Altura Vault Tokens', Decimal('98.030000'), datetime.date(2026, 4, 14))
('America Party', Decimal('0.000007'), datetime.date(2026, 4, 14))
('Amiko', Decimal('3.770000'), datetime.date(2026, 4, 14))
('Amp', Decimal('0.082568'), datetime.date(2026, 4, 14))
('ANDY ETH', Decimal('0.000866'), datetime.date(2026, 4, 14))
('ANDY70B', Decimal('1.061000'), datetime.date(2026, 4, 14))
('Animecoin', Decimal('0.433817'), datetime.date(2026, 4, 14))
('Ankr Network', Decimal('0.478947'), datetime.date(2026, 4, 14))
('Anvil', Decimal('0.053586'), datetime.date(2026, 4, 14))
('Anzen USDz', Decimal('92.390000'), datetime.date(2026, 4, 14))
('Anzens USDA', Decimal('93.810000'), datetime.date(2026, 4, 14))
('Ape and Pepe', Decimal('0.000117'), datetime.date(2026, 4, 14))
('ApeCoin', Decimal('8.280000'), datetime.date(2026, 4, 14))
('AINFT', Decimal('0.000031'), datetime.date(2026, 4, 14))
('APES', Decimal('7.060000'), datetime.date(2026, 4, 14))
('APEX', Decimal('1.840000'), datetime.date(2026, 4, 14))
('Apex', Decimal('261.100000'), datetime.date(2026, 4, 14))
('APEX', Decimal('26.430000'), datetime.date(2026, 4, 14))
('Api3', Decimal('26.750000'), datetime.date(2026, 4, 14))
('Apollo Diversified Credit Securitize Fund', Decimal('101746.000000'), datetime.date(2026, 4, 14))
('aPriori', Decimal('23.820000'), datetime.date(2026, 4, 14))
('Apro', Decimal('15.760000'), datetime.date(2026, 4, 14))
('Aptos', Decimal('80.690000'), datetime.date(2026, 4, 14))
('Apu Apustaja', Decimal('0.003213'), datetime.date(2026, 4, 14))
('apxUSD', Decimal('93.090000'), datetime.date(2026, 4, 14))
('apyUSD', Decimal('125.020000'), datetime.date(2026, 4, 14))
('Aquarius', Decimal('0.032303'), datetime.date(2026, 4, 14))
('Arbitrum', Decimal('10.360000'), datetime.date(2026, 4, 14))
('Arcblock', Decimal('30.970000'), datetime.date(2026, 4, 14))
('Ardor', Decimal('4.020000'), datetime.date(2026, 4, 14))
('Argentine Football Association Fan Token', Decimal('60.290000'), datetime.date(2026, 4, 14))
('Aria.AI', Decimal('89.450000'), datetime.date(2026, 4, 14))
('ARK', Decimal('15.790000'), datetime.date(2026, 4, 14))
('Arkham', Decimal('9.450000'), datetime.date(2026, 4, 14))
('Arsenal Fan Token', Decimal('44.380000'), datetime.date(2026, 4, 14))
('Arweave', Decimal('165.300000'), datetime.date(2026, 4, 14))
('AS Roma Fan Token', Decimal('115.710000'), datetime.date(2026, 4, 14))
('AscendEx', Decimal('1.450000'), datetime.date(2026, 4, 14))
('Assemble AI', Decimal('0.629618'), datetime.date(2026, 4, 14))
('Astar', Decimal('0.708047'), datetime.date(2026, 4, 14))
('Aster', Decimal('64.010000'), datetime.date(2026, 4, 14))
('Aster USDF', Decimal('93.000000'), datetime.date(2026, 4, 14))
('Atletico Madrid Fan Token', Decimal('106.480000'), datetime.date(2026, 4, 14))
('AtomOne', Decimal('29.730000'), datetime.date(2026, 4, 14))
('Atoshi', Decimal('3.670000'), datetime.date(2026, 4, 14))
('Bounce', Decimal('445.790000'), datetime.date(2026, 4, 14))
('Audiera', Decimal('36.400000'), datetime.date(2026, 4, 14))
('Autonolas', Decimal('4.200000'), datetime.date(2026, 4, 14))
('Autonomi', Decimal('9.430000'), datetime.date(2026, 4, 14))
('Avalanche', Decimal('884.440000'), datetime.date(2026, 4, 14))
('Avalaunch', Decimal('27.020000'), datetime.date(2026, 4, 14))
('Avant USD', Decimal('93.060000'), datetime.date(2026, 4, 14))
('Avantis', Decimal('12.430000'), datetime.date(2026, 4, 14))
('Axelar', Decimal('4.290000'), datetime.date(2026, 4, 14))
('Axie Infinity', Decimal('104.230000'), datetime.date(2026, 4, 14))
('Aztec', Decimal('2.130000'), datetime.date(2026, 4, 14))
('B3 (Base)', Decimal('0.029043'), datetime.date(2026, 4, 14))
('Baby Doge Coin', Decimal('0.000000'), datetime.date(2026, 4, 14))
('BabyBoomToken', Decimal('20.450000'), datetime.date(2026, 4, 14))
('Babylon', Decimal('1.360000'), datetime.date(2026, 4, 14))
('Backpack', Decimal('13.500000'), datetime.date(2026, 4, 14))
('Balancer', Decimal('15.020000'), datetime.date(2026, 4, 14))
('Bald', Decimal('1.250000'), datetime.date(2026, 4, 14))
('Balsa MM Fund', Decimal('7.630000'), datetime.date(2026, 4, 14))
('Banana For Scale', Decimal('1.029000'), datetime.date(2026, 4, 14))
('Bancor Network', Decimal('28.840000'), datetime.date(2026, 4, 14))
('Band', Decimal('19.260000'), datetime.date(2026, 4, 14))
('BankrCoin', Decimal('0.036644'), datetime.date(2026, 4, 14))
('Brett', Decimal('0.676050'), datetime.date(2026, 4, 14))
('BasedHype', Decimal('0.678799'), datetime.date(2026, 4, 14))
('Basic Attention', Decimal('9.080000'), datetime.date(2026, 4, 14))
('BCGame Coin', Decimal('1.001000'), datetime.date(2026, 4, 14))
('Beam', Decimal('0.175481'), datetime.date(2026, 4, 14))
('Bedrock', Decimal('11.080000'), datetime.date(2026, 4, 14))
('Beldex', Decimal('7.470000'), datetime.date(2026, 4, 14))
('BENQI', Decimal('0.141713'), datetime.date(2026, 4, 14))
('Berachain', Decimal('38.310000'), datetime.date(2026, 4, 14))
('Bertram The Pomeranian', Decimal('0.880203'), datetime.date(2026, 4, 14))
('BFUSD', Decimal('93.070000'), datetime.date(2026, 4, 14))
('币安人生 (BinanceLife)', Decimal('32.780000'), datetime.date(2026, 4, 14))
('Big Dog Fink', Decimal('0.007381'), datetime.date(2026, 4, 14))
('BIM', Decimal('140.780000'), datetime.date(2026, 4, 14))
('BUSD', Decimal('93.020000'), datetime.date(2026, 4, 14))
('BNB', Decimal('57937.000000'), datetime.date(2026, 4, 14))
('Bio Protocol', Decimal('1.800000'), datetime.date(2026, 4, 14))
('bitcastle Token', Decimal('18.680000'), datetime.date(2026, 4, 14))
('Bitcoin', Decimal('7029893.000000'), datetime.date(2026, 4, 14))
('Bitcoin Cash', Decimal('41212.000000'), datetime.date(2026, 4, 14))
('Bitcoin SV', Decimal('1456.060000'), datetime.date(2026, 4, 14))
('BitDCA', Decimal('63.850000'), datetime.date(2026, 4, 14))
('Bitget Token', Decimal('178.640000'), datetime.date(2026, 4, 14))
('KUB Coin', Decimal('79.110000'), datetime.date(2026, 4, 14))
('BitMart', Decimal('29.940000'), datetime.date(2026, 4, 14))
('BitMEX', Decimal('8.870000'), datetime.date(2026, 4, 14))
('Bitgert', Decimal('0.000002'), datetime.date(2026, 4, 14))
('Bittensor', Decimal('23472.000000'), datetime.date(2026, 4, 14))
('BitTorrent', Decimal('0.000031'), datetime.date(2026, 4, 14))
('Bitway', Decimal('1.550000'), datetime.date(2026, 4, 14))
('BlackRock USD Institutional Digital Liquidity Fund', Decimal('93.080000'), datetime.date(2026, 4, 14))
('Blast', Decimal('0.045512'), datetime.date(2026, 4, 14))
('Bless', Decimal('1.700000'), datetime.date(2026, 4, 14))
('Block Street', Decimal('22.180000'), datetime.date(2026, 4, 14))
('Blockchain Capital', Decimal('7703.390000'), datetime.date(2026, 4, 14))
('Stacks', Decimal('20.870000'), datetime.date(2026, 4, 14))
('BLOCKv', Decimal('1.400000'), datetime.date(2026, 4, 14))
('Blur', Decimal('1.950000'), datetime.date(2026, 4, 14))
('Bluwhale', Decimal('0.867223'), datetime.date(2026, 4, 14))
('KOGE', Decimal('4470.730000'), datetime.date(2026, 4, 14))
('Boba Network', Decimal('2.120000'), datetime.date(2026, 4, 14))
('Bonk', Decimal('0.000562'), datetime.date(2026, 4, 14))
('BOOK OF MEME', Decimal('0.039753'), datetime.date(2026, 4, 14))
('BORA', Decimal('3.400000'), datetime.date(2026, 4, 14))
('BOTXCOIN', Decimal('58.930000'), datetime.date(2026, 4, 14))
('BounceBit', Decimal('2.340000'), datetime.date(2026, 4, 14))
('Brevis', Decimal('11.390000'), datetime.date(2026, 4, 14))
('Brazilian Digital', Decimal('18.670000'), datetime.date(2026, 4, 14))
('BSquared Network', Decimal('64.240000'), datetime.date(2026, 4, 14))
('BTSE Token', Decimal('104.940000'), datetime.date(2026, 4, 14))
('Bucket Protocol BUCK Stablecoin', Decimal('93.100000'), datetime.date(2026, 4, 14))
('BugsCoin', Decimal('0.114671'), datetime.date(2026, 4, 14))
('BUILDon', Decimal('10.530000'), datetime.date(2026, 4, 14))
('BurnedFi', Decimal('370.060000'), datetime.date(2026, 4, 14))
('Buttcoin', Decimal('1.140000'), datetime.date(2026, 4, 14))
('Maya Protocol', Decimal('10.110000'), datetime.date(2026, 4, 14))
('Canton', Decimal('14.510000'), datetime.date(2026, 4, 14))
('Cap USD', Decimal('93.050000'), datetime.date(2026, 4, 14))
('Cardano', Decimal('23.140000'), datetime.date(2026, 4, 14))
('Carrot', Decimal('6516.430000'), datetime.date(2026, 4, 14))
('Cartesi', Decimal('2.890000'), datetime.date(2026, 4, 14))
('CARV', Decimal('5.010000'), datetime.date(2026, 4, 14))
('CASH', Decimal('93.070000'), datetime.date(2026, 4, 14))
('Casper Network', Decimal('0.273252'), datetime.date(2026, 4, 14))
('cat in a dogs world', Decimal('0.054324'), datetime.date(2026, 4, 14))
('CATX', Decimal('0.001147'), datetime.date(2026, 4, 14))
('Celer Network', Decimal('0.222490'), datetime.date(2026, 4, 14))
('Celestia', Decimal('29.120000'), datetime.date(2026, 4, 14))
('lium', Decimal('1172.810000'), datetime.date(2026, 4, 14))
('Celo', Decimal('7.540000'), datetime.date(2026, 4, 14))
('Centrifuge', Decimal('19.170000'), datetime.date(2026, 4, 14))
('Shentu', Decimal('16.200000'), datetime.date(2026, 4, 14))
('Onyxcoin', Decimal('0.439495'), datetime.date(2026, 4, 14))
('Chainbase', Decimal('6.440000'), datetime.date(2026, 4, 14))
('Chainlink', Decimal('860.520000'), datetime.date(2026, 4, 14))
('ChainOpera AI', Decimal('38.350000'), datetime.date(2026, 4, 14))
('ChangeNOW', Decimal('56.220000'), datetime.date(2026, 4, 14))
('Checkmate', Decimal('3.710000'), datetime.date(2026, 4, 14))
('Cheems Token', Decimal('0.000050'), datetime.date(2026, 4, 14))
('Chia', Decimal('208.590000'), datetime.date(2026, 4, 14))
('Chiliz', Decimal('3.430000'), datetime.date(2026, 4, 14))
('Chutes', Decimal('2052.850000'), datetime.date(2026, 4, 14))
('Circle Internet Group (Ondo Tokenized Stock)', Decimal('9979.180000'), datetime.date(2026, 4, 14))
('Circle xStock', Decimal('9959.120000'), datetime.date(2026, 4, 14))
('Civic', Decimal('2.800000'), datetime.date(2026, 4, 14))
('CJournal', Decimal('1.550000'), datetime.date(2026, 4, 14))
('Clash of Lilliput', Decimal('14.040000'), datetime.date(2026, 4, 14))
('Cobak', Decimal('23.050000'), datetime.date(2026, 4, 14))
('Codatta', Decimal('0.481657'), datetime.date(2026, 4, 14))
('CoinEx', Decimal('2.760000'), datetime.date(2026, 4, 14))
('Comedian', Decimal('7.780000'), datetime.date(2026, 4, 14))
('CommonWealth', Decimal('3.020000'), datetime.date(2026, 4, 14))
('Compound', Decimal('1932.300000'), datetime.date(2026, 4, 14))
('Compounding OpenDollar', Decimal('97.290000'), datetime.date(2026, 4, 14))
('Concordium', Decimal('0.433490'), datetime.date(2026, 4, 14))
('Conflux', Decimal('5.070000'), datetime.date(2026, 4, 14))
('WalletConnect Token', Decimal('5.340000'), datetime.date(2026, 4, 14))
('Constellation', Decimal('0.817114'), datetime.date(2026, 4, 14))
('ConstitutionDAO', Decimal('0.675316'), datetime.date(2026, 4, 14))
('Convex Finance', Decimal('170.170000'), datetime.date(2026, 4, 14))
('Cookie DAO', Decimal('1.490000'), datetime.date(2026, 4, 14))
('Core', Decimal('2.460000'), datetime.date(2026, 4, 14))
('CorgiAI', Decimal('0.003320'), datetime.date(2026, 4, 14))
('Cosmos Hub', Decimal('165.680000'), datetime.date(2026, 4, 14))
('COTI', Decimal('1.270000'), datetime.date(2026, 4, 14))
('CoW Protocol', Decimal('20.790000'), datetime.date(2026, 4, 14))
('Creditcoin', Decimal('13.700000'), datetime.date(2026, 4, 14))
('CREPE', Decimal('0.001334'), datetime.date(2026, 4, 14))
('Crob Mob', Decimal('0.911245'), datetime.date(2026, 4, 14))
('CROSS', Decimal('7.160000'), datetime.date(2026, 4, 14))
('Crown BRLV', Decimal('18.710000'), datetime.date(2026, 4, 14))
('crvUSD', Decimal('93.110000'), datetime.date(2026, 4, 14))
('Cronos', Decimal('6.580000'), datetime.date(2026, 4, 14))
('Curve DAO', Decimal('20.590000'), datetime.date(2026, 4, 14))
('CYBER', Decimal('47.640000'), datetime.date(2026, 4, 14))
('Cygnus Finance Global USD', Decimal('92.660000'), datetime.date(2026, 4, 14))
('Cysic', Decimal('32.300000'), datetime.date(2026, 4, 14))
('Dacxi', Decimal('0.041818'), datetime.date(2026, 4, 14))
('Dai', Decimal('93.050000'), datetime.date(2026, 4, 14))
('DAI on PulseChain', Decimal('0.143858'), datetime.date(2026, 4, 14))
('DAO Maker', Decimal('4.480000'), datetime.date(2026, 4, 14))
('Dash', Decimal('3769.670000'), datetime.date(2026, 4, 14))
('Data Universe', Decimal('194.750000'), datetime.date(2026, 4, 14))
('DEAPCOIN', Decimal('0.104142'), datetime.date(2026, 4, 14))
('deBridge', Decimal('1.320000'), datetime.date(2026, 4, 14))
('Decentraland', Decimal('8.100000'), datetime.date(2026, 4, 14))
('Decred', Decimal('2040.680000'), datetime.date(2026, 4, 14))
('DeepBook', Decimal('2.740000'), datetime.date(2026, 4, 14))
('Defi.money', Decimal('92.840000'), datetime.date(2026, 4, 14))
('Definitive', Decimal('10.900000'), datetime.date(2026, 4, 14))
('Degen', Decimal('0.068198'), datetime.date(2026, 4, 14))
('Delysium', Decimal('1.060000'), datetime.date(2026, 4, 14))
('Derive', Decimal('8.330000'), datetime.date(2026, 4, 14))
('Decentralized Social', Decimal('459.340000'), datetime.date(2026, 4, 14))
('DeXe', Decimal('934.170000'), datetime.date(2026, 4, 14))
('DexTools', Decimal('12.900000'), datetime.date(2026, 4, 14))
('Dialectic USD Vault', Decimal('94.770000'), datetime.date(2026, 4, 14))
('Diverge Loop', Decimal('1.400000'), datetime.date(2026, 4, 14))
('Diem', Decimal('110246.000000'), datetime.date(2026, 4, 14))
('DigiByte', Decimal('0.440207'), datetime.date(2026, 4, 14))
('Dinero', Decimal('1.110000'), datetime.date(2026, 4, 14))
('Dippy', Decimal('295.470000'), datetime.date(2026, 4, 14))
('dKargo', Decimal('0.639873'), datetime.date(2026, 4, 14))
('Dog (Bitcoin)', Decimal('0.068368'), datetime.date(2026, 4, 14))
('Dogecoin', Decimal('9.080000'), datetime.date(2026, 4, 14))
('Dogelon Mars', Decimal('0.000004'), datetime.date(2026, 4, 14))
('dogwifhat', Decimal('18.540000'), datetime.date(2026, 4, 14))
('DOLA', Decimal('92.460000'), datetime.date(2026, 4, 14))
('DoubleZero', Decimal('7.490000'), datetime.date(2026, 4, 14))
('DOVU', Decimal('0.228521'), datetime.date(2026, 4, 14))
('Drift Protocol', Decimal('4.070000'), datetime.date(2026, 4, 14))
('Dual', Decimal('0.692547'), datetime.date(2026, 4, 14))
('Dupe', Decimal('1.035000'), datetime.date(2026, 4, 14))
('DUSK', Decimal('13.810000'), datetime.date(2026, 4, 14))
('dYdX', Decimal('9.060000'), datetime.date(2026, 4, 14))
('EarthMeta', Decimal('0.542618'), datetime.date(2026, 4, 14))
('eBTC', Decimal('7003828.000000'), datetime.date(2026, 4, 14))
('eCash', Decimal('0.000650'), datetime.date(2026, 4, 14))
('Eclipse', Decimal('15.000000'), datetime.date(2026, 4, 14))
('ECOMI', Decimal('0.012430'), datetime.date(2026, 4, 14))
('edgeX', Decimal('89.360000'), datetime.date(2026, 4, 14))
('Open Campus', Decimal('4.520000'), datetime.date(2026, 4, 14))
('EigenCloud (prev. EigenLayer)', Decimal('15.320000'), datetime.date(2026, 4, 14))
('Ekubo Protocol', Decimal('88.710000'), datetime.date(2026, 4, 14))
('Elastos', Decimal('41.970000'), datetime.date(2026, 4, 14))
('Ellipsis [OLD]', Decimal('1.310000'), datetime.date(2026, 4, 14))
('MultiversX', Decimal('356.110000'), datetime.date(2026, 4, 14))
('ELYSIA', Decimal('0.169687'), datetime.date(2026, 4, 14))
('Ember Third Eye', Decimal('95.930000'), datetime.date(2026, 4, 14))
('Fusionist', Decimal('10.500000'), datetime.date(2026, 4, 14))
('Energy Web Token', Decimal('41.910000'), datetime.date(2026, 4, 14))
('Enjin Coin', Decimal('4.360000'), datetime.date(2026, 4, 14))
('Enosys Loans CDP', Decimal('93.710000'), datetime.date(2026, 4, 14))
('Epic Chain', Decimal('25.910000'), datetime.date(2026, 4, 14))
('Ergo', Decimal('29.090000'), datetime.date(2026, 4, 14))
('Escoin', Decimal('27.060000'), datetime.date(2026, 4, 14))
('Espresso', Decimal('7.140000'), datetime.date(2026, 4, 14))
('eSui Dollar', Decimal('93.070000'), datetime.date(2026, 4, 14))
('Ethena', Decimal('8.980000'), datetime.date(2026, 4, 14))
('Ethena USDe', Decimal('93.120000'), datetime.date(2026, 4, 14))
('Ether.fi', Decimal('40.920000'), datetime.date(2026, 4, 14))
('Ethereum', Decimal('222636.000000'), datetime.date(2026, 4, 14))
('Ethereum Classic', Decimal('791.010000'), datetime.date(2026, 4, 14))
('Ethereum Name Service', Decimal('551.230000'), datetime.date(2026, 4, 14))
('EthereumPoW', Decimal('24.190000'), datetime.date(2026, 4, 14))
('ETHGas', Decimal('6.100000'), datetime.date(2026, 4, 14))
('Ethix', Decimal('14.790000'), datetime.date(2026, 4, 14))
('Euler', Decimal('110.560000'), datetime.date(2026, 4, 14))
('Eurite', Decimal('109.840000'), datetime.date(2026, 4, 14))
('EURC', Decimal('109.860000'), datetime.date(2026, 4, 14))
('eUSD', Decimal('93.090000'), datetime.date(2026, 4, 14))
('Spiko EU T-Bills Money Market Fund', Decimal('115.320000'), datetime.date(2026, 4, 14))
('IQ', Decimal('0.101493'), datetime.date(2026, 4, 14))
('Everlyn', Decimal('4.970000'), datetime.date(2026, 4, 14))
('Everything', Decimal('0.081563'), datetime.date(2026, 4, 14))
('EXOD', Decimal('639.470000'), datetime.date(2026, 4, 14))
('Falcon USD', Decimal('92.940000'), datetime.date(2026, 4, 14))
('Falcon Finance', Decimal('7.360000'), datetime.date(2026, 4, 14))
('FAR Labs', Decimal('0.262930'), datetime.date(2026, 4, 14))
('Fartcoin', Decimal('20.370000'), datetime.date(2026, 4, 14))
('FC Barcelona Fan Token', Decimal('51.410000'), datetime.date(2026, 4, 14))
('FC Porto', Decimal('90.130000'), datetime.date(2026, 4, 14))
('Felix feUSD', Decimal('92.790000'), datetime.date(2026, 4, 14))
('Felysyum', Decimal('24.660000'), datetime.date(2026, 4, 14))

In [ ]:
#2️⃣ crypto_prices (daily prices of top coins)

In [42]:
#Find the highest daily price of Bitcoin in the last 365 days.
cursor.execute("""
SELECT 
    coin_id,
    MAX(price_inr) AS highest_price
FROM crypto_prices
WHERE coin_id = 'bitcoin'
""")

for row in cursor.fetchall():
    print(row)

('bitcoin', Decimal('11070472.246733'))

In [43]:
#Calculate the average daily price of Ethereum in the past 1 year.
cursor.execute("""
SELECT 
    coin_id,
    ROUND(AVG(price_inr), 2) AS avg_price
FROM crypto_prices
WHERE coin_id = 'ethereum'
""")

for row in cursor.fetchall():
    print(row)

('ethereum', Decimal('267001.88'))

In [48]:
#Show the daily price trend of Bitcoin in January 2025. (or change the month and year according you your data)
cursor.execute("""
SELECT date, price_inr
FROM crypto_prices
WHERE coin_id = 'bitcoin'

-- Last 30 days automatically
AND date >= DATE_SUB((SELECT MAX(date) FROM crypto_prices), INTERVAL 30 DAY)

ORDER BY date
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2026, 3, 15), Decimal('6593624.616147'))
(datetime.date(2026, 3, 16), Decimal('6727548.658016'))
(datetime.date(2026, 3, 17), Decimal('6906940.623961'))
(datetime.date(2026, 3, 18), Decimal('6829860.404015'))
(datetime.date(2026, 3, 19), Decimal('6639390.135900'))
(datetime.date(2026, 3, 20), Decimal('6504037.303026'))
(datetime.date(2026, 3, 21), Decimal('6635372.108167'))
(datetime.date(2026, 3, 22), Decimal('6461678.631620'))
(datetime.date(2026, 3, 23), Decimal('6364717.089252'))
(datetime.date(2026, 3, 24), Decimal('6614293.785504'))
(datetime.date(2026, 3, 25), Decimal('6649392.307316'))
(datetime.date(2026, 3, 26), Decimal('6712173.732416'))
(datetime.date(2026, 3, 27), Decimal('6487672.474785'))
(datetime.date(2026, 3, 28), Decimal('6291490.149057'))
(datetime.date(2026, 3, 29), Decimal('6286074.723244'))
(datetime.date(2026, 3, 30), Decimal('6252812.763420'))
(datetime.date(2026, 3, 31), Decimal('6293233.346703'))
(datetime.date(2026, 4, 1), Decimal('6378628.791276'))
(datetime.date(2026, 4, 2), Decimal('6307964.144412'))
(datetime.date(2026, 4, 3), Decimal('6219175.587859'))
(datetime.date(2026, 4, 4), Decimal('6209570.020236'))
(datetime.date(2026, 4, 5), Decimal('6257848.032767'))
(datetime.date(2026, 4, 6), Decimal('6414170.630917'))
(datetime.date(2026, 4, 7), Decimal('6401867.152928'))
(datetime.date(2026, 4, 8), Decimal('6683688.621063'))
(datetime.date(2026, 4, 9), Decimal('6562922.404613'))
(datetime.date(2026, 4, 10), Decimal('6636645.267469'))
(datetime.date(2026, 4, 11), Decimal('6794200.621616'))
(datetime.date(2026, 4, 12), Decimal('6801700.513611'))
(datetime.date(2026, 4, 13), Decimal('6685979.115011'))
(datetime.date(2026, 4, 14), Decimal('7073662.431479'))
(datetime.date(2026, 4, 14), Decimal('6901117.665664'))

In [49]:
#Find the coin with the highest average price over 1 year.
cursor.execute("""
SELECT coin_id, AVG(price_inr) AS avg_price
FROM crypto_prices

-- Group data for each coin
GROUP BY coin_id

-- Sort by highest average price
ORDER BY avg_price DESC

-- Take top coin
LIMIT 1
""")

for row in cursor.fetchall():
    print(row)

('bitcoin', Decimal('8566681.4082241366'))

In [52]:
#Get the % change in Bitcoin’s price between Sep 2024 and Sep 2025
cursor.execute("""
SELECT 
(
    MAX(price_inr) - MIN(price_inr)
) / MIN(price_inr) * 100 AS percentage_change

FROM crypto_prices
WHERE coin_id = 'bitcoin'
""")

for row in cursor.fetchall():
    print(row)

(Decimal('95.0182427944'),)

In [ ]:
#3️⃣ oil_prices

In [54]:
#Find the highest oil price in the last 5 years.
cursor.execute("""
SELECT date, price_inr
FROM oil_prices
ORDER BY price_inr DESC
LIMIT 1
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2022, 3, 8), Decimal('10262.120000'))

In [56]:
#Get the average oil price per year.
cursor.execute("""
SELECT 
    YEAR(date) AS year,
    ROUND(AVG(price_inr), 2) AS avg_price
FROM oil_prices
GROUP BY YEAR(date)
ORDER BY year
""")

for row in cursor.fetchall():
    print(row)

(2020, Decimal('3250.32'))
(2021, Decimal('5655.21'))
(2022, Decimal('7876.94'))
(2023, Decimal('6438.85'))
(2024, Decimal('6360.48'))
(2025, Decimal('5427.21'))
(2026, Decimal('6180.88'))

In [59]:
#Show oil prices during COVID crash (March–April 2020).
cursor.execute("""
SELECT date, price_inr
FROM oil_prices

-- Filter COVID crash period
WHERE date BETWEEN '2020-03-01' AND '2020-04-30'

-- Sort by date
ORDER BY date
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2020, 3, 2), Decimal('3882.740000'))
(datetime.date(2020, 3, 3), Decimal('3923.410000'))
(datetime.date(2020, 3, 4), Decimal('3882.740000'))
(datetime.date(2020, 3, 5), Decimal('3809.700000'))
(datetime.date(2020, 3, 6), Decimal('3414.620000'))
(datetime.date(2020, 3, 9), Decimal('2577.150000'))
(datetime.date(2020, 3, 10), Decimal('2861.010000'))
(datetime.date(2020, 3, 11), Decimal('2749.790000'))
(datetime.date(2020, 3, 12), Decimal('2619.480000'))
(datetime.date(2020, 3, 13), Decimal('2632.760000'))
(datetime.date(2020, 3, 16), Decimal('2403.680000'))
(datetime.date(2020, 3, 17), Decimal('2237.680000'))
(datetime.date(2020, 3, 18), Decimal('1699.840000'))
(datetime.date(2020, 3, 19), Decimal('2082.470000'))
(datetime.date(2020, 3, 20), Decimal('1616.840000'))
(datetime.date(2020, 3, 23), Decimal('1936.390000'))
(datetime.date(2020, 3, 24), Decimal('1745.490000'))
(datetime.date(2020, 3, 25), Decimal('1722.250000'))
(datetime.date(2020, 3, 26), Decimal('1377.800000'))
(datetime.date(2020, 3, 27), Decimal('1284.840000'))
(datetime.date(2020, 3, 30), Decimal('1170.300000'))
(datetime.date(2020, 3, 31), Decimal('1702.330000'))
(datetime.date(2020, 4, 1), Decimal('1683.240000'))
(datetime.date(2020, 4, 2), Decimal('2089.940000'))
(datetime.date(2020, 4, 3), Decimal('2353.880000'))
(datetime.date(2020, 4, 6), Decimal('2175.430000'))
(datetime.date(2020, 4, 7), Decimal('1953.820000'))
(datetime.date(2020, 4, 8), Decimal('2072.510000'))
(datetime.date(2020, 4, 9), Decimal('1900.700000'))
(datetime.date(2020, 4, 13), Decimal('1855.880000'))
(datetime.date(2020, 4, 14), Decimal('1672.450000'))
(datetime.date(2020, 4, 15), Decimal('1656.680000'))
(datetime.date(2020, 4, 16), Decimal('1645.060000'))
(datetime.date(2020, 4, 17), Decimal('1519.730000'))
(datetime.date(2020, 4, 20), Decimal('-3069.340000'))
(datetime.date(2020, 4, 21), Decimal('739.530000'))
(datetime.date(2020, 4, 22), Decimal('1132.120000'))
(datetime.date(2020, 4, 23), Decimal('1249.980000'))
(datetime.date(2020, 4, 24), Decimal('1327.170000'))
(datetime.date(2020, 4, 27), Decimal('1010.110000'))
(datetime.date(2020, 4, 28), Decimal('1029.200000'))
(datetime.date(2020, 4, 29), Decimal('1248.320000'))
(datetime.date(2020, 4, 30), Decimal('1596.090000'))

In [65]:
#Find the lowest price of oil in the last 10 years.
cursor.execute("""
SELECT date, price_inr
FROM oil_prices
WHERE price_inr > 0
ORDER BY price_inr ASC
LIMIT 1
""")

print(cursor.fetchall())

[(datetime.date(2020, 4, 21), Decimal('739.530000'))]

In [66]:
#Calculate the volatility of oil prices (max-min difference per year).
cursor.execute("""
SELECT 
    YEAR(date) AS year,

    -- Highest price in that year
    MAX(price_inr) AS max_price,

    -- Lowest price in that year
    MIN(price_inr) AS min_price,

    -- Volatility = max - min
    (MAX(price_inr) - MIN(price_inr)) AS volatility

FROM oil_prices

-- Group data year-wise
GROUP BY YEAR(date)

-- Sort by year
ORDER BY year
""")

for row in cursor.fetchall():
    print(row)

(2020, Decimal('5251.410000'), Decimal('-3069.340000'), Decimal('8320.750000'))
(2021, Decimal('7108.120000'), Decimal('3940.010000'), Decimal('3168.110000'))
(2022, Decimal('10262.120000'), Decimal('5897.150000'), Decimal('4364.970000'))
(2023, Decimal('7774.610000'), Decimal('5528.630000'), Decimal('2245.980000'))
(2024, Decimal('7278.270000'), Decimal('5538.590000'), Decimal('1739.680000'))
(2025, Decimal('6700.590000'), Decimal('4601.520000'), Decimal('2099.070000'))
(2026, Decimal('9462.830000'), Decimal('4648.830000'), Decimal('4814.000000'))

In [ ]:
#4️⃣ stock_prices

In [74]:
#Get all stock prices for a given ticker
cursor.execute("""
SELECT 
    ticker,          -- stock/index name
    Date,            -- date of trading
    Close            -- closing price
FROM stock_prices

-- remove missing values (market closed days)
WHERE Close IS NOT NULL

-- sort properly: first by ticker, then by date
ORDER BY ticker, Date
""")

# Fetch and print results
for row in cursor.fetchall():
    print(row)

('^GSPC', datetime.date(2020, 1, 2), Decimal('3257.850098'))
('^GSPC', datetime.date(2020, 1, 3), Decimal('3234.850098'))
('^GSPC', datetime.date(2020, 1, 6), Decimal('3246.280029'))
('^GSPC', datetime.date(2020, 1, 7), Decimal('3237.179932'))
('^GSPC', datetime.date(2020, 1, 8), Decimal('3253.050049'))
('^GSPC', datetime.date(2020, 1, 9), Decimal('3274.699951'))
('^GSPC', datetime.date(2020, 1, 10), Decimal('3265.350098'))
('^GSPC', datetime.date(2020, 1, 13), Decimal('3288.129883'))
('^GSPC', datetime.date(2020, 1, 14), Decimal('3283.149902'))
('^GSPC', datetime.date(2020, 1, 15), Decimal('3289.290039'))
('^GSPC', datetime.date(2020, 1, 16), Decimal('3316.810059'))
('^GSPC', datetime.date(2020, 1, 17), Decimal('3329.620117'))
('^GSPC', datetime.date(2020, 1, 21), Decimal('3320.790039'))
('^GSPC', datetime.date(2020, 1, 22), Decimal('3321.750000'))
('^GSPC', datetime.date(2020, 1, 23), Decimal('3325.540039'))
('^GSPC', datetime.date(2020, 1, 24), Decimal('3295.469971'))
('^GSPC', datetime.date(2020, 1, 27), Decimal('3243.629883'))
('^GSPC', datetime.date(2020, 1, 28), Decimal('3276.239990'))
('^GSPC', datetime.date(2020, 1, 29), Decimal('3273.399902'))
('^GSPC', datetime.date(2020, 1, 30), Decimal('3283.659912'))
('^GSPC', datetime.date(2020, 1, 31), Decimal('3225.520020'))
('^GSPC', datetime.date(2020, 2, 3), Decimal('3248.919922'))
('^GSPC', datetime.date(2020, 2, 4), Decimal('3297.590088'))
('^GSPC', datetime.date(2020, 2, 5), Decimal('3334.689941'))
('^GSPC', datetime.date(2020, 2, 6), Decimal('3345.780029'))
('^GSPC', datetime.date(2020, 2, 7), Decimal('3327.709961'))
('^GSPC', datetime.date(2020, 2, 10), Decimal('3352.090088'))
('^GSPC', datetime.date(2020, 2, 11), Decimal('3357.750000'))
('^GSPC', datetime.date(2020, 2, 12), Decimal('3379.449951'))
('^GSPC', datetime.date(2020, 2, 13), Decimal('3373.939941'))
('^GSPC', datetime.date(2020, 2, 14), Decimal('3380.159912'))
('^GSPC', datetime.date(2020, 2, 18), Decimal('3370.290039'))
('^GSPC', datetime.date(2020, 2, 19), Decimal('3386.149902'))
('^GSPC', datetime.date(2020, 2, 20), Decimal('3373.229980'))
('^GSPC', datetime.date(2020, 2, 21), Decimal('3337.750000'))
('^GSPC', datetime.date(2020, 2, 24), Decimal('3225.889893'))
('^GSPC', datetime.date(2020, 2, 25), Decimal('3128.209961'))
('^GSPC', datetime.date(2020, 2, 26), Decimal('3116.389893'))
('^GSPC', datetime.date(2020, 2, 27), Decimal('2978.760010'))
('^GSPC', datetime.date(2020, 2, 28), Decimal('2954.219971'))
('^GSPC', datetime.date(2020, 3, 2), Decimal('3090.229980'))
('^GSPC', datetime.date(2020, 3, 3), Decimal('3003.370117'))
('^GSPC', datetime.date(2020, 3, 4), Decimal('3130.120117'))
('^GSPC', datetime.date(2020, 3, 5), Decimal('3023.939941'))
('^GSPC', datetime.date(2020, 3, 6), Decimal('2972.370117'))
('^GSPC', datetime.date(2020, 3, 9), Decimal('2746.560059'))
('^GSPC', datetime.date(2020, 3, 10), Decimal('2882.229980'))
('^GSPC', datetime.date(2020, 3, 11), Decimal('2741.379883'))
('^GSPC', datetime.date(2020, 3, 12), Decimal('2480.639893'))
('^GSPC', datetime.date(2020, 3, 13), Decimal('2711.020020'))
('^GSPC', datetime.date(2020, 3, 16), Decimal('2386.129883'))
('^GSPC', datetime.date(2020, 3, 17), Decimal('2529.189941'))
('^GSPC', datetime.date(2020, 3, 18), Decimal('2398.100098'))
('^GSPC', datetime.date(2020, 3, 19), Decimal('2409.389893'))
('^GSPC', datetime.date(2020, 3, 20), Decimal('2304.919922'))
('^GSPC', datetime.date(2020, 3, 23), Decimal('2237.399902'))
('^GSPC', datetime.date(2020, 3, 24), Decimal('2447.330078'))
('^GSPC', datetime.date(2020, 3, 25), Decimal('2475.560059'))
('^GSPC', datetime.date(2020, 3, 26), Decimal('2630.070068'))
('^GSPC', datetime.date(2020, 3, 27), Decimal('2541.469971'))
('^GSPC', datetime.date(2020, 3, 30), Decimal('2626.649902'))
('^GSPC', datetime.date(2020, 3, 31), Decimal('2584.590088'))
('^GSPC', datetime.date(2020, 4, 1), Decimal('2470.500000'))
('^GSPC', datetime.date(2020, 4, 2), Decimal('2526.899902'))
('^GSPC', datetime.date(2020, 4, 3), Decimal('2488.649902'))
('^GSPC', datetime.date(2020, 4, 6), Decimal('2663.679932'))
('^GSPC', datetime.date(2020, 4, 7), Decimal('2659.409912'))
('^GSPC', datetime.date(2020, 4, 8), Decimal('2749.979980'))
('^GSPC', datetime.date(2020, 4, 9), Decimal('2789.820068'))
('^GSPC', datetime.date(2020, 4, 13), Decimal('2761.629883'))
('^GSPC', datetime.date(2020, 4, 14), Decimal('2846.060059'))
('^GSPC', datetime.date(2020, 4, 15), Decimal('2783.360107'))
('^GSPC', datetime.date(2020, 4, 16), Decimal('2799.550049'))
('^GSPC', datetime.date(2020, 4, 17), Decimal('2874.560059'))
('^GSPC', datetime.date(2020, 4, 20), Decimal('2823.159912'))
('^GSPC', datetime.date(2020, 4, 21), Decimal('2736.560059'))
('^GSPC', datetime.date(2020, 4, 22), Decimal('2799.310059'))
('^GSPC', datetime.date(2020, 4, 23), Decimal('2797.800049'))
('^GSPC', datetime.date(2020, 4, 24), Decimal('2836.739990'))
('^GSPC', datetime.date(2020, 4, 27), Decimal('2878.479980'))
('^GSPC', datetime.date(2020, 4, 28), Decimal('2863.389893'))
('^GSPC', datetime.date(2020, 4, 29), Decimal('2939.510010'))
('^GSPC', datetime.date(2020, 4, 30), Decimal('2912.429932'))
('^GSPC', datetime.date(2020, 5, 1), Decimal('2830.709961'))
('^GSPC', datetime.date(2020, 5, 4), Decimal('2842.739990'))
('^GSPC', datetime.date(2020, 5, 5), Decimal('2868.439941'))
('^GSPC', datetime.date(2020, 5, 6), Decimal('2848.419922'))
('^GSPC', datetime.date(2020, 5, 7), Decimal('2881.189941'))
('^GSPC', datetime.date(2020, 5, 8), Decimal('2929.800049'))
('^GSPC', datetime.date(2020, 5, 11), Decimal('2930.189941'))
('^GSPC', datetime.date(2020, 5, 12), Decimal('2870.120117'))
('^GSPC', datetime.date(2020, 5, 13), Decimal('2820.000000'))
('^GSPC', datetime.date(2020, 5, 14), Decimal('2852.500000'))
('^GSPC', datetime.date(2020, 5, 15), Decimal('2863.699951'))
('^GSPC', datetime.date(2020, 5, 18), Decimal('2953.909912'))
('^GSPC', datetime.date(2020, 5, 19), Decimal('2922.939941'))
('^GSPC', datetime.date(2020, 5, 20), Decimal('2971.610107'))
('^GSPC', datetime.date(2020, 5, 21), Decimal('2948.510010'))
('^GSPC', datetime.date(2020, 5, 22), Decimal('2955.449951'))
('^GSPC', datetime.date(2020, 5, 26), Decimal('2991.770020'))
('^GSPC', datetime.date(2020, 5, 27), Decimal('3036.129883'))
('^GSPC', datetime.date(2020, 5, 28), Decimal('3029.729980'))
('^GSPC', datetime.date(2020, 5, 29), Decimal('3044.310059'))
('^GSPC', datetime.date(2020, 6, 1), Decimal('3055.729980'))
('^GSPC', datetime.date(2020, 6, 2), Decimal('3080.820068'))
('^GSPC', datetime.date(2020, 6, 3), Decimal('3122.870117'))
('^GSPC', datetime.date(2020, 6, 4), Decimal('3112.350098'))
('^GSPC', datetime.date(2020, 6, 5), Decimal('3193.929932'))
('^GSPC', datetime.date(2020, 6, 8), Decimal('3232.389893'))
('^GSPC', datetime.date(2020, 6, 9), Decimal('3207.179932'))
('^GSPC', datetime.date(2020, 6, 10), Decimal('3190.139893'))
('^GSPC', datetime.date(2020, 6, 11), Decimal('3002.100098'))
('^GSPC', datetime.date(2020, 6, 12), Decimal('3041.310059'))
('^GSPC', datetime.date(2020, 6, 15), Decimal('3066.590088'))
('^GSPC', datetime.date(2020, 6, 16), Decimal('3124.739990'))
('^GSPC', datetime.date(2020, 6, 17), Decimal('3113.489990'))
('^GSPC', datetime.date(2020, 6, 18), Decimal('3115.340088'))
('^GSPC', datetime.date(2020, 6, 19), Decimal('3097.739990'))
('^GSPC', datetime.date(2020, 6, 22), Decimal('3117.860107'))
('^GSPC', datetime.date(2020, 6, 23), Decimal('3131.290039'))
('^GSPC', datetime.date(2020, 6, 24), Decimal('3050.330078'))
('^GSPC', datetime.date(2020, 6, 25), Decimal('3083.760010'))
('^GSPC', datetime.date(2020, 6, 26), Decimal('3009.050049'))
('^GSPC', datetime.date(2020, 6, 29), Decimal('3053.239990'))
('^GSPC', datetime.date(2020, 6, 30), Decimal('3100.290039'))
('^GSPC', datetime.date(2020, 7, 1), Decimal('3115.860107'))
('^GSPC', datetime.date(2020, 7, 2), Decimal('3130.010010'))
('^GSPC', datetime.date(2020, 7, 6), Decimal('3179.719971'))
('^GSPC', datetime.date(2020, 7, 7), Decimal('3145.320068'))
('^GSPC', datetime.date(2020, 7, 8), Decimal('3169.939941'))
('^GSPC', datetime.date(2020, 7, 9), Decimal('3152.050049'))
('^GSPC', datetime.date(2020, 7, 10), Decimal('3185.040039'))
('^GSPC', datetime.date(2020, 7, 13), Decimal('3155.219971'))
('^GSPC', datetime.date(2020, 7, 14), Decimal('3197.520020'))
('^GSPC', datetime.date(2020, 7, 15), Decimal('3226.560059'))
('^GSPC', datetime.date(2020, 7, 16), Decimal('3215.570068'))
('^GSPC', datetime.date(2020, 7, 17), Decimal('3224.729980'))
('^GSPC', datetime.date(2020, 7, 20), Decimal('3251.840088'))
('^GSPC', datetime.date(2020, 7, 21), Decimal('3257.300049'))
('^GSPC', datetime.date(2020, 7, 22), Decimal('3276.020020'))
('^GSPC', datetime.date(2020, 7, 23), Decimal('3235.659912'))
('^GSPC', datetime.date(2020, 7, 24), Decimal('3215.629883'))
('^GSPC', datetime.date(2020, 7, 27), Decimal('3239.409912'))
('^GSPC', datetime.date(2020, 7, 28), Decimal('3218.439941'))
('^GSPC', datetime.date(2020, 7, 29), Decimal('3258.439941'))
('^GSPC', datetime.date(2020, 7, 30), Decimal('3246.219971'))
('^GSPC', datetime.date(2020, 7, 31), Decimal('3271.120117'))
('^GSPC', datetime.date(2020, 8, 3), Decimal('3294.610107'))
('^GSPC', datetime.date(2020, 8, 4), Decimal('3306.510010'))
('^GSPC', datetime.date(2020, 8, 5), Decimal('3327.770020'))
('^GSPC', datetime.date(2020, 8, 6), Decimal('3349.159912'))
('^GSPC', datetime.date(2020, 8, 7), Decimal('3351.280029'))
('^GSPC', datetime.date(2020, 8, 10), Decimal('3360.469971'))
('^GSPC', datetime.date(2020, 8, 11), Decimal('3333.689941'))
('^GSPC', datetime.date(2020, 8, 12), Decimal('3380.350098'))
('^GSPC', datetime.date(2020, 8, 13), Decimal('3373.429932'))
('^GSPC', datetime.date(2020, 8, 14), Decimal('3372.850098'))
('^GSPC', datetime.date(2020, 8, 17), Decimal('3381.989990'))
('^GSPC', datetime.date(2020, 8, 18), Decimal('3389.780029'))
('^GSPC', datetime.date(2020, 8, 19), Decimal('3374.850098'))
('^GSPC', datetime.date(2020, 8, 20), Decimal('3385.510010'))
('^GSPC', datetime.date(2020, 8, 21), Decimal('3397.159912'))
('^GSPC', datetime.date(2020, 8, 24), Decimal('3431.280029'))
('^GSPC', datetime.date(2020, 8, 25), Decimal('3443.620117'))
('^GSPC', datetime.date(2020, 8, 26), Decimal('3478.729980'))
('^GSPC', datetime.date(2020, 8, 27), Decimal('3484.550049'))
('^GSPC', datetime.date(2020, 8, 28), Decimal('3508.010010'))
('^GSPC', datetime.date(2020, 8, 31), Decimal('3500.310059'))
('^GSPC', datetime.date(2020, 9, 1), Decimal('3526.649902'))
('^GSPC', datetime.date(2020, 9, 2), Decimal('3580.840088'))
('^GSPC', datetime.date(2020, 9, 3), Decimal('3455.060059'))
('^GSPC', datetime.date(2020, 9, 4), Decimal('3426.959961'))
('^GSPC', datetime.date(2020, 9, 8), Decimal('3331.840088'))
('^GSPC', datetime.date(2020, 9, 9), Decimal('3398.959961'))
('^GSPC', datetime.date(2020, 9, 10), Decimal('3339.189941'))
('^GSPC', datetime.date(2020, 9, 11), Decimal('3340.969971'))
('^GSPC', datetime.date(2020, 9, 14), Decimal('3383.540039'))
('^GSPC', datetime.date(2020, 9, 15), Decimal('3401.199951'))
('^GSPC', datetime.date(2020, 9, 16), Decimal('3385.489990'))
('^GSPC', datetime.date(2020, 9, 17), Decimal('3357.010010'))
('^GSPC', datetime.date(2020, 9, 18), Decimal('3319.469971'))
('^GSPC', datetime.date(2020, 9, 21), Decimal('3281.060059'))
('^GSPC', datetime.date(2020, 9, 22), Decimal('3315.570068'))
('^GSPC', datetime.date(2020, 9, 23), Decimal('3236.919922'))
('^GSPC', datetime.date(2020, 9, 24), Decimal('3246.590088'))
('^GSPC', datetime.date(2020, 9, 25), Decimal('3298.459961'))
('^GSPC', datetime.date(2020, 9, 28), Decimal('3351.600098'))
('^GSPC', datetime.date(2020, 9, 29), Decimal('3335.469971'))
('^GSPC', datetime.date(2020, 9, 30), Decimal('3363.000000'))
('^GSPC', datetime.date(2020, 10, 1), Decimal('3380.800049'))
('^GSPC', datetime.date(2020, 10, 2), Decimal('3348.419922'))
('^GSPC', datetime.date(2020, 10, 5), Decimal('3408.600098'))
('^GSPC', datetime.date(2020, 10, 6), Decimal('3360.969971'))
('^GSPC', datetime.date(2020, 10, 7), Decimal('3419.439941'))
('^GSPC', datetime.date(2020, 10, 8), Decimal('3446.830078'))
('^GSPC', datetime.date(2020, 10, 9), Decimal('3477.139893'))
('^GSPC', datetime.date(2020, 10, 12), Decimal('3534.219971'))
('^GSPC', datetime.date(2020, 10, 13), Decimal('3511.929932'))
('^GSPC', datetime.date(2020, 10, 14), Decimal('3488.669922'))
('^GSPC', datetime.date(2020, 10, 15), Decimal('3483.340088'))
('^GSPC', datetime.date(2020, 10, 16), Decimal('3483.810059'))
('^GSPC', datetime.date(2020, 10, 19), Decimal('3426.919922'))
('^GSPC', datetime.date(2020, 10, 20), Decimal('3443.120117'))
('^GSPC', datetime.date(2020, 10, 21), Decimal('3435.560059'))
('^GSPC', datetime.date(2020, 10, 22), Decimal('3453.489990'))
('^GSPC', datetime.date(2020, 10, 23), Decimal('3465.389893'))
('^GSPC', datetime.date(2020, 10, 26), Decimal('3400.969971'))
('^GSPC', datetime.date(2020, 10, 27), Decimal('3390.679932'))
('^GSPC', datetime.date(2020, 10, 28), Decimal('3271.030029'))
('^GSPC', datetime.date(2020, 10, 29), Decimal('3310.110107'))
('^GSPC', datetime.date(2020, 10, 30), Decimal('3269.959961'))
('^GSPC', datetime.date(2020, 11, 2), Decimal('3310.239990'))
('^GSPC', datetime.date(2020, 11, 3), Decimal('3369.159912'))
('^GSPC', datetime.date(2020, 11, 4), Decimal('3443.439941'))
('^GSPC', datetime.date(2020, 11, 5), Decimal('3510.449951'))
('^GSPC', datetime.date(2020, 11, 6), Decimal('3509.439941'))
('^GSPC', datetime.date(2020, 11, 9), Decimal('3550.500000'))
('^GSPC', datetime.date(2020, 11, 10), Decimal('3545.530029'))
('^GSPC', datetime.date(2020, 11, 11), Decimal('3572.659912'))
('^GSPC', datetime.date(2020, 11, 12), Decimal('3537.010010'))
('^GSPC', datetime.date(2020, 11, 13), Decimal('3585.149902'))
('^GSPC', datetime.date(2020, 11, 16), Decimal('3626.909912'))
('^GSPC', datetime.date(2020, 11, 17), Decimal('3609.530029'))
('^GSPC', datetime.date(2020, 11, 18), Decimal('3567.790039'))
('^GSPC', datetime.date(2020, 11, 19), Decimal('3581.870117'))
('^GSPC', datetime.date(2020, 11, 20), Decimal('3557.540039'))
('^GSPC', datetime.date(2020, 11, 23), Decimal('3577.590088'))
('^GSPC', datetime.date(2020, 11, 24), Decimal('3635.409912'))
('^GSPC', datetime.date(2020, 11, 25), Decimal('3629.649902'))
('^GSPC', datetime.date(2020, 11, 27), Decimal('3638.350098'))
('^GSPC', datetime.date(2020, 11, 30), Decimal('3621.629883'))
('^GSPC', datetime.date(2020, 12, 1), Decimal('3662.449951'))
('^GSPC', datetime.date(2020, 12, 2), Decimal('3669.010010'))
('^GSPC', datetime.date(2020, 12, 3), Decimal('3666.719971'))
('^GSPC', datetime.date(2020, 12, 4), Decimal('3699.120117'))
('^GSPC', datetime.date(2020, 12, 7), Decimal('3691.959961'))
('^GSPC', datetime.date(2020, 12, 8), Decimal('3702.250000'))
('^GSPC', datetime.date(2020, 12, 9), Decimal('3672.820068'))
('^GSPC', datetime.date(2020, 12, 10), Decimal('3668.100098'))
('^GSPC', datetime.date(2020, 12, 11), Decimal('3663.459961'))
('^GSPC', datetime.date(2020, 12, 14), Decimal('3647.489990'))
('^GSPC', datetime.date(2020, 12, 15), Decimal('3694.620117'))
('^GSPC', datetime.date(2020, 12, 16), Decimal('3701.169922'))
('^GSPC', datetime.date(2020, 12, 17), Decimal('3722.479980'))
('^GSPC', datetime.date(2020, 12, 18), Decimal('3709.409912'))
('^GSPC', datetime.date(2020, 12, 21), Decimal('3694.919922'))
('^GSPC', datetime.date(2020, 12, 22), Decimal('3687.260010'))
('^GSPC', datetime.date(2020, 12, 23), Decimal('3690.010010'))
('^GSPC', datetime.date(2020, 12, 24), Decimal('3703.060059'))
('^GSPC', datetime.date(2020, 12, 28), Decimal('3735.360107'))
('^GSPC', datetime.date(2020, 12, 29), Decimal('3727.040039'))
('^GSPC', datetime.date(2020, 12, 30), Decimal('3732.040039'))
('^GSPC', datetime.date(2020, 12, 31), Decimal('3756.070068'))
('^GSPC', datetime.date(2021, 1, 4), Decimal('3700.649902'))
('^GSPC', datetime.date(2021, 1, 5), Decimal('3726.860107'))
('^GSPC', datetime.date(2021, 1, 6), Decimal('3748.139893'))
('^GSPC', datetime.date(2021, 1, 7), Decimal('3803.790039'))
('^GSPC', datetime.date(2021, 1, 8), Decimal('3824.679932'))
('^GSPC', datetime.date(2021, 1, 11), Decimal('3799.610107'))
('^GSPC', datetime.date(2021, 1, 12), Decimal('3801.189941'))
('^GSPC', datetime.date(2021, 1, 13), Decimal('3809.840088'))
('^GSPC', datetime.date(2021, 1, 14), Decimal('3795.540039'))
('^GSPC', datetime.date(2021, 1, 15), Decimal('3768.250000'))
('^GSPC', datetime.date(2021, 1, 19), Decimal('3798.909912'))
('^GSPC', datetime.date(2021, 1, 20), Decimal('3851.850098'))
('^GSPC', datetime.date(2021, 1, 21), Decimal('3853.070068'))
('^GSPC', datetime.date(2021, 1, 22), Decimal('3841.469971'))
('^GSPC', datetime.date(2021, 1, 25), Decimal('3855.360107'))
('^GSPC', datetime.date(2021, 1, 26), Decimal('3849.620117'))
('^GSPC', datetime.date(2021, 1, 27), Decimal('3750.770020'))
('^GSPC', datetime.date(2021, 1, 28), Decimal('3787.379883'))
('^GSPC', datetime.date(2021, 1, 29), Decimal('3714.239990'))
('^GSPC', datetime.date(2021, 2, 1), Decimal('3773.860107'))
('^GSPC', datetime.date(2021, 2, 2), Decimal('3826.310059'))
('^GSPC', datetime.date(2021, 2, 3), Decimal('3830.169922'))
('^GSPC', datetime.date(2021, 2, 4), Decimal('3871.739990'))
('^GSPC', datetime.date(2021, 2, 5), Decimal('3886.830078'))
('^GSPC', datetime.date(2021, 2, 8), Decimal('3915.590088'))
('^GSPC', datetime.date(2021, 2, 9), Decimal('3911.229980'))
('^GSPC', datetime.date(2021, 2, 10), Decimal('3909.879883'))
('^GSPC', datetime.date(2021, 2, 11), Decimal('3916.379883'))
('^GSPC', datetime.date(2021, 2, 12), Decimal('3934.830078'))
('^GSPC', datetime.date(2021, 2, 16), Decimal('3932.590088'))
('^GSPC', datetime.date(2021, 2, 17), Decimal('3931.330078'))
('^GSPC', datetime.date(2021, 2, 18), Decimal('3913.969971'))
('^GSPC', datetime.date(2021, 2, 19), Decimal('3906.709961'))
('^GSPC', datetime.date(2021, 2, 22), Decimal('3876.500000'))
('^GSPC', datetime.date(2021, 2, 23), Decimal('3881.370117'))
('^GSPC', datetime.date(2021, 2, 24), Decimal('3925.429932'))
('^GSPC', datetime.date(2021, 2, 25), Decimal('3829.340088'))
('^GSPC', datetime.date(2021, 2, 26), Decimal('3811.149902'))
('^GSPC', datetime.date(2021, 3, 1), Decimal('3901.820068'))
('^GSPC', datetime.date(2021, 3, 2), Decimal('3870.290039'))
('^GSPC', datetime.date(2021, 3, 3), Decimal('3819.719971'))
('^GSPC', datetime.date(2021, 3, 4), Decimal('3768.469971'))
('^GSPC', datetime.date(2021, 3, 5), Decimal('3841.939941'))
('^GSPC', datetime.date(2021, 3, 8), Decimal('3821.350098'))
('^GSPC', datetime.date(2021, 3, 9), Decimal('3875.439941'))
('^GSPC', datetime.date(2021, 3, 10), Decimal('3898.810059'))
('^GSPC', datetime.date(2021, 3, 11), Decimal('3939.340088'))
('^GSPC', datetime.date(2021, 3, 12), Decimal('3943.340088'))
('^GSPC', datetime.date(2021, 3, 15), Decimal('3968.939941'))
('^GSPC', datetime.date(2021, 3, 16), Decimal('3962.709961'))
('^GSPC', datetime.date(2021, 3, 17), Decimal('3974.120117'))
('^GSPC', datetime.date(2021, 3, 18), Decimal('3915.459961'))
('^GSPC', datetime.date(2021, 3, 19), Decimal('3913.100098'))
('^GSPC', datetime.date(2021, 3, 22), Decimal('3940.590088'))
('^GSPC', datetime.date(2021, 3, 23), Decimal('3910.520020'))
('^GSPC', datetime.date(2021, 3, 24), Decimal('3889.139893'))
('^GSPC', datetime.date(2021, 3, 25), Decimal('3909.520020'))
('^GSPC', datetime.date(2021, 3, 26), Decimal('3974.540039'))
('^GSPC', datetime.date(2021, 3, 29), Decimal('3971.090088'))
('^GSPC', datetime.date(2021, 3, 30), Decimal('3958.550049'))
('^GSPC', datetime.date(2021, 3, 31), Decimal('3972.889893'))
('^GSPC', datetime.date(2021, 4, 1), Decimal('4019.870117'))
('^GSPC', datetime.date(2021, 4, 5), Decimal('4077.909912'))
('^GSPC', datetime.date(2021, 4, 6), Decimal('4073.939941'))
('^GSPC', datetime.date(2021, 4, 7), Decimal('4079.949951'))
('^GSPC', datetime.date(2021, 4, 8), Decimal('4097.169922'))
('^GSPC', datetime.date(2021, 4, 9), Decimal('4128.799805'))
('^GSPC', datetime.date(2021, 4, 12), Decimal('4127.990234'))
('^GSPC', datetime.date(2021, 4, 13), Decimal('4141.589844'))
('^GSPC', datetime.date(2021, 4, 14), Decimal('4124.660156'))

In [75]:
#Find the highest closing price for NASDAQ (^IXIC)
cursor.execute("""
SELECT Date, Close
FROM stock_prices
WHERE ticker = '^IXIC'
AND Close IS NOT NULL
ORDER BY Close DESC
LIMIT 1
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2025, 10, 29), Decimal('23958.470703'))

In [76]:
#List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)
cursor.execute("""
SELECT 
    Date,

    -- Daily highest price
    High,

    -- Daily lowest price
    Low,

    -- Difference (volatility of that day)
    (High - Low) AS price_difference

FROM stock_prices

-- Filter S&P 500
WHERE ticker = '^GSPC'

-- Remove missing values
AND High IS NOT NULL
AND Low IS NOT NULL

-- Sort by highest difference
ORDER BY price_difference DESC

-- Take top 5 days
LIMIT 5
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2025, 4, 9), Decimal('5481.339844'), Decimal('4948.430176'), Decimal('532.909668'))
(datetime.date(2025, 4, 7), Decimal('5246.569824'), Decimal('4835.040039'), Decimal('411.529785'))
(datetime.date(2025, 4, 8), Decimal('5267.470215'), Decimal('4910.419922'), Decimal('357.050293'))
(datetime.date(2025, 4, 10), Decimal('5353.149902'), Decimal('5115.270020'), Decimal('237.879882'))
(datetime.date(2025, 11, 20), Decimal('6770.350098'), Decimal('6534.049805'), Decimal('236.300293'))

In [77]:
#Get monthly average closing price for each ticker
cursor.execute("""
SELECT 
    ticker,

    -- Extract year
    YEAR(Date) AS year,

    -- Extract month
    MONTH(Date) AS month,

    -- Average closing price
    AVG(Close) AS avg_close

FROM stock_prices

-- Remove missing values
WHERE Close IS NOT NULL

-- Group by ticker + year + month
GROUP BY ticker, YEAR(Date), MONTH(Date)

-- Sort properly
ORDER BY ticker, year, month
""")

for row in cursor.fetchall():
    print(row)

('^GSPC', 2020, 1, Decimal('3278.2028576667'))
('^GSPC', 2020, 2, Decimal('3277.3141832632'))
('^GSPC', 2020, 3, Decimal('2652.3936323636'))
('^GSPC', 2020, 4, Decimal('2761.9752255714'))
('^GSPC', 2020, 5, Decimal('2919.6084838000'))
('^GSPC', 2020, 6, Decimal('3104.6609330909'))
('^GSPC', 2020, 7, Decimal('3207.6190962273'))
('^GSPC', 2020, 8, Decimal('3391.7100190952'))
('^GSPC', 2020, 9, Decimal('3365.5166713810'))
('^GSPC', 2020, 10, Decimal('3418.6999956818'))
('^GSPC', 2020, 11, Decimal('3548.9924803500'))
('^GSPC', 2020, 12, Decimal('3695.3100141818'))
('^GSPC', 2021, 1, Decimal('3793.7484323158'))
('^GSPC', 2021, 2, Decimal('3883.4321160526'))
('^GSPC', 2021, 3, Decimal('3910.5082796522'))
('^GSPC', 2021, 4, Decimal('4141.1761997619'))
('^GSPC', 2021, 5, Decimal('4167.8495361500'))
('^GSPC', 2021, 6, Decimal('4238.4895463182'))
('^GSPC', 2021, 7, Decimal('4363.7127976190'))
('^GSPC', 2021, 8, Decimal('4453.9659312727'))
('^GSPC', 2021, 9, Decimal('4445.5433173810'))
('^GSPC', 2021, 10, Decimal('4460.7070777619'))
('^GSPC', 2021, 11, Decimal('4667.3866490000'))
('^GSPC', 2021, 12, Decimal('4674.7727717727'))
('^GSPC', 2022, 1, Decimal('4573.8154541500'))
('^GSPC', 2022, 2, Decimal('4435.9804944211'))
('^GSPC', 2022, 3, Decimal('4391.2652640870'))
('^GSPC', 2022, 4, Decimal('4391.2959960000'))
('^GSPC', 2022, 5, Decimal('4040.3600027619'))
('^GSPC', 2022, 6, Decimal('3898.9466842857'))
('^GSPC', 2022, 7, Decimal('3911.7294922000'))
('^GSPC', 2022, 8, Decimal('4158.5630836957'))
('^GSPC', 2022, 9, Decimal('3850.5204961905'))
('^GSPC', 2022, 10, Decimal('3726.0509556190'))
('^GSPC', 2022, 11, Decimal('3917.4885950952'))
('^GSPC', 2022, 12, Decimal('3912.3809523333'))
('^GSPC', 2023, 1, Decimal('3960.6565309000'))
('^GSPC', 2023, 2, Decimal('4079.6847244737'))
('^GSPC', 2023, 3, Decimal('3968.5591458261'))
('^GSPC', 2023, 4, Decimal('4121.4673623158'))
('^GSPC', 2023, 5, Decimal('4146.1731955455'))
('^GSPC', 2023, 6, Decimal('4345.3728376667'))
('^GSPC', 2023, 7, Decimal('4508.0754882500'))
('^GSPC', 2023, 8, Decimal('4457.3586744783'))
('^GSPC', 2023, 9, Decimal('4409.0949950500'))
('^GSPC', 2023, 10, Decimal('4269.4009454091'))
('^GSPC', 2023, 11, Decimal('4460.0633138095'))
('^GSPC', 2023, 12, Decimal('4685.0514893000'))
('^GSPC', 2024, 1, Decimal('4804.4915131905'))
('^GSPC', 2024, 2, Decimal('5011.9614258000'))
('^GSPC', 2024, 3, Decimal('5170.5724853000'))
('^GSPC', 2024, 4, Decimal('5112.4927424091'))
('^GSPC', 2024, 5, Decimal('5235.2254971818'))
('^GSPC', 2024, 6, Decimal('5415.1404963684'))
('^GSPC', 2024, 7, Decimal('5538.0045721364'))
('^GSPC', 2024, 8, Decimal('5478.2145775000'))
('^GSPC', 2024, 9, Decimal('5621.2604493500'))
('^GSPC', 2024, 10, Decimal('5792.3195482174'))
('^GSPC', 2024, 11, Decimal('5929.9159912000'))
('^GSPC', 2024, 12, Decimal('6010.9085518571'))
('^GSPC', 2025, 1, Decimal('5979.5155273000'))
('^GSPC', 2025, 2, Decimal('6038.6899670526'))
('^GSPC', 2025, 3, Decimal('5683.9833519524'))
('^GSPC', 2025, 4, Decimal('5369.4957217619'))
('^GSPC', 2025, 5, Decimal('5810.9194800952'))
('^GSPC', 2025, 6, Decimal('6029.9515137000'))
('^GSPC', 2025, 7, Decimal('6296.4981801364'))
('^GSPC', 2025, 8, Decimal('6408.9494744286'))
('^GSPC', 2025, 9, Decimal('6584.0180896667'))
('^GSPC', 2025, 10, Decimal('6735.6917247391'))
('^GSPC', 2025, 11, Decimal('6740.8857678421'))
('^GSPC', 2025, 12, Decimal('6853.0254572273'))
('^GSPC', 2026, 1, Decimal('6929.1219727000'))
('^GSPC', 2026, 2, Decimal('6893.8062809474'))
('^GSPC', 2026, 3, Decimal('6654.4191228182'))
('^GSPC', 2026, 4, Decimal('6579.0048825000'))
('^IXIC', 2020, 1, Decimal('9233.3599796190'))
('^IXIC', 2020, 2, Decimal('9418.8500207368'))
('^IXIC', 2020, 3, Decimal('7772.2058328636'))
('^IXIC', 2020, 4, Decimal('8292.4071800952'))
('^IXIC', 2020, 5, Decimal('9105.6554687500'))
('^IXIC', 2020, 6, Decimal('9839.9713245455'))
('^IXIC', 2020, 7, Decimal('10499.8627042727'))
('^IXIC', 2020, 8, Decimal('11212.2905042857'))
('^IXIC', 2020, 9, Decimal('11088.6799665238'))
('^IXIC', 2020, 10, Decimal('11435.2341086818'))
('^IXIC', 2020, 11, Decimal('11794.4615235500'))
('^IXIC', 2020, 12, Decimal('12619.0509144091'))
('^IXIC', 2021, 1, Decimal('13186.6057771053'))
('^IXIC', 2021, 2, Decimal('13737.4036286316'))
('^IXIC', 2021, 3, Decimal('13168.8118206957'))
('^IXIC', 2021, 4, Decimal('13900.4379650952'))
('^IXIC', 2021, 5, Decimal('13520.2290527000'))
('^IXIC', 2021, 6, Decimal('14097.1690785000'))
('^IXIC', 2021, 7, Decimal('14639.0728700952'))
('^IXIC', 2021, 8, Decimal('14856.5177113636'))
('^IXIC', 2021, 9, Decimal('15023.5385510000'))
('^IXIC', 2021, 10, Decimal('14879.0123232381'))
('^IXIC', 2021, 11, Decimal('15814.9328962381'))
('^IXIC', 2021, 12, Decimal('15474.4317295000'))
('^IXIC', 2022, 1, Decimal('14531.3774903000'))
('^IXIC', 2022, 2, Decimal('13898.7284129474'))
('^IXIC', 2022, 3, Decimal('13623.2629501304'))
('^IXIC', 2022, 4, Decimal('13394.1630372000'))
('^IXIC', 2022, 5, Decimal('11829.7295386667'))
('^IXIC', 2022, 6, Decimal('11418.9190848095'))
('^IXIC', 2022, 7, Decimal('11622.6315430500'))
('^IXIC', 2022, 8, Decimal('12570.2604026087'))
('^IXIC', 2022, 9, Decimal('11402.8499815238'))
('^IXIC', 2022, 10, Decimal('10801.4942801905'))
('^IXIC', 2022, 11, Decimal('10973.6381138571'))
('^IXIC', 2022, 12, Decimal('10838.9958146667'))
('^IXIC', 2023, 1, Decimal('11013.9909668500'))
('^IXIC', 2023, 2, Decimal('11785.0743216316'))
('^IXIC', 2023, 3, Decimal('11637.0922215217'))
('^IXIC', 2023, 4, Decimal('12073.4647409474'))
('^IXIC', 2023, 5, Decimal('12446.5304955000'))
('^IXIC', 2023, 6, Decimal('13463.7781343810'))
('^IXIC', 2023, 7, Decimal('14033.0909667000'))
('^IXIC', 2023, 8, Decimal('13743.2130180435'))
('^IXIC', 2023, 9, Decimal('13585.8395508000'))
('^IXIC', 2023, 10, Decimal('13199.4276901364'))
('^IXIC', 2023, 11, Decimal('13913.1605748095'))
('^IXIC', 2023, 12, Decimal('14690.4739746000'))
('^IXIC', 2024, 1, Decimal('15081.3881605238'))
('^IXIC', 2024, 2, Decimal('15808.9350097500'))
('^IXIC', 2024, 3, Decimal('16216.2955078000'))
('^IXIC', 2024, 4, Decimal('15950.8635475909'))
('^IXIC', 2024, 5, Decimal('16536.3171609545'))
('^IXIC', 2024, 6, Decimal('17495.8916530000'))
('^IXIC', 2024, 7, Decimal('17963.2909269091'))
('^IXIC', 2024, 8, Decimal('17268.2688653636'))
('^IXIC', 2024, 9, Decimal('17599.2301758000'))
('^IXIC', 2024, 10, Decimal('18316.4046366087'))
('^IXIC', 2024, 11, Decimal('18961.3357423500'))
('^IXIC', 2024, 12, Decimal('19734.5417596667'))
('^IXIC', 2025, 1, Decimal('19565.0439454500'))
('^IXIC', 2025, 2, Decimal('19547.2814556842'))
('^IXIC', 2025, 3, Decimal('17828.0265067619'))
('^IXIC', 2025, 4, Decimal('16678.4597284762'))
('^IXIC', 2025, 5, Decimal('18642.3692336667'))
('^IXIC', 2025, 6, Decimal('19673.3011718500'))
('^IXIC', 2025, 7, Decimal('20784.8959517727'))
('^IXIC', 2025, 8, Decimal('21383.5871466190'))
('^IXIC', 2025, 9, Decimal('22188.5877977143'))
('^IXIC', 2025, 10, Decimal('23003.1257643478'))
('^IXIC', 2025, 11, Decimal('23023.6227385263'))
('^IXIC', 2025, 12, Decimal('23377.3268821364'))
('^IXIC', 2026, 1, Decimal('23520.7223633500'))
('^IXIC', 2026, 2, Decimal('22892.9234170000'))
('^IXIC', 2026, 3, Decimal('22130.0376420909'))
('^IXIC', 2026, 4, Decimal('21860.0644535000'))
('^NSEI', 2020, 1, Decimal('12183.0651325217'))
('^NSEI', 2020, 2, Decimal('11948.8211863684'))
('^NSEI', 2020, 3, Decimal('9426.3119419524'))
('^NSEI', 2020, 4, Decimal('9063.5833334444'))
('^NSEI', 2020, 5, Decimal('9192.0130551053'))
('^NSEI', 2020, 6, Decimal('10116.4546787273'))
('^NSEI', 2020, 7, Decimal('10897.6956945652'))
('^NSEI', 2020, 8, Decimal('11318.5666852381'))
('^NSEI', 2020, 9, Decimal('11336.7021928636'))
('^NSEI', 2020, 10, Decimal('11789.7094958571'))
('^NSEI', 2020, 11, Decimal('12592.9579564737'))
('^NSEI', 2020, 12, Decimal('13550.4408735455'))
('^NSEI', 2021, 1, Decimal('14284.6024902000'))
('^NSEI', 2021, 2, Decimal('14956.8425293000'))
('^NSEI', 2021, 3, Decimal('14835.0999813810'))
('^NSEI', 2021, 4, Decimal('14613.8525391053'))
('^NSEI', 2021, 5, Decimal('14983.5250000500'))
('^NSEI', 2021, 6, Decimal('15733.6772015455'))
('^NSEI', 2021, 7, Decimal('15783.0976562381'))
('^NSEI', 2021, 8, Decimal('16470.4594493810'))
('^NSEI', 2021, 9, Decimal('17508.6143043333'))
('^NSEI', 2021, 10, Decimal('18020.2200195500'))
('^NSEI', 2021, 11, Decimal('17718.8923828500'))
('^NSEI', 2021, 12, Decimal('17174.2694463913'))
('^NSEI', 2022, 1, Decimal('17770.6224609500'))
('^NSEI', 2022, 2, Decimal('17225.9399902000'))
('^NSEI', 2022, 3, Decimal('16864.6738745714'))
('^NSEI', 2022, 4, Decimal('17419.3607114211'))
('^NSEI', 2022, 5, Decimal('16271.0191128095'))
('^NSEI', 2022, 6, Decimal('15933.1636630000'))
('^NSEI', 2022, 7, Decimal('16299.0213448571'))
('^NSEI', 2022, 8, Decimal('17579.0649415000'))
('^NSEI', 2022, 9, Decimal('17544.8773080909'))
('^NSEI', 2022, 10, Decimal('17406.8736635789'))
('^NSEI', 2022, 11, Decimal('18311.2832962381'))
('^NSEI', 2022, 12, Decimal('18385.1319245909'))
('^NSEI', 2023, 1, Decimal('17968.7450707143'))
('^NSEI', 2023, 2, Decimal('17739.2223632500'))
('^NSEI', 2023, 3, Decimal('17225.6429502381'))
('^NSEI', 2023, 4, Decimal('17710.6796874706'))
('^NSEI', 2023, 5, Decimal('18307.0545987727'))
('^NSEI', 2023, 6, Decimal('18726.7713913810'))
('^NSEI', 2023, 7, Decimal('19586.0002790000'))
('^NSEI', 2023, 8, Decimal('19438.2865766364'))
('^NSEI', 2023, 9, Decimal('19786.0451171000'))
('^NSEI', 2023, 10, Decimal('19481.6649413500'))
('^NSEI', 2023, 11, Decimal('19602.8499023500'))
('^NSEI', 2023, 12, Decimal('21165.9900391500'))
('^NSEI', 2024, 1, Decimal('21634.7546502381'))
('^NSEI', 2024, 2, Decimal('21947.2785528571'))
('^NSEI', 2024, 3, Decimal('22176.6943360000'))
('^NSEI', 2024, 4, Decimal('22443.4576172500'))
('^NSEI', 2024, 5, Decimal('22484.4332217143'))
('^NSEI', 2024, 6, Decimal('23364.0447162632'))
('^NSEI', 2024, 7, Decimal('24495.1521661818'))
('^NSEI', 2024, 8, Decimal('24613.0737537619'))
('^NSEI', 2024, 9, Decimal('25470.0904948095'))
('^NSEI', 2024, 10, Decimal('24781.6703656818'))
('^NSEI', 2024, 11, Decimal('23969.8474506316'))
('^NSEI', 2024, 12, Decimal('24231.0191592857'))
('^NSEI', 2025, 1, Decimal('23366.3956352609'))
('^NSEI', 2025, 2, Decimal('23060.9376953000'))
('^NSEI', 2025, 3, Decimal('22851.5369037895'))
('^NSEI', 2025, 4, Decimal('23531.6629317368'))
('^NSEI', 2025, 5, Decimal('24676.4402902857'))
('^NSEI', 2025, 6, Decimal('25003.3976934762'))
('^NSEI', 2025, 7, Decimal('25164.8914741304'))
('^NSEI', 2025, 8, Decimal('24698.1027960000'))
('^NSEI', 2025, 9, Decimal('24942.6749821364'))
('^NSEI', 2025, 10, Decimal('25494.0835192857'))
('^NSEI', 2025, 11, Decimal('25894.8343955789'))
('^NSEI', 2025, 12, Decimal('25997.7387250909'))
('^NSEI', 2026, 1, Decimal('25652.9626953000'))
('^NSEI', 2026, 2, Decimal('25625.5750976500'))
('^NSEI', 2026, 3, Decimal('23593.4842722632'))
('^NSEI', 2026, 4, Decimal('22696.2500000000'))

In [6]:
#Get average trading volume of NSEI in 2024
cursor.execute("""
SELECT AVG(volume) AS avg_volume
FROM stock_prices

-- Filter only NSEI index
WHERE ticker = '^NSEI'

-- Filter year 2024 data
AND YEAR(date) = 2024
""")

for row in cursor.fetchall():
    print(row)

(Decimal('313560.1626'),)

In [ ]:
#🔗 Join Queries (Cross-Market Analysis)

In [9]:
#Compare Bitcoin vs Oil average price in 2025.
cursor.execute("""
SELECT 
    ROUND(AVG(cp.price_inr),2) AS bitcoin_avg,
    ROUND(AVG(op.price_inr),2) AS oil_avg
FROM crypto_prices cp
JOIN oil_prices op 
ON cp.date = op.date
WHERE cp.coin_id = 'bitcoin'
AND YEAR(cp.date) = 2025
""")

print(cursor.fetchall())

[(Decimal('9245356.33'), Decimal('5253.94'))]

In [10]:
#Check if Bitcoin moves with S&P 500 (correlation idea).
cursor.execute("""
SELECT 
    cp.date,
    cp.price_inr AS bitcoin_price,
    sp.close AS sp500_price

FROM crypto_prices cp

-- Join with stock data using date
JOIN stock_prices sp 
ON cp.date = sp.date

-- Filter Bitcoin
WHERE cp.coin_id = 'bitcoin'

-- Filter S&P 500
AND sp.ticker = '^GSPC'

-- Sort for trend
ORDER BY cp.date
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2025, 4, 15), Decimal('7271599.950977'), Decimal('5396.629883'))
(datetime.date(2025, 4, 16), Decimal('7171572.949307'), Decimal('5275.700195'))
(datetime.date(2025, 4, 17), Decimal('7201187.297551'), Decimal('5282.700195'))
(datetime.date(2025, 4, 21), Decimal('7263849.726469'), Decimal('5158.200195'))
(datetime.date(2025, 4, 22), Decimal('7447341.987487'), Decimal('5287.759766'))
(datetime.date(2025, 4, 23), Decimal('7975735.892698'), Decimal('5375.859863'))
(datetime.date(2025, 4, 24), Decimal('8003280.213214'), Decimal('5484.770020'))
(datetime.date(2025, 4, 25), Decimal('8000169.783417'), Decimal('5525.209961'))
(datetime.date(2025, 4, 28), Decimal('8009924.381134'), Decimal('5528.750000'))
(datetime.date(2025, 4, 29), Decimal('8092853.390806'), Decimal('5560.830078'))
(datetime.date(2025, 4, 30), Decimal('8027696.597799'), Decimal('5569.060059'))
(datetime.date(2025, 5, 1), Decimal('7968688.759781'), Decimal('5604.140137'))
(datetime.date(2025, 5, 2), Decimal('8167058.515488'), Decimal('5686.669922'))
(datetime.date(2025, 5, 5), Decimal('7973099.086450'), Decimal('5650.379883'))
(datetime.date(2025, 5, 6), Decimal('7980688.008703'), Decimal('5606.910156'))
(datetime.date(2025, 5, 7), Decimal('8207545.052482'), Decimal('5631.279785'))
(datetime.date(2025, 5, 8), Decimal('8229539.783984'), Decimal('5663.939941'))
(datetime.date(2025, 5, 9), Decimal('8868161.595114'), Decimal('5659.910156'))
(datetime.date(2025, 5, 12), Decimal('8882429.185762'), Decimal('5844.189941'))
(datetime.date(2025, 5, 13), Decimal('8739740.641206'), Decimal('5886.549805'))
(datetime.date(2025, 5, 14), Decimal('8860925.913889'), Decimal('5892.580078'))
(datetime.date(2025, 5, 15), Decimal('8854656.259617'), Decimal('5916.930176'))
(datetime.date(2025, 5, 16), Decimal('8861418.050018'), Decimal('5958.379883'))
(datetime.date(2025, 5, 19), Decimal('9065676.354330'), Decimal('5963.600098'))
(datetime.date(2025, 5, 20), Decimal('9017978.281234'), Decimal('5940.459961'))
(datetime.date(2025, 5, 21), Decimal('9134061.037906'), Decimal('5844.609863'))
(datetime.date(2025, 5, 22), Decimal('9387459.456661'), Decimal('5842.009766'))
(datetime.date(2025, 5, 23), Decimal('9591418.421810'), Decimal('5802.819824'))
(datetime.date(2025, 5, 26), Decimal('9274975.732278'), None)
(datetime.date(2025, 5, 27), Decimal('9314436.685236'), Decimal('5921.540039'))
(datetime.date(2025, 5, 28), Decimal('9310175.102672'), Decimal('5888.549805'))
(datetime.date(2025, 5, 29), Decimal('9208280.990680'), Decimal('5912.169922'))
(datetime.date(2025, 5, 30), Decimal('9026592.666677'), Decimal('5911.689941'))
(datetime.date(2025, 6, 2), Decimal('9040802.274014'), Decimal('5935.939941'))
(datetime.date(2025, 6, 3), Decimal('9038740.617012'), Decimal('5970.370117'))
(datetime.date(2025, 6, 4), Decimal('9036688.899610'), Decimal('5970.810059'))
(datetime.date(2025, 6, 5), Decimal('9003749.459209'), Decimal('5939.299805'))
(datetime.date(2025, 6, 6), Decimal('8729536.730078'), Decimal('6000.359863'))
(datetime.date(2025, 6, 9), Decimal('9066867.468852'), Decimal('6005.879883'))
(datetime.date(2025, 6, 10), Decimal('9455619.179044'), Decimal('6038.810059'))
(datetime.date(2025, 6, 11), Decimal('9440056.689266'), Decimal('6022.240234'))
(datetime.date(2025, 6, 12), Decimal('9288882.881869'), Decimal('6045.259766'))
(datetime.date(2025, 6, 13), Decimal('9081227.025134'), Decimal('5976.970215'))
(datetime.date(2025, 6, 16), Decimal('9090411.274773'), Decimal('6033.109863'))
(datetime.date(2025, 6, 17), Decimal('9208980.453923'), Decimal('5982.720215'))
(datetime.date(2025, 6, 18), Decimal('9039952.955659'), Decimal('5980.870117'))
(datetime.date(2025, 6, 19), Decimal('9070436.848135'), None)
(datetime.date(2025, 6, 20), Decimal('9080584.318377'), Decimal('5967.839844'))
(datetime.date(2025, 6, 23), Decimal('8731873.284684'), Decimal('6025.169922'))
(datetime.date(2025, 6, 24), Decimal('9111429.945371'), Decimal('6092.180176'))
(datetime.date(2025, 6, 25), Decimal('9111165.386620'), Decimal('6092.160156'))
(datetime.date(2025, 6, 26), Decimal('9223086.808659'), Decimal('6141.020020'))
(datetime.date(2025, 6, 27), Decimal('9165684.099752'), Decimal('6173.069824'))
(datetime.date(2025, 6, 30), Decimal('9263092.465182'), Decimal('6204.950195'))
(datetime.date(2025, 7, 1), Decimal('9181709.414668'), Decimal('6198.009766'))
(datetime.date(2025, 7, 2), Decimal('9054321.250570'), Decimal('6227.419922'))
(datetime.date(2025, 7, 3), Decimal('9325640.339018'), Decimal('6279.350098'))
(datetime.date(2025, 7, 4), Decimal('9360532.463405'), None)
(datetime.date(2025, 7, 7), Decimal('9337523.923074'), Decimal('6229.979980'))
(datetime.date(2025, 7, 8), Decimal('9302203.177317'), Decimal('6225.520020'))
(datetime.date(2025, 7, 9), Decimal('9338122.035801'), Decimal('6263.259766'))
(datetime.date(2025, 7, 10), Decimal('9541743.483381'), Decimal('6280.459961'))
(datetime.date(2025, 7, 11), Decimal('9934947.612549'), Decimal('6259.750000'))
(datetime.date(2025, 7, 14), Decimal('10222853.345055'), Decimal('6268.560059'))
(datetime.date(2025, 7, 15), Decimal('10301939.218478'), Decimal('6243.759766'))
(datetime.date(2025, 7, 16), Decimal('10119542.204331'), Decimal('6263.700195'))
(datetime.date(2025, 7, 17), Decimal('10198739.393321'), Decimal('6297.359863'))
(datetime.date(2025, 7, 18), Decimal('10277885.478397'), Decimal('6296.790039'))
(datetime.date(2025, 7, 21), Decimal('10101549.352407'), Decimal('6305.600098'))
(datetime.date(2025, 7, 22), Decimal('10136533.758092'), Decimal('6309.620117'))
(datetime.date(2025, 7, 23), Decimal('10357349.266440'), Decimal('6358.910156'))
(datetime.date(2025, 7, 24), Decimal('10249425.749007'), Decimal('6363.350098'))
(datetime.date(2025, 7, 25), Decimal('10229427.683390'), Decimal('6388.640137'))
(datetime.date(2025, 7, 28), Decimal('10330494.375552'), Decimal('6389.770020'))
(datetime.date(2025, 7, 29), Decimal('10240072.841856'), Decimal('6370.859863'))
(datetime.date(2025, 7, 30), Decimal('10260715.669243'), Decimal('6362.899902'))
(datetime.date(2025, 7, 31), Decimal('10330510.927891'), Decimal('6339.390137'))
(datetime.date(2025, 8, 1), Decimal('10122552.718401'), Decimal('6238.009766'))
(datetime.date(2025, 8, 4), Decimal('9963363.104407'), Decimal('6329.939941'))
(datetime.date(2025, 8, 5), Decimal('10119947.866363'), Decimal('6299.189941'))
(datetime.date(2025, 8, 6), Decimal('10011721.550657'), Decimal('6345.060059'))
(datetime.date(2025, 8, 7), Decimal('10094655.435390'), Decimal('6340.000000'))
(datetime.date(2025, 8, 8), Decimal('10270107.263259'), Decimal('6389.450195'))
(datetime.date(2025, 8, 11), Decimal('10434491.300113'), Decimal('6373.450195'))
(datetime.date(2025, 8, 12), Decimal('10412275.449239'), Decimal('6445.759766'))
(datetime.date(2025, 8, 13), Decimal('10529495.638104'), Decimal('6466.580078'))
(datetime.date(2025, 8, 14), Decimal('10805439.783697'), Decimal('6468.540039'))
(datetime.date(2025, 8, 15), Decimal('10383230.847886'), Decimal('6449.799805'))
(datetime.date(2025, 8, 18), Decimal('10286533.101170'), Decimal('6449.149902'))
(datetime.date(2025, 8, 19), Decimal('10148644.242275'), Decimal('6411.370117'))
(datetime.date(2025, 8, 20), Decimal('9819786.419050'), Decimal('6395.779785'))
(datetime.date(2025, 8, 21), Decimal('9942066.543755'), Decimal('6370.169922'))
(datetime.date(2025, 8, 22), Decimal('9813063.277506'), Decimal('6466.910156'))
(datetime.date(2025, 8, 25), Decimal('9903221.350806'), Decimal('6439.319824'))
(datetime.date(2025, 8, 26), Decimal('9653212.189244'), Decimal('6465.939941'))
(datetime.date(2025, 8, 27), Decimal('9801777.668907'), Decimal('6481.399902'))
(datetime.date(2025, 8, 28), Decimal('9749130.258868'), Decimal('6501.859863'))
(datetime.date(2025, 8, 29), Decimal('9856302.068935'), Decimal('6460.259766'))
(datetime.date(2025, 9, 1), Decimal('9545191.818462'), None)
(datetime.date(2025, 9, 2), Decimal('9606486.079009'), Decimal('6415.540039'))
(datetime.date(2025, 9, 3), Decimal('9784574.242949'), Decimal('6448.259766'))
(datetime.date(2025, 9, 4), Decimal('9838796.609222'), Decimal('6502.080078'))
(datetime.date(2025, 9, 5), Decimal('9765163.284050'), Decimal('6481.500000'))
(datetime.date(2025, 9, 8), Decimal('9800346.003034'), Decimal('6495.149902'))
(datetime.date(2025, 9, 9), Decimal('9856054.849015'), Decimal('6512.609863'))
(datetime.date(2025, 9, 10), Decimal('9840553.151485'), Decimal('6532.040039'))
(datetime.date(2025, 9, 11), Decimal('10035954.764446'), Decimal('6587.470215'))
(datetime.date(2025, 9, 12), Decimal('10195205.098488'), Decimal('6584.290039'))
(datetime.date(2025, 9, 15), Decimal('10184894.127284'), Decimal('6615.279785'))
(datetime.date(2025, 9, 16), Decimal('10169238.650025'), Decimal('6606.759766'))
(datetime.date(2025, 9, 17), Decimal('10261685.530264'), Decimal('6600.350098'))
(datetime.date(2025, 9, 18), Decimal('10237752.888404'), Decimal('6631.959961'))
(datetime.date(2025, 9, 19), Decimal('10333070.257186'), Decimal('6664.359863'))
(datetime.date(2025, 9, 22), Decimal('10158260.693491'), Decimal('6693.750000'))
(datetime.date(2025, 9, 23), Decimal('9951646.271657'), Decimal('6656.919922'))
(datetime.date(2025, 9, 24), Decimal('9948492.512889'), Decimal('6637.970215'))
(datetime.date(2025, 9, 25), Decimal('10060469.351466'), Decimal('6604.720215'))
(datetime.date(2025, 9, 26), Decimal('9673068.167457'), Decimal('6643.700195'))
(datetime.date(2025, 9, 29), Decimal('9944472.608697'), Decimal('6661.209961'))
(datetime.date(2025, 9, 30), Decimal('10139763.924083'), Decimal('6688.459961'))
(datetime.date(2025, 10, 1), Decimal('10130020.723922'), Decimal('6711.200195'))
(datetime.date(2025, 10, 2), Decimal('10509252.859359'), Decimal('6715.350098'))
(datetime.date(2025, 10, 3), Decimal('10700725.995237'), Decimal('6715.790039'))
(datetime.date(2025, 10, 6), Decimal('10959365.064936'), Decimal('6740.279785'))
(datetime.date(2025, 10, 7), Decimal('11070472.246733'), Decimal('6714.589844'))
(datetime.date(2025, 10, 8), Decimal('10783920.730193'), Decimal('6753.720215'))
(datetime.date(2025, 10, 9), Decimal('10949945.979090'), Decimal('6735.109863'))
(datetime.date(2025, 10, 10), Decimal('10814774.599012'), Decimal('6552.509766'))
(datetime.date(2025, 10, 13), Decimal('10223942.881585'), Decimal('6654.720215'))
(datetime.date(2025, 10, 14), Decimal('10216224.051871'), Decimal('6644.310059'))
(datetime.date(2025, 10, 15), Decimal('10046351.075826'), Decimal('6671.060059'))
(datetime.date(2025, 10, 16), Decimal('9721344.884649'), Decimal('6629.069824'))
(datetime.date(2025, 10, 17), Decimal('9509774.024195'), Decimal('6664.009766'))
(datetime.date(2025, 10, 20), Decimal('9558930.877185'), Decimal('6735.129883'))
(datetime.date(2025, 10, 21), Decimal('9720308.914971'), Decimal('6735.350098'))
(datetime.date(2025, 10, 22), Decimal('9549158.301143'), Decimal('6699.399902'))
(datetime.date(2025, 10, 23), Decimal('9442499.946296'), Decimal('6738.439941'))
(datetime.date(2025, 10, 24), Decimal('9659976.397608'), Decimal('6791.689941'))
(datetime.date(2025, 10, 27), Decimal('10055171.794297'), Decimal('6875.160156'))
(datetime.date(2025, 10, 28), Decimal('10073474.454011'), Decimal('6890.890137'))
(datetime.date(2025, 10, 29), Decimal('9965129.220872'), Decimal('6890.589844'))
(datetime.date(2025, 10, 30), Decimal('9722166.865440'), Decimal('6822.339844'))
(datetime.date(2025, 10, 31), Decimal('9593893.171045'), Decimal('6840.200195'))
(datetime.date(2025, 11, 3), Decimal('9824421.072228'), Decimal('6851.970215'))
(datetime.date(2025, 11, 4), Decimal('9450928.858755'), Decimal('6771.549805'))
(datetime.date(2025, 11, 5), Decimal('9018317.599499'), Decimal('6796.290039'))
(datetime.date(2025, 11, 6), Decimal('9199126.082981'), Decimal('6720.319824'))
(datetime.date(2025, 11, 7), Decimal('8984607.813502'), Decimal('6728.799805'))
(datetime.date(2025, 11, 10), Decimal('9283589.006016'), Decimal('6832.430176'))
(datetime.date(2025, 11, 11), Decimal('9394913.182234'), Decimal('6846.609863'))
(datetime.date(2025, 11, 12), Decimal('9108594.696794'), Decimal('6850.919922'))
(datetime.date(2025, 11, 13), Decimal('8994239.327086'), Decimal('6737.490234'))
(datetime.date(2025, 11, 14), Decimal('8857694.854444'), Decimal('6734.109863'))
(datetime.date(2025, 11, 17), Decimal('8373085.239388'), Decimal('6672.410156'))
(datetime.date(2025, 11, 18), Decimal('8157780.455111'), Decimal('6617.319824'))
(datetime.date(2025, 11, 19), Decimal('8219844.429071'), Decimal('6642.160156'))
(datetime.date(2025, 11, 20), Decimal('8084502.705830'), Decimal('6538.759766'))
(datetime.date(2025, 11, 21), Decimal('7685198.360480'), Decimal('6602.990234'))
(datetime.date(2025, 11, 24), Decimal('7778520.446851'), Decimal('6705.120117'))
(datetime.date(2025, 11, 25), Decimal('7865475.253834'), Decimal('6765.879883'))
(datetime.date(2025, 11, 26), Decimal('7783791.323602'), Decimal('6812.609863'))
(datetime.date(2025, 11, 27), Decimal('8066930.863801'), None)
(datetime.date(2025, 11, 28), Decimal('8157156.351484'), Decimal('6849.089844'))
(datetime.date(2025, 12, 1), Decimal('8078246.317718'), Decimal('6812.629883'))
(datetime.date(2025, 12, 2), Decimal('7731939.315083'), Decimal('6829.370117'))
(datetime.date(2025, 12, 3), Decimal('8213485.439947'), Decimal('6849.720215'))
(datetime.date(2025, 12, 4), Decimal('8441734.894690'), Decimal('6857.120117'))
(datetime.date(2025, 12, 5), Decimal('8277612.193785'), Decimal('6870.399902'))
(datetime.date(2025, 12, 8), Decimal('8110183.521497'), Decimal('6846.509766'))
(datetime.date(2025, 12, 9), Decimal('8167418.756507'), Decimal('6840.509766'))
(datetime.date(2025, 12, 10), Decimal('8337407.116606'), Decimal('6886.680176'))
(datetime.date(2025, 12, 11), Decimal('8261440.281356'), Decimal('6901.000000'))
(datetime.date(2025, 12, 12), Decimal('8347818.307928'), Decimal('6827.410156'))
(datetime.date(2025, 12, 15), Decimal('7992348.231966'), Decimal('6816.509766'))
(datetime.date(2025, 12, 16), Decimal('7844409.288927'), Decimal('6800.259766'))
(datetime.date(2025, 12, 17), Decimal('7987315.985985'), Decimal('6721.430176'))
(datetime.date(2025, 12, 18), Decimal('7781471.915537'), Decimal('6774.759766'))
(datetime.date(2025, 12, 19), Decimal('7712879.171309'), Decimal('6834.500000'))
(datetime.date(2025, 12, 22), Decimal('7933999.654740'), Decimal('6878.490234'))
(datetime.date(2025, 12, 23), Decimal('7929162.759663'), Decimal('6909.790039'))
(datetime.date(2025, 12, 24), Decimal('7820620.968822'), Decimal('6932.049805'))
(datetime.date(2025, 12, 26), Decimal('7860175.221035'), Decimal('6929.939941'))
(datetime.date(2025, 12, 29), Decimal('7887770.596681'), Decimal('6905.740234'))
(datetime.date(2025, 12, 30), Decimal('7835388.056690'), Decimal('6896.240234'))
(datetime.date(2025, 12, 31), Decimal('7936951.056509'), Decimal('6845.500000'))
(datetime.date(2026, 1, 1), Decimal('7875103.911537'), None)
(datetime.date(2026, 1, 2), Decimal('7982611.090932'), Decimal('6858.470215'))
(datetime.date(2026, 1, 5), Decimal('8224912.970330'), Decimal('6902.049805'))
(datetime.date(2026, 1, 6), Decimal('8475311.204337'), Decimal('6944.819824'))
(datetime.date(2026, 1, 7), Decimal('8443838.294347'), Decimal('6920.930176'))
(datetime.date(2026, 1, 8), Decimal('8200790.873529'), Decimal('6921.459961'))
(datetime.date(2026, 1, 9), Decimal('8179932.125614'), Decimal('6966.279785'))
(datetime.date(2026, 1, 12), Decimal('8196362.955223'), Decimal('6977.270020'))
(datetime.date(2026, 1, 13), Decimal('8214254.506812'), Decimal('6963.740234'))
(datetime.date(2026, 1, 14), Decimal('8600260.479528'), Decimal('6926.600098'))
(datetime.date(2026, 1, 15), Decimal('8754772.557780'), Decimal('6944.470215'))
(datetime.date(2026, 1, 16), Decimal('8637202.771129'), Decimal('6940.009766'))
(datetime.date(2026, 1, 19), Decimal('8504968.615885'), None)
(datetime.date(2026, 1, 20), Decimal('8414003.970645'), Decimal('6796.859863'))
(datetime.date(2026, 1, 21), Decimal('8046939.830277'), Decimal('6875.620117'))
(datetime.date(2026, 1, 22), Decimal('8179241.969295'), Decimal('6913.350098'))
(datetime.date(2026, 1, 23), Decimal('8189307.776815'), Decimal('6915.609863'))
(datetime.date(2026, 1, 26), Decimal('7931480.810441'), Decimal('6950.229980'))
(datetime.date(2026, 1, 27), Decimal('8098992.121061'), Decimal('6978.600098'))
(datetime.date(2026, 1, 28), Decimal('8165356.488930'), Decimal('6978.029785'))
(datetime.date(2026, 1, 29), Decimal('8206661.924142'), Decimal('6969.009766'))
(datetime.date(2026, 1, 30), Decimal('7762053.970031'), Decimal('6939.029785'))
(datetime.date(2026, 2, 2), Decimal('7055170.474775'), Decimal('6976.439941'))
(datetime.date(2026, 2, 3), Decimal('7124353.514367'), Decimal('6917.810059'))
(datetime.date(2026, 2, 4), Decimal('6839512.652076'), Decimal('6882.720215'))
(datetime.date(2026, 2, 5), Decimal('6617843.606631'), Decimal('6798.399902'))
(datetime.date(2026, 2, 6), Decimal('5676634.189757'), Decimal('6932.299805'))
(datetime.date(2026, 2, 9), Decimal('6388983.809905'), Decimal('6964.819824'))
(datetime.date(2026, 2, 10), Decimal('6363124.007123'), Decimal('6941.810059'))
(datetime.date(2026, 2, 11), Decimal('6230645.199778'), Decimal('6941.470215'))
(datetime.date(2026, 2, 12), Decimal('6073656.888034'), Decimal('6832.759766'))
(datetime.date(2026, 2, 13), Decimal('5993963.255323'), Decimal('6836.169922'))
(datetime.date(2026, 2, 16), Decimal('6222983.548183'), None)
(datetime.date(2026, 2, 17), Decimal('6255749.578602'), Decimal('6843.220215'))
(datetime.date(2026, 2, 18), Decimal('6116329.755578'), Decimal('6881.310059'))
(datetime.date(2026, 2, 19), Decimal('6033801.765391'), Decimal('6861.890137'))
(datetime.date(2026, 2, 20), Decimal('6092367.347486'), Decimal('6909.509766'))
(datetime.date(2026, 2, 23), Decimal('6132044.383909'), Decimal('6837.750000'))
(datetime.date(2026, 2, 24), Decimal('5877904.816486'), Decimal('6890.069824'))
(datetime.date(2026, 2, 25), Decimal('5825506.041088'), Decimal('6946.129883'))
(datetime.date(2026, 2, 26), Decimal('6179906.746479'), Decimal('6908.859863'))
(datetime.date(2026, 2, 27), Decimal('6139221.658943'), Decimal('6878.879883'))
(datetime.date(2026, 3, 2), Decimal('5984275.487394'), Decimal('6881.620117'))
(datetime.date(2026, 3, 3), Decimal('6305544.630558'), Decimal('6816.629883'))
(datetime.date(2026, 3, 4), Decimal('6286193.488373'), Decimal('6869.500000'))
(datetime.date(2026, 3, 5), Decimal('6694568.064726'), Decimal('6830.709961'))
(datetime.date(2026, 3, 6), Decimal('6505413.051213'), Decimal('6740.020020'))
(datetime.date(2026, 3, 9), Decimal('6071162.609842'), Decimal('6795.990234'))
(datetime.date(2026, 3, 10), Decimal('6319544.712080'), Decimal('6781.479980'))
(datetime.date(2026, 3, 11), Decimal('6427459.132594'), Decimal('6775.799805'))
(datetime.date(2026, 3, 12), Decimal('6476952.781588'), Decimal('6672.620117'))
(datetime.date(2026, 3, 13), Decimal('6517601.857024'), Decimal('6632.189941'))
(datetime.date(2026, 3, 16), Decimal('6727548.658016'), Decimal('6699.379883'))
(datetime.date(2026, 3, 17), Decimal('6906940.623961'), Decimal('6716.089844'))
(datetime.date(2026, 3, 18), Decimal('6829860.404015'), Decimal('6624.700195'))
(datetime.date(2026, 3, 19), Decimal('6639390.135900'), Decimal('6606.490234'))
(datetime.date(2026, 3, 20), Decimal('6504037.303026'), Decimal('6506.479980'))
(datetime.date(2026, 3, 23), Decimal('6364717.089252'), Decimal('6581.000000'))
(datetime.date(2026, 3, 24), Decimal('6614293.785504'), Decimal('6556.370117'))
(datetime.date(2026, 3, 25), Decimal('6649392.307316'), Decimal('6591.899902'))
(datetime.date(2026, 3, 26), Decimal('6712173.732416'), Decimal('6477.160156'))
(datetime.date(2026, 3, 27), Decimal('6487672.474785'), Decimal('6368.850098'))
(datetime.date(2026, 3, 30), Decimal('6252812.763420'), Decimal('6343.720215'))
(datetime.date(2026, 3, 31), Decimal('6293233.346703'), Decimal('6528.520020'))
(datetime.date(2026, 4, 1), Decimal('6378628.791276'), Decimal('6575.319824'))
(datetime.date(2026, 4, 2), Decimal('6307964.144412'), Decimal('6582.689941'))

In [12]:
#Compare Ethereum and NASDAQ daily prices for 2025.
cursor.execute("""
SELECT 
    cp.date,
    cp.price_inr AS ethereum_price,
    sp.close AS nasdaq_price

FROM crypto_prices cp

-- Join using same date
JOIN stock_prices sp 
ON cp.date = sp.date

-- Filter Ethereum
WHERE cp.coin_id = 'ethereum'

-- Filter NASDAQ
AND sp.ticker = '^IXIC'

-- Filter year (change if needed)
AND YEAR(cp.date) = 2025

-- Sort for trend
ORDER BY cp.date
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2025, 4, 15), Decimal('139502.269181'), Decimal('16823.169922'))
(datetime.date(2025, 4, 16), Decimal('136118.340300'), Decimal('16307.160156'))
(datetime.date(2025, 4, 17), Decimal('135084.250075'), Decimal('16286.450195'))
(datetime.date(2025, 4, 21), Decimal('135372.221202'), Decimal('15870.900391'))
(datetime.date(2025, 4, 22), Decimal('134334.008185'), Decimal('16300.419922'))
(datetime.date(2025, 4, 23), Decimal('149984.444802'), Decimal('16708.050781'))
(datetime.date(2025, 4, 24), Decimal('153384.691226'), Decimal('17166.039063'))
(datetime.date(2025, 4, 25), Decimal('150793.822639'), Decimal('17382.939453'))
(datetime.date(2025, 4, 28), Decimal('153154.647160'), Decimal('17366.130859'))
(datetime.date(2025, 4, 29), Decimal('153246.471992'), Decimal('17461.320313'))
(datetime.date(2025, 4, 30), Decimal('153045.868306'), Decimal('17446.339844'))
(datetime.date(2025, 5, 1), Decimal('151706.989211'), Decimal('17710.740234'))
(datetime.date(2025, 5, 2), Decimal('155745.169241'), Decimal('17977.730469'))
(datetime.date(2025, 5, 5), Decimal('152837.106066'), Decimal('17844.240234'))
(datetime.date(2025, 5, 6), Decimal('153282.693897'), Decimal('17689.660156'))
(datetime.date(2025, 5, 7), Decimal('153903.860522'), Decimal('17738.160156'))
(datetime.date(2025, 5, 8), Decimal('153546.465434'), Decimal('17928.140625'))
(datetime.date(2025, 5, 9), Decimal('189067.053860'), Decimal('17928.919922'))
(datetime.date(2025, 5, 12), Decimal('214170.100120'), Decimal('18708.339844'))
(datetime.date(2025, 5, 13), Decimal('211740.195869'), Decimal('19010.089844'))
(datetime.date(2025, 5, 14), Decimal('227649.060175'), Decimal('19146.810547'))
(datetime.date(2025, 5, 15), Decimal('222550.861260'), Decimal('19112.320313'))
(datetime.date(2025, 5, 16), Decimal('217226.914605'), Decimal('19211.099609'))
(datetime.date(2025, 5, 19), Decimal('210787.975693'), Decimal('19215.460938'))
(datetime.date(2025, 5, 20), Decimal('215738.556840'), Decimal('19142.710938'))
(datetime.date(2025, 5, 21), Decimal('215915.199355'), Decimal('18872.640625'))
(datetime.date(2025, 5, 22), Decimal('219047.575634'), Decimal('18925.740234'))
(datetime.date(2025, 5, 23), Decimal('228450.369638'), Decimal('18737.210938'))
(datetime.date(2025, 5, 26), Decimal('216970.852280'), None)
(datetime.date(2025, 5, 27), Decimal('218190.675235'), Decimal('19199.160156'))
(datetime.date(2025, 5, 28), Decimal('227238.584850'), Decimal('19100.939453'))
(datetime.date(2025, 5, 29), Decimal('228525.939096'), Decimal('19175.869141'))
(datetime.date(2025, 5, 30), Decimal('224768.844035'), Decimal('19113.769531'))
(datetime.date(2025, 6, 2), Decimal('217089.574074'), Decimal('19242.609375'))
(datetime.date(2025, 6, 3), Decimal('222777.498728'), Decimal('19398.960938'))
(datetime.date(2025, 6, 4), Decimal('222455.178610'), Decimal('19460.490234'))
(datetime.date(2025, 6, 5), Decimal('224236.444163'), Decimal('19298.449219'))
(datetime.date(2025, 6, 6), Decimal('207961.654189'), Decimal('19529.949219'))
(datetime.date(2025, 6, 9), Decimal('215217.423364'), Decimal('19591.240234'))
(datetime.date(2025, 6, 10), Decimal('230255.547118'), Decimal('19714.990234'))
(datetime.date(2025, 6, 11), Decimal('240556.865727'), Decimal('19615.880859'))
(datetime.date(2025, 6, 12), Decimal('237276.581795'), Decimal('19662.490234'))
(datetime.date(2025, 6, 13), Decimal('227345.610242'), Decimal('19406.830078'))
(datetime.date(2025, 6, 16), Decimal('219421.869835'), Decimal('19701.210938'))
(datetime.date(2025, 6, 17), Decimal('220541.897449'), Decimal('19521.089844'))
(datetime.date(2025, 6, 18), Decimal('217182.056291'), Decimal('19546.269531'))
(datetime.date(2025, 6, 19), Decimal('218382.420147'), None)
(datetime.date(2025, 6, 20), Decimal('218767.013088'), Decimal('19447.410156'))
(datetime.date(2025, 6, 23), Decimal('192852.030967'), Decimal('19630.970703'))
(datetime.date(2025, 6, 24), Decimal('209315.247806'), Decimal('19912.529297'))
(datetime.date(2025, 6, 25), Decimal('210338.280603'), Decimal('19973.550781'))
(datetime.date(2025, 6, 26), Decimal('207894.423633'), Decimal('20167.910156'))
(datetime.date(2025, 6, 27), Decimal('206903.990972'), Decimal('20273.460938'))
(datetime.date(2025, 6, 30), Decimal('213866.808206'), Decimal('20369.730469'))
(datetime.date(2025, 7, 1), Decimal('213247.902754'), Decimal('20202.890625'))
(datetime.date(2025, 7, 2), Decimal('206191.537951'), Decimal('20393.130859'))
(datetime.date(2025, 7, 3), Decimal('220583.067715'), Decimal('20601.099609'))
(datetime.date(2025, 7, 4), Decimal('221209.207186'), None)
(datetime.date(2025, 7, 7), Decimal('219842.285096'), Decimal('20412.519531'))
(datetime.date(2025, 7, 8), Decimal('218478.507032'), Decimal('20418.460938'))
(datetime.date(2025, 7, 9), Decimal('224192.012935'), Decimal('20611.339844'))
(datetime.date(2025, 7, 10), Decimal('237634.328591'), Decimal('20630.660156'))
(datetime.date(2025, 7, 11), Decimal('252785.182611'), Decimal('20585.529297'))
(datetime.date(2025, 7, 14), Decimal('255256.074912'), Decimal('20640.330078'))
(datetime.date(2025, 7, 15), Decimal('258953.022960'), Decimal('20677.800781'))
(datetime.date(2025, 7, 16), Decimal('269423.172852'), Decimal('20730.490234'))
(datetime.date(2025, 7, 17), Decimal('289273.061958'), Decimal('20885.650391'))
(datetime.date(2025, 7, 18), Decimal('299604.700132'), Decimal('20895.650391'))
(datetime.date(2025, 7, 21), Decimal('323799.563511'), Decimal('20974.179688'))
(datetime.date(2025, 7, 22), Decimal('324888.026671'), Decimal('20892.689453'))
(datetime.date(2025, 7, 23), Decimal('323522.285507'), Decimal('21020.019531'))
(datetime.date(2025, 7, 24), Decimal('313632.809934'), Decimal('21057.960938'))
(datetime.date(2025, 7, 25), Decimal('320521.286638'), Decimal('21108.320313'))
(datetime.date(2025, 7, 28), Decimal('334271.335633'), Decimal('21178.580078'))
(datetime.date(2025, 7, 29), Decimal('328567.307202'), Decimal('21098.289063'))
(datetime.date(2025, 7, 30), Decimal('329848.444896'), Decimal('21129.669922'))
(datetime.date(2025, 7, 31), Decimal('333798.497867'), Decimal('21122.449219'))
(datetime.date(2025, 8, 1), Decimal('323419.739184'), Decimal('20650.130859'))
(datetime.date(2025, 8, 4), Decimal('305147.659724'), Decimal('21053.580078'))
(datetime.date(2025, 8, 5), Decimal('326586.856083'), Decimal('20916.550781'))
(datetime.date(2025, 8, 6), Decimal('316895.551838'), Decimal('21169.419922'))
(datetime.date(2025, 8, 7), Decimal('323322.001028'), Decimal('21242.699219'))
(datetime.date(2025, 8, 8), Decimal('341975.042294'), Decimal('21450.019531'))
(datetime.date(2025, 8, 11), Decimal('372140.597063'), Decimal('21385.400391'))
(datetime.date(2025, 8, 12), Decimal('370718.817449'), Decimal('21681.900391'))
(datetime.date(2025, 8, 13), Decimal('403547.061908'), Decimal('21713.140625'))
(datetime.date(2025, 8, 14), Decimal('416582.605127'), Decimal('21710.669922'))
(datetime.date(2025, 8, 15), Decimal('399375.212719'), Decimal('21622.980469'))
(datetime.date(2025, 8, 18), Decimal('392681.418991'), Decimal('21629.769531'))
(datetime.date(2025, 8, 19), Decimal('376878.098282'), Decimal('21314.949219'))
(datetime.date(2025, 8, 20), Decimal('354772.704309'), Decimal('21172.859375'))
(datetime.date(2025, 8, 21), Decimal('376832.666663'), Decimal('21100.310547'))
(datetime.date(2025, 8, 22), Decimal('368766.663947'), Decimal('21496.539063'))
(datetime.date(2025, 8, 25), Decimal('417273.907118'), Decimal('21449.289063'))
(datetime.date(2025, 8, 26), Decimal('383869.230416'), Decimal('21544.269531'))
(datetime.date(2025, 8, 27), Decimal('403346.846734'), Decimal('21590.140625'))
(datetime.date(2025, 8, 28), Decimal('394479.821080'), Decimal('21705.160156'))
(datetime.date(2025, 8, 29), Decimal('394824.628584'), Decimal('21455.550781'))
(datetime.date(2025, 9, 1), Decimal('386992.074421'), None)
(datetime.date(2025, 9, 2), Decimal('378688.487081'), Decimal('21279.630859'))
(datetime.date(2025, 9, 3), Decimal('380669.060827'), Decimal('21497.730469'))
(datetime.date(2025, 9, 4), Decimal('391914.257365'), Decimal('21707.689453'))
(datetime.date(2025, 9, 5), Decimal('379062.507112'), Decimal('21700.390625'))
(datetime.date(2025, 9, 8), Decimal('379557.731567'), Decimal('21798.699219'))
(datetime.date(2025, 9, 9), Decimal('379169.380394'), Decimal('21879.490234'))
(datetime.date(2025, 9, 10), Decimal('380163.959897'), Decimal('21886.060547'))
(datetime.date(2025, 9, 11), Decimal('382811.635601'), Decimal('22043.070313'))
(datetime.date(2025, 9, 12), Decimal('393614.073912'), Decimal('22141.099609'))
(datetime.date(2025, 9, 15), Decimal('406940.596240'), Decimal('22348.750000'))
(datetime.date(2025, 9, 16), Decimal('398693.429952'), Decimal('22333.960938'))
(datetime.date(2025, 9, 17), Decimal('395856.797623'), Decimal('22261.330078'))
(datetime.date(2025, 9, 18), Decimal('403666.756890'), Decimal('22470.720703'))
(datetime.date(2025, 9, 19), Decimal('404926.983275'), Decimal('22631.480469'))
(datetime.date(2025, 9, 22), Decimal('392295.475243'), Decimal('22788.980469'))
(datetime.date(2025, 9, 23), Decimal('370875.271422'), Decimal('22573.470703'))
(datetime.date(2025, 9, 24), Decimal('369992.091901'), Decimal('22497.859375'))
(datetime.date(2025, 9, 25), Decimal('368312.965606'), Decimal('22384.699219'))
(datetime.date(2025, 9, 26), Decimal('342937.444019'), Decimal('22484.070313'))
(datetime.date(2025, 9, 29), Decimal('367286.122984'), Decimal('22591.150391'))
(datetime.date(2025, 9, 30), Decimal('373944.853294'), Decimal('22660.009766'))
(datetime.date(2025, 10, 1), Decimal('368177.371385'), Decimal('22755.160156'))
(datetime.date(2025, 10, 2), Decimal('385235.779735'), Decimal('22844.050781'))
(datetime.date(2025, 10, 3), Decimal('397823.051940'), Decimal('22780.509766'))
(datetime.date(2025, 10, 6), Decimal('400668.642140'), Decimal('22941.669922'))
(datetime.date(2025, 10, 7), Decimal('416041.060854'), Decimal('22788.359375'))
(datetime.date(2025, 10, 8), Decimal('395289.802631'), Decimal('23043.380859'))
(datetime.date(2025, 10, 9), Decimal('401911.048471'), Decimal('23024.630859'))
(datetime.date(2025, 10, 10), Decimal('388222.872053'), Decimal('22204.429688'))
(datetime.date(2025, 10, 13), Decimal('369207.336266'), Decimal('22694.609375'))
(datetime.date(2025, 10, 14), Decimal('376492.357405'), Decimal('22521.699219'))
(datetime.date(2025, 10, 15), Decimal('366574.058384'), Decimal('22670.080078'))
(datetime.date(2025, 10, 16), Decimal('349761.388471'), Decimal('22562.539063'))
(datetime.date(2025, 10, 17), Decimal('342302.332206'), Decimal('22679.970703'))
(datetime.date(2025, 10, 20), Decimal('350696.680434'), Decimal('22990.539063'))
(datetime.date(2025, 10, 21), Decimal('349657.073531'), Decimal('22953.669922'))
(datetime.date(2025, 10, 22), Decimal('341303.984264'), Decimal('22740.400391'))
(datetime.date(2025, 10, 23), Decimal('333571.215359'), Decimal('22941.800781'))
(datetime.date(2025, 10, 24), Decimal('338462.929082'), Decimal('23204.869141'))
(datetime.date(2025, 10, 27), Decimal('365539.562112'), Decimal('23637.460938'))
(datetime.date(2025, 10, 28), Decimal('363758.942322'), Decimal('23827.490234'))
(datetime.date(2025, 10, 29), Decimal('351342.532572'), Decimal('23958.470703'))
(datetime.date(2025, 10, 30), Decimal('344315.528945'), Decimal('23581.140625'))
(datetime.date(2025, 10, 31), Decimal('337015.499062'), Decimal('23724.960938'))
(datetime.date(2025, 11, 3), Decimal('347169.858003'), Decimal('23834.720703'))
(datetime.date(2025, 11, 4), Decimal('319468.258320'), Decimal('23348.640625'))
(datetime.date(2025, 11, 5), Decimal('292527.201423'), Decimal('23499.800781'))
(datetime.date(2025, 11, 6), Decimal('303546.180795'), Decimal('23053.990234'))
(datetime.date(2025, 11, 7), Decimal('293412.527668'), Decimal('23004.539063'))
(datetime.date(2025, 11, 10), Decimal('317071.729162'), Decimal('23527.169922'))
(datetime.date(2025, 11, 11), Decimal('316207.159735'), Decimal('23468.300781'))
(datetime.date(2025, 11, 12), Decimal('302271.191060'), Decimal('23406.460938'))
(datetime.date(2025, 11, 13), Decimal('302072.225249'), Decimal('22870.359375'))
(datetime.date(2025, 11, 14), Decimal('287385.518250'), Decimal('22900.589844'))
(datetime.date(2025, 11, 17), Decimal('275080.205979'), Decimal('22708.070313'))
(datetime.date(2025, 11, 18), Decimal('267796.573111'), Decimal('22432.849609'))
(datetime.date(2025, 11, 19), Decimal('276052.048981'), Decimal('22564.230469'))
(datetime.date(2025, 11, 20), Decimal('267032.830083'), Decimal('22078.050781'))
(datetime.date(2025, 11, 21), Decimal('251183.081268'), Decimal('22273.080078'))
(datetime.date(2025, 11, 24), Decimal('250950.128363'), Decimal('22872.009766'))
(datetime.date(2025, 11, 25), Decimal('263283.403583'), Decimal('23025.589844'))
(datetime.date(2025, 11, 26), Decimal('263444.939990'), Decimal('23214.689453'))
(datetime.date(2025, 11, 27), Decimal('269938.197095'), None)
(datetime.date(2025, 11, 28), Decimal('269490.252798'), Decimal('23365.689453'))
(datetime.date(2025, 12, 1), Decimal('267424.459259'), Decimal('23275.919922'))
(datetime.date(2025, 12, 2), Decimal('250829.944089'), Decimal('23413.669922'))
(datetime.date(2025, 12, 3), Decimal('269370.304182'), Decimal('23454.089844'))
(datetime.date(2025, 12, 4), Decimal('288132.425357'), Decimal('23505.140625'))
(datetime.date(2025, 12, 5), Decimal('281520.951599'), Decimal('23578.130859'))
(datetime.date(2025, 12, 8), Decimal('274616.237564'), Decimal('23545.900391'))
(datetime.date(2025, 12, 9), Decimal('281685.692185'), Decimal('23576.490234'))
(datetime.date(2025, 12, 10), Decimal('298746.963031'), Decimal('23654.150391'))
(datetime.date(2025, 12, 11), Decimal('298675.714749'), Decimal('23593.859375'))
(datetime.date(2025, 12, 12), Decimal('292065.557142'), Decimal('23195.169922'))
(datetime.date(2025, 12, 15), Decimal('277686.257525'), Decimal('23057.410156'))
(datetime.date(2025, 12, 16), Decimal('269107.822475'), Decimal('23111.460938'))
(datetime.date(2025, 12, 17), Decimal('269596.837410'), Decimal('22693.320313'))
(datetime.date(2025, 12, 18), Decimal('255672.948161'), Decimal('23006.359375'))
(datetime.date(2025, 12, 19), Decimal('255132.826415'), Decimal('23307.619141'))
(datetime.date(2025, 12, 22), Decimal('268857.457211'), Decimal('23428.830078'))
(datetime.date(2025, 12, 23), Decimal('269330.668986'), Decimal('23561.839844'))
(datetime.date(2025, 12, 24), Decimal('265308.330577'), Decimal('23613.310547'))
(datetime.date(2025, 12, 26), Decimal('261698.838882'), Decimal('23593.099609'))
(datetime.date(2025, 12, 29), Decimal('264760.550466'), Decimal('23474.349609'))
(datetime.date(2025, 12, 30), Decimal('263786.422730'), Decimal('23419.080078'))
(datetime.date(2025, 12, 31), Decimal('266620.867155'), Decimal('23241.990234'))

In [13]:
#Find days when oil price spiked and compare with Bitcoin price change
cursor.execute("""
SELECT 
    op.date,
    op.price_inr AS oil_price,
    cp.price_inr AS bitcoin_price

FROM oil_prices op
JOIN crypto_prices cp 
ON op.date = cp.date

WHERE cp.coin_id = 'bitcoin'
ORDER BY op.date
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2025, 4, 15), Decimal('5124.420000'), Decimal('7271599.950977'))
(datetime.date(2025, 4, 16), Decimal('5219.040000'), Decimal('7171572.949307'))
(datetime.date(2025, 4, 17), Decimal('5400.810000'), Decimal('7201187.297551'))
(datetime.date(2025, 4, 21), Decimal('5268.840000'), Decimal('7263849.726469'))
(datetime.date(2025, 4, 22), Decimal('5361.800000'), Decimal('7447341.987487'))
(datetime.date(2025, 4, 23), Decimal('5199.120000'), Decimal('7975735.892698'))
(datetime.date(2025, 4, 24), Decimal('5274.650000'), Decimal('8003280.213214'))
(datetime.date(2025, 4, 25), Decimal('5299.550000'), Decimal('8000169.783417'))
(datetime.date(2025, 4, 28), Decimal('5253.900000'), Decimal('8009924.381134'))
(datetime.date(2025, 4, 29), Decimal('5132.720000'), Decimal('8092853.390806'))
(datetime.date(2025, 4, 30), Decimal('4942.650000'), Decimal('8027696.597799'))
(datetime.date(2025, 5, 1), Decimal('5028.970000'), Decimal('7968688.759781'))
(datetime.date(2025, 5, 2), Decimal('4952.610000'), Decimal('8167058.515488'))
(datetime.date(2025, 5, 5), Decimal('4855.500000'), Decimal('7973099.086450'))
(datetime.date(2025, 5, 6), Decimal('5014.860000'), Decimal('7980688.008703'))
(datetime.date(2025, 5, 7), Decimal('4931.860000'), Decimal('8207545.052482'))
(datetime.date(2025, 5, 8), Decimal('5083.750000'), Decimal('8229539.783984'))
(datetime.date(2025, 5, 9), Decimal('5176.710000'), Decimal('8868161.595114'))
(datetime.date(2025, 5, 12), Decimal('5255.560000'), Decimal('8882429.185762'))
(datetime.date(2025, 5, 13), Decimal('5398.320000'), Decimal('8739740.641206'))
(datetime.date(2025, 5, 14), Decimal('5351.840000'), Decimal('8860925.913889'))
(datetime.date(2025, 5, 15), Decimal('5231.490000'), Decimal('8854656.259617'))
(datetime.date(2025, 5, 16), Decimal('5298.720000'), Decimal('8861418.050018'))
(datetime.date(2025, 5, 19), Decimal('5310.340000'), Decimal('9065676.354330'))
(datetime.date(2025, 5, 20), Decimal('5309.510000'), Decimal('9017978.281234'))
(datetime.date(2025, 5, 21), Decimal('5223.190000'), Decimal('9134061.037906'))
(datetime.date(2025, 5, 22), Decimal('5191.650000'), Decimal('9387459.456661'))
(datetime.date(2025, 5, 23), Decimal('5219.870000'), Decimal('9591418.421810'))
(datetime.date(2025, 5, 27), Decimal('5113.630000'), Decimal('9314436.685236'))
(datetime.date(2025, 5, 28), Decimal('5190.820000'), Decimal('9310175.102672'))
(datetime.date(2025, 5, 29), Decimal('5117.780000'), Decimal('9208280.990680'))
(datetime.date(2025, 5, 30), Decimal('5101.180000'), Decimal('9026592.666677'))
(datetime.date(2025, 6, 2), Decimal('5251.410000'), Decimal('9040802.274014'))
(datetime.date(2025, 6, 3), Decimal('5320.300000'), Decimal('9038740.617012'))
(datetime.date(2025, 6, 4), Decimal('5276.310000'), Decimal('9036688.899610'))
(datetime.date(2025, 6, 5), Decimal('5316.980000'), Decimal('9003749.459209'))
(datetime.date(2025, 6, 6), Decimal('5419.900000'), Decimal('8729536.730078'))
(datetime.date(2025, 6, 9), Decimal('5477.170000'), Decimal('9066867.468852'))
(datetime.date(2025, 6, 10), Decimal('5449.780000'), Decimal('9455619.179044'))
(datetime.date(2025, 6, 11), Decimal('5719.530000'), Decimal('9440056.689266'))
(datetime.date(2025, 6, 12), Decimal('5704.590000'), Decimal('9288882.881869'))
(datetime.date(2025, 6, 13), Decimal('6128.720000'), Decimal('9081227.025134'))
(datetime.date(2025, 6, 16), Decimal('6019.990000'), Decimal('9090411.274773'))
(datetime.date(2025, 6, 17), Decimal('6276.460000'), Decimal('9208980.453923'))
(datetime.date(2025, 6, 18), Decimal('6298.870000'), Decimal('9039952.955659'))
(datetime.date(2025, 6, 20), Decimal('6284.760000'), Decimal('9080584.318377'))
(datetime.date(2025, 6, 23), Decimal('5756.880000'), Decimal('8731873.284684'))
(datetime.date(2025, 6, 24), Decimal('5432.350000'), Decimal('9111429.945371'))
(datetime.date(2025, 6, 25), Decimal('5476.340000'), Decimal('9111165.386620'))
(datetime.date(2025, 6, 26), Decimal('5514.520000'), Decimal('9223086.808659'))
(datetime.date(2025, 6, 27), Decimal('5532.780000'), Decimal('9165684.099752'))
(datetime.date(2025, 6, 30), Decimal('5502.900000'), Decimal('9263092.465182'))
(datetime.date(2025, 7, 1), Decimal('5531.120000'), Decimal('9181709.414668'))
(datetime.date(2025, 7, 2), Decimal('5698.780000'), Decimal('9054321.250570'))
(datetime.date(2025, 7, 3), Decimal('5654.790000'), Decimal('9325640.339018'))
(datetime.date(2025, 7, 7), Decimal('5740.280000'), Decimal('9337523.923074'))
(datetime.date(2025, 7, 8), Decimal('5772.650000'), Decimal('9302203.177317'))
(datetime.date(2025, 7, 9), Decimal('5777.630000'), Decimal('9338122.035801'))
(datetime.date(2025, 7, 10), Decimal('5625.740000'), Decimal('9541743.483381'))
(datetime.date(2025, 7, 11), Decimal('5779.290000'), Decimal('9934947.612549'))
(datetime.date(2025, 7, 14), Decimal('5659.770000'), Decimal('10222853.345055'))
(datetime.date(2025, 7, 15), Decimal('5624.080000'), Decimal('10301939.218478'))
(datetime.date(2025, 7, 16), Decimal('5571.790000'), Decimal('10119542.204331'))
(datetime.date(2025, 7, 17), Decimal('5707.080000'), Decimal('10198739.393321'))
(datetime.date(2025, 7, 18), Decimal('5687.990000'), Decimal('10277885.478397'))
(datetime.date(2025, 7, 21), Decimal('5676.370000'), Decimal('10101549.352407'))
(datetime.date(2025, 7, 22), Decimal('5607.480000'), Decimal('10136533.758092'))
(datetime.date(2025, 7, 23), Decimal('5482.150000'), Decimal('10357349.266440'))
(datetime.date(2025, 7, 24), Decimal('5574.280000'), Decimal('10249425.749007'))
(datetime.date(2025, 7, 25), Decimal('5509.540000'), Decimal('10229427.683390'))
(datetime.date(2025, 7, 28), Decimal('5628.230000'), Decimal('10330494.375552'))
(datetime.date(2025, 7, 29), Decimal('5832.410000'), Decimal('10240072.841856'))
(datetime.date(2025, 7, 30), Decimal('5900.470000'), Decimal('10260715.669243'))
(datetime.date(2025, 7, 31), Decimal('5839.880000'), Decimal('10330510.927891'))
(datetime.date(2025, 8, 1), Decimal('5676.370000'), Decimal('10122552.718401'))
(datetime.date(2025, 8, 4), Decimal('5588.390000'), Decimal('9963363.104407'))
(datetime.date(2025, 8, 5), Decimal('5494.600000'), Decimal('10119947.866363'))
(datetime.date(2025, 8, 6), Decimal('5426.540000'), Decimal('10011721.550657'))
(datetime.date(2025, 8, 7), Decimal('5386.700000'), Decimal('10094655.435390'))
(datetime.date(2025, 8, 8), Decimal('5390.020000'), Decimal('10270107.263259'))
(datetime.date(2025, 8, 11), Decimal('5397.490000'), Decimal('10434491.300113'))
(datetime.date(2025, 8, 12), Decimal('5330.260000'), Decimal('10412275.449239'))
(datetime.date(2025, 8, 13), Decimal('5285.440000'), Decimal('10529495.638104'))
(datetime.date(2025, 8, 14), Decimal('5394.170000'), Decimal('10805439.783697'))
(datetime.date(2025, 8, 15), Decimal('5293.740000'), Decimal('10383230.847886'))
(datetime.date(2025, 8, 18), Decimal('5354.330000'), Decimal('10286533.101170'))
(datetime.date(2025, 8, 19), Decimal('5260.540000'), Decimal('10148644.242275'))
(datetime.date(2025, 8, 20), Decimal('5327.770000'), Decimal('9819786.419050'))
(datetime.date(2025, 8, 21), Decimal('5358.480000'), Decimal('9942066.543755'))
(datetime.date(2025, 8, 22), Decimal('5318.640000'), Decimal('9813063.277506'))
(datetime.date(2025, 8, 25), Decimal('5409.940000'), Decimal('9903221.350806'))
(datetime.date(2025, 8, 26), Decimal('5278.800000'), Decimal('9653212.189244'))
(datetime.date(2025, 8, 27), Decimal('5352.670000'), Decimal('9801777.668907'))
(datetime.date(2025, 8, 28), Decimal('5391.680000'), Decimal('9749130.258868'))
(datetime.date(2025, 8, 29), Decimal('5341.880000'), Decimal('9856302.068935'))
(datetime.date(2025, 9, 2), Decimal('5473.850000'), Decimal('9606486.079009'))
(datetime.date(2025, 9, 3), Decimal('5341.880000'), Decimal('9784574.242949'))
(datetime.date(2025, 9, 4), Decimal('5296.230000'), Decimal('9838796.609222'))
(datetime.date(2025, 9, 5), Decimal('5164.260000'), Decimal('9765163.284050'))
(datetime.date(2025, 9, 8), Decimal('5195.800000'), Decimal('9800346.003034'))
(datetime.date(2025, 9, 9), Decimal('5226.510000'), Decimal('9856054.849015'))
(datetime.date(2025, 9, 10), Decimal('5312.830000'), Decimal('9840553.151485'))
(datetime.date(2025, 9, 11), Decimal('5204.930000'), Decimal('10035954.764446'))
(datetime.date(2025, 9, 12), Decimal('5230.660000'), Decimal('10195205.098488'))
(datetime.date(2025, 9, 15), Decimal('5283.780000'), Decimal('10184894.127284'))
(datetime.date(2025, 9, 16), Decimal('5385.870000'), Decimal('10169238.650025'))
(datetime.date(2025, 9, 17), Decimal('5346.030000'), Decimal('10261685.530264'))
(datetime.date(2025, 9, 18), Decimal('5304.530000'), Decimal('10237752.888404'))
(datetime.date(2025, 9, 19), Decimal('5230.660000'), Decimal('10333070.257186'))
(datetime.date(2025, 9, 22), Decimal('5228.170000'), Decimal('10158260.693491'))
(datetime.date(2025, 9, 23), Decimal('5292.080000'), Decimal('9951646.271657'))
(datetime.date(2025, 9, 24), Decimal('5428.200000'), Decimal('9948492.512889'))
(datetime.date(2025, 9, 25), Decimal('5437.330000'), Decimal('10060469.351466'))
(datetime.date(2025, 9, 26), Decimal('5519.500000'), Decimal('9673068.167457'))
(datetime.date(2025, 9, 29), Decimal('5334.410000'), Decimal('9944472.608697'))
(datetime.date(2025, 9, 30), Decimal('5243.110000'), Decimal('10139763.924083'))
(datetime.date(2025, 10, 1), Decimal('5194.970000'), Decimal('10130020.723922'))
(datetime.date(2025, 10, 2), Decimal('5086.240000'), Decimal('10509252.859359'))
(datetime.date(2025, 10, 3), Decimal('5116.950000'), Decimal('10700725.995237'))
(datetime.date(2025, 10, 6), Decimal('5186.670000'), Decimal('10959365.064936'))
(datetime.date(2025, 10, 7), Decimal('5189.160000'), Decimal('11070472.246733'))
(datetime.date(2025, 10, 8), Decimal('5259.710000'), Decimal('10783920.730193'))
(datetime.date(2025, 10, 9), Decimal('5175.880000'), Decimal('10949945.979090'))
(datetime.date(2025, 10, 10), Decimal('4959.250000'), Decimal('10814774.599012'))
(datetime.date(2025, 10, 14), Decimal('4940.160000'), Decimal('10216224.051871'))
(datetime.date(2025, 10, 15), Decimal('4903.640000'), Decimal('10046351.075826'))
(datetime.date(2025, 10, 16), Decimal('4838.070000'), Decimal('9721344.884649'))
(datetime.date(2025, 10, 17), Decimal('4838.900000'), Decimal('9509774.024195'))
(datetime.date(2025, 10, 20), Decimal('4842.220000'), Decimal('9558930.877185'))
(datetime.date(2025, 10, 21), Decimal('4868.780000'), Decimal('9720308.914971'))
(datetime.date(2025, 10, 22), Decimal('4921.900000'), Decimal('9549158.301143'))
(datetime.date(2025, 10, 23), Decimal('5182.520000'), Decimal('9442499.946296'))
(datetime.date(2025, 10, 24), Decimal('5168.410000'), Decimal('9659976.397608'))
(datetime.date(2025, 10, 27), Decimal('5156.790000'), Decimal('10055171.794297'))
(datetime.date(2025, 10, 28), Decimal('5060.510000'), Decimal('10073474.454011'))
(datetime.date(2025, 10, 29), Decimal('5084.580000'), Decimal('9965129.220872'))
(datetime.date(2025, 10, 30), Decimal('5092.880000'), Decimal('9722166.865440'))
(datetime.date(2025, 10, 31), Decimal('5125.250000'), Decimal('9593893.171045'))
(datetime.date(2025, 11, 3), Decimal('5128.570000'), Decimal('9824421.072228'))
(datetime.date(2025, 11, 4), Decimal('5094.540000'), Decimal('9450928.858755'))
(datetime.date(2025, 11, 5), Decimal('5013.200000'), Decimal('9018317.599499'))
(datetime.date(2025, 11, 6), Decimal('4999.920000'), Decimal('9199126.082981'))
(datetime.date(2025, 11, 7), Decimal('5024.820000'), Decimal('8984607.813502'))
(datetime.date(2025, 11, 10), Decimal('5058.020000'), Decimal('9283589.006016'))
(datetime.date(2025, 11, 12), Decimal('4921.900000'), Decimal('9108594.696794'))
(datetime.date(2025, 11, 13), Decimal('4941.820000'), Decimal('8994239.327086'))
(datetime.date(2025, 11, 14), Decimal('5052.210000'), Decimal('8857694.854444'))
(datetime.date(2025, 11, 17), Decimal('5034.780000'), Decimal('8373085.239388'))
(datetime.date(2025, 11, 18), Decimal('5105.330000'), Decimal('8157780.455111'))
(datetime.date(2025, 11, 19), Decimal('5002.410000'), Decimal('8219844.429071'))
(datetime.date(2025, 11, 20), Decimal('4985.810000'), Decimal('8084502.705830'))
(datetime.date(2025, 11, 21), Decimal('4885.380000'), Decimal('7685198.360480'))
(datetime.date(2025, 11, 24), Decimal('4906.130000'), Decimal('7778520.446851'))
(datetime.date(2025, 11, 25), Decimal('4834.750000'), Decimal('7865475.253834'))
(datetime.date(2025, 11, 26), Decimal('4881.230000'), Decimal('7783791.323602'))
(datetime.date(2025, 11, 28), Decimal('4862.140000'), Decimal('8157156.351484'))
(datetime.date(2025, 12, 1), Decimal('4936.010000'), Decimal('8078246.317718'))
(datetime.date(2025, 12, 2), Decimal('4881.230000'), Decimal('7731939.315083'))
(datetime.date(2025, 12, 3), Decimal('4904.470000'), Decimal('8213485.439947'))
(datetime.date(2025, 12, 4), Decimal('4965.060000'), Decimal('8441734.894690'))
(datetime.date(2025, 12, 5), Decimal('4999.090000'), Decimal('8277612.193785'))
(datetime.date(2025, 12, 8), Decimal('4900.320000'), Decimal('8110183.521497'))
(datetime.date(2025, 12, 9), Decimal('4847.200000'), Decimal('8167418.756507'))
(datetime.date(2025, 12, 10), Decimal('4869.610000'), Decimal('8337407.116606'))
(datetime.date(2025, 12, 11), Decimal('4794.080000'), Decimal('8261440.281356'))
(datetime.date(2025, 12, 12), Decimal('4781.630000'), Decimal('8347818.307928'))
(datetime.date(2025, 12, 15), Decimal('4728.510000'), Decimal('7992348.231966'))
(datetime.date(2025, 12, 16), Decimal('4601.520000'), Decimal('7844409.288927'))
(datetime.date(2025, 12, 17), Decimal('4653.810000'), Decimal('7987315.985985'))
(datetime.date(2025, 12, 18), Decimal('4666.260000'), Decimal('7781471.915537'))
(datetime.date(2025, 12, 19), Decimal('4714.400000'), Decimal('7712879.171309'))
(datetime.date(2025, 12, 22), Decimal('4828.940000'), Decimal('7933999.654740'))
(datetime.date(2025, 12, 23), Decimal('4859.650000'), Decimal('7929162.759663'))
(datetime.date(2025, 12, 24), Decimal('4873.760000'), Decimal('7820620.968822'))
(datetime.date(2025, 12, 26), Decimal('4697.800000'), Decimal('7860175.221035'))
(datetime.date(2025, 12, 29), Decimal('4804.870000'), Decimal('7887770.596681'))
(datetime.date(2025, 12, 30), Decimal('4796.570000'), Decimal('7835388.056690'))
(datetime.date(2025, 12, 31), Decimal('4752.580000'), Decimal('7936951.056509'))
(datetime.date(2026, 1, 2), Decimal('4748.430000'), Decimal('7982611.090932'))
(datetime.date(2026, 1, 5), Decimal('4822.300000'), Decimal('8224912.970330'))
(datetime.date(2026, 1, 6), Decimal('4728.510000'), Decimal('8475311.204337'))
(datetime.date(2026, 1, 7), Decimal('4648.830000'), Decimal('8443838.294347'))
(datetime.date(2026, 1, 8), Decimal('4792.420000'), Decimal('8200790.873529'))
(datetime.date(2026, 1, 9), Decimal('4893.680000'), Decimal('8179932.125614'))
(datetime.date(2026, 1, 12), Decimal('4929.370000'), Decimal('8196362.955223'))
(datetime.date(2026, 1, 13), Decimal('5050.550000'), Decimal('8214254.506812'))
(datetime.date(2026, 1, 14), Decimal('5132.720000'), Decimal('8600260.479528'))
(datetime.date(2026, 1, 15), Decimal('4907.790000'), Decimal('8754772.557780'))
(datetime.date(2026, 1, 16), Decimal('4930.200000'), Decimal('8637202.771129'))
(datetime.date(2026, 1, 20), Decimal('5004.900000'), Decimal('8414003.970645'))
(datetime.date(2026, 1, 21), Decimal('5011.540000'), Decimal('8046939.830277'))
(datetime.date(2026, 1, 22), Decimal('4916.920000'), Decimal('8179241.969295'))
(datetime.date(2026, 1, 23), Decimal('5038.100000'), Decimal('8189307.776815'))
(datetime.date(2026, 1, 26), Decimal('5018.180000'), Decimal('7931480.810441'))
(datetime.date(2026, 1, 27), Decimal('5149.320000'), Decimal('8098992.121061'))
(datetime.date(2026, 1, 28), Decimal('5208.250000'), Decimal('8165356.488930'))
(datetime.date(2026, 1, 29), Decimal('5375.910000'), Decimal('8206661.924142'))
(datetime.date(2026, 1, 30), Decimal('5353.500000'), Decimal('7762053.970031'))
(datetime.date(2026, 2, 2), Decimal('5112.800000'), Decimal('7055170.474775'))
(datetime.date(2026, 2, 3), Decimal('5197.460000'), Decimal('7124353.514367'))
(datetime.date(2026, 2, 4), Decimal('5358.480000'), Decimal('6839512.652076'))
(datetime.date(2026, 2, 5), Decimal('5220.700000'), Decimal('6617843.606631'))
(datetime.date(2026, 2, 6), Decimal('5292.910000'), Decimal('5676634.189757'))
(datetime.date(2026, 2, 9), Decimal('5355.990000'), Decimal('6388983.809905'))
(datetime.date(2026, 2, 10), Decimal('5328.600000'), Decimal('6363124.007123'))
(datetime.date(2026, 2, 11), Decimal('5378.400000'), Decimal('6230645.199778'))
(datetime.date(2026, 2, 12), Decimal('5235.640000'), Decimal('6073656.888034'))
(datetime.date(2026, 2, 13), Decimal('5233.150000'), Decimal('5993963.255323'))
(datetime.date(2026, 2, 17), Decimal('5189.990000'), Decimal('6255749.578602'))
(datetime.date(2026, 2, 18), Decimal('5422.390000'), Decimal('6116329.755578'))
(datetime.date(2026, 2, 19), Decimal('5532.780000'), Decimal('6033801.765391'))
(datetime.date(2026, 2, 20), Decimal('5535.270000'), Decimal('6092367.347486'))
(datetime.date(2026, 2, 23), Decimal('5507.880000'), Decimal('6132044.383909'))
(datetime.date(2026, 2, 24), Decimal('5446.460000'), Decimal('5877904.816486'))
(datetime.date(2026, 2, 25), Decimal('5419.900000'), Decimal('5825506.041088'))
(datetime.date(2026, 2, 26), Decimal('5403.300000'), Decimal('6179906.746479'))
(datetime.date(2026, 2, 27), Decimal('5557.680000'), Decimal('6139221.658943'))
(datetime.date(2026, 3, 2), Decimal('5903.790000'), Decimal('5984275.487394'))
(datetime.date(2026, 3, 3), Decimal('6181.840000'), Decimal('6305544.630558'))
(datetime.date(2026, 3, 4), Decimal('6190.140000'), Decimal('6286193.488373'))
(datetime.date(2026, 3, 5), Decimal('6713.040000'), Decimal('6694568.064726'))
(datetime.date(2026, 3, 6), Decimal('7533.910000'), Decimal('6505413.051213'))
(datetime.date(2026, 3, 9), Decimal('7855.950000'), Decimal('6071162.609842'))
(datetime.date(2026, 3, 10), Decimal('6947.930000'), Decimal('6319544.712080'))
(datetime.date(2026, 3, 11), Decimal('7204.400000'), Decimal('6427459.132594'))
(datetime.date(2026, 3, 12), Decimal('7935.630000'), Decimal('6476952.781588'))
(datetime.date(2026, 3, 13), Decimal('8173.840000'), Decimal('6517601.857024'))
(datetime.date(2026, 3, 16), Decimal('7751.370000'), Decimal('6727548.658016'))
(datetime.date(2026, 3, 17), Decimal('7968.830000'), Decimal('6906940.623961'))
(datetime.date(2026, 3, 18), Decimal('7977.960000'), Decimal('6829860.404015'))
(datetime.date(2026, 3, 19), Decimal('7977.130000'), Decimal('6639390.135900'))
(datetime.date(2026, 3, 20), Decimal('8192.930000'), Decimal('6504037.303026'))
(datetime.date(2026, 3, 23), Decimal('7414.390000'), Decimal('6364717.089252'))
(datetime.date(2026, 3, 24), Decimal('7733.940000'), Decimal('6614293.785504'))
(datetime.date(2026, 3, 25), Decimal('7595.330000'), Decimal('6649392.307316'))
(datetime.date(2026, 3, 26), Decimal('7982.940000'), Decimal('6712173.732416'))
(datetime.date(2026, 3, 27), Decimal('8404.580000'), Decimal('6487672.474785'))
(datetime.date(2026, 3, 30), Decimal('8689.270000'), Decimal('6252812.763420'))
(datetime.date(2026, 3, 31), Decimal('8537.380000'), Decimal('6293233.346703'))
(datetime.date(2026, 4, 1), Decimal('8457.700000'), Decimal('6378628.791276'))
(datetime.date(2026, 4, 2), Decimal('9398.090000'), Decimal('6307964.144412'))
(datetime.date(2026, 4, 6), Decimal('9462.830000'), Decimal('6414170.630917'))

In [14]:
#Compare top 3 coins daily price trend vs Nifty (^NSEI).
cursor.execute("""
SELECT 
    cp.date,
    cp.coin_id,
    cp.price_inr AS crypto_price,
    sp.close AS nifty_price

FROM crypto_prices cp

-- Join with stock data
JOIN stock_prices sp 
ON cp.date = sp.date

-- Filter top 3 coins
WHERE cp.coin_id IN ('bitcoin', 'ethereum', 'tether')

-- Filter Nifty
AND sp.ticker = '^NSEI'

-- Sort for trend
ORDER BY cp.date, cp.coin_id
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2025, 4, 15), 'bitcoin', Decimal('7271599.950977'), Decimal('23328.550781'))
(datetime.date(2025, 4, 15), 'ethereum', Decimal('139502.269181'), Decimal('23328.550781'))
(datetime.date(2025, 4, 15), 'tether', Decimal('86.024832'), Decimal('23328.550781'))
(datetime.date(2025, 4, 16), 'bitcoin', Decimal('7171572.949307'), Decimal('23437.199219'))
(datetime.date(2025, 4, 16), 'ethereum', Decimal('136118.340300'), Decimal('23437.199219'))
(datetime.date(2025, 4, 16), 'tether', Decimal('85.722129'), Decimal('23437.199219'))
(datetime.date(2025, 4, 17), 'bitcoin', Decimal('7201187.297551'), Decimal('23851.650391'))
(datetime.date(2025, 4, 17), 'ethereum', Decimal('135084.250075'), Decimal('23851.650391'))
(datetime.date(2025, 4, 17), 'tether', Decimal('85.620824'), Decimal('23851.650391'))
(datetime.date(2025, 4, 21), 'bitcoin', Decimal('7263849.726469'), Decimal('24125.550781'))
(datetime.date(2025, 4, 21), 'ethereum', Decimal('135372.221202'), Decimal('24125.550781'))
(datetime.date(2025, 4, 21), 'tether', Decimal('85.381519'), Decimal('24125.550781'))
(datetime.date(2025, 4, 22), 'bitcoin', Decimal('7447341.987487'), Decimal('24167.250000'))
(datetime.date(2025, 4, 22), 'ethereum', Decimal('134334.008185'), Decimal('24167.250000'))
(datetime.date(2025, 4, 22), 'tether', Decimal('85.159972'), Decimal('24167.250000'))
(datetime.date(2025, 4, 23), 'bitcoin', Decimal('7975735.892698'), Decimal('24328.949219'))
(datetime.date(2025, 4, 23), 'ethereum', Decimal('149984.444802'), Decimal('24328.949219'))
(datetime.date(2025, 4, 23), 'tether', Decimal('85.269284'), Decimal('24328.949219'))
(datetime.date(2025, 4, 24), 'bitcoin', Decimal('8003280.213214'), Decimal('24246.699219'))
(datetime.date(2025, 4, 24), 'ethereum', Decimal('153384.691226'), Decimal('24246.699219'))
(datetime.date(2025, 4, 24), 'tether', Decimal('85.533091'), Decimal('24246.699219'))
(datetime.date(2025, 4, 25), 'bitcoin', Decimal('8000169.783417'), Decimal('24039.349609'))
(datetime.date(2025, 4, 25), 'ethereum', Decimal('150793.822639'), Decimal('24039.349609'))
(datetime.date(2025, 4, 25), 'tether', Decimal('85.256652'), Decimal('24039.349609'))
(datetime.date(2025, 4, 28), 'bitcoin', Decimal('8009924.381134'), Decimal('24328.500000'))
(datetime.date(2025, 4, 28), 'ethereum', Decimal('153154.647160'), Decimal('24328.500000'))
(datetime.date(2025, 4, 28), 'tether', Decimal('85.413648'), Decimal('24328.500000'))
(datetime.date(2025, 4, 29), 'bitcoin', Decimal('8092853.390806'), Decimal('24335.949219'))
(datetime.date(2025, 4, 29), 'ethereum', Decimal('153246.471992'), Decimal('24335.949219'))
(datetime.date(2025, 4, 29), 'tether', Decimal('85.179249'), Decimal('24335.949219'))
(datetime.date(2025, 4, 30), 'bitcoin', Decimal('8027696.597799'), Decimal('24334.199219'))
(datetime.date(2025, 4, 30), 'ethereum', Decimal('153045.868306'), Decimal('24334.199219'))
(datetime.date(2025, 4, 30), 'tether', Decimal('85.191867'), Decimal('24334.199219'))
(datetime.date(2025, 5, 1), 'bitcoin', Decimal('7968688.759781'), None)
(datetime.date(2025, 5, 1), 'ethereum', Decimal('151706.989211'), None)
(datetime.date(2025, 5, 1), 'tether', Decimal('84.568425'), None)
(datetime.date(2025, 5, 2), 'bitcoin', Decimal('8167058.515488'), Decimal('24346.699219'))
(datetime.date(2025, 5, 2), 'ethereum', Decimal('155745.169241'), Decimal('24346.699219'))
(datetime.date(2025, 5, 2), 'tether', Decimal('84.721437'), Decimal('24346.699219'))
(datetime.date(2025, 5, 5), 'bitcoin', Decimal('7973099.086450'), Decimal('24461.150391'))
(datetime.date(2025, 5, 5), 'ethereum', Decimal('152837.106066'), Decimal('24461.150391'))
(datetime.date(2025, 5, 5), 'tether', Decimal('84.529781'), Decimal('24461.150391'))
(datetime.date(2025, 5, 6), 'bitcoin', Decimal('7980688.008703'), Decimal('24379.599609'))
(datetime.date(2025, 5, 6), 'ethereum', Decimal('153282.693897'), Decimal('24379.599609'))
(datetime.date(2025, 5, 6), 'tether', Decimal('84.214175'), Decimal('24379.599609'))
(datetime.date(2025, 5, 7), 'bitcoin', Decimal('8207545.052482'), Decimal('24414.400391'))
(datetime.date(2025, 5, 7), 'ethereum', Decimal('153903.860522'), Decimal('24414.400391'))
(datetime.date(2025, 5, 7), 'tether', Decimal('84.735990'), Decimal('24414.400391'))
(datetime.date(2025, 5, 8), 'bitcoin', Decimal('8229539.783984'), Decimal('24273.800781'))
(datetime.date(2025, 5, 8), 'ethereum', Decimal('153546.465434'), Decimal('24273.800781'))
(datetime.date(2025, 5, 8), 'tether', Decimal('84.832827'), Decimal('24273.800781'))
(datetime.date(2025, 5, 9), 'bitcoin', Decimal('8868161.595114'), Decimal('24008.000000'))
(datetime.date(2025, 5, 9), 'ethereum', Decimal('189067.053860'), Decimal('24008.000000'))
(datetime.date(2025, 5, 9), 'tether', Decimal('86.029149'), Decimal('24008.000000'))
(datetime.date(2025, 5, 12), 'bitcoin', Decimal('8882429.185762'), Decimal('24924.699219'))
(datetime.date(2025, 5, 12), 'ethereum', Decimal('214170.100120'), Decimal('24924.699219'))
(datetime.date(2025, 5, 12), 'tether', Decimal('85.428990'), Decimal('24924.699219'))
(datetime.date(2025, 5, 13), 'bitcoin', Decimal('8739740.641206'), Decimal('24578.349609'))
(datetime.date(2025, 5, 13), 'ethereum', Decimal('211740.195869'), Decimal('24578.349609'))
(datetime.date(2025, 5, 13), 'tether', Decimal('84.956521'), Decimal('24578.349609'))
(datetime.date(2025, 5, 14), 'bitcoin', Decimal('8860925.913889'), Decimal('24666.900391'))
(datetime.date(2025, 5, 14), 'ethereum', Decimal('227649.060175'), Decimal('24666.900391'))
(datetime.date(2025, 5, 14), 'tether', Decimal('85.061564'), Decimal('24666.900391'))
(datetime.date(2025, 5, 15), 'bitcoin', Decimal('8854656.259617'), Decimal('25062.099609'))
(datetime.date(2025, 5, 15), 'ethereum', Decimal('222550.861260'), Decimal('25062.099609'))
(datetime.date(2025, 5, 15), 'tether', Decimal('85.488237'), Decimal('25062.099609'))
(datetime.date(2025, 5, 16), 'bitcoin', Decimal('8861418.050018'), Decimal('25019.800781'))
(datetime.date(2025, 5, 16), 'ethereum', Decimal('217226.914605'), Decimal('25019.800781'))
(datetime.date(2025, 5, 16), 'tether', Decimal('85.456562'), Decimal('25019.800781'))
(datetime.date(2025, 5, 19), 'bitcoin', Decimal('9065676.354330'), Decimal('24945.449219'))
(datetime.date(2025, 5, 19), 'ethereum', Decimal('210787.975693'), Decimal('24945.449219'))
(datetime.date(2025, 5, 19), 'tether', Decimal('85.527044'), Decimal('24945.449219'))
(datetime.date(2025, 5, 20), 'bitcoin', Decimal('9017978.281234'), Decimal('24683.900391'))
(datetime.date(2025, 5, 20), 'ethereum', Decimal('215738.556840'), Decimal('24683.900391'))
(datetime.date(2025, 5, 20), 'tether', Decimal('85.398174'), Decimal('24683.900391'))
(datetime.date(2025, 5, 21), 'bitcoin', Decimal('9134061.037906'), Decimal('24813.449219'))
(datetime.date(2025, 5, 21), 'ethereum', Decimal('215915.199355'), Decimal('24813.449219'))
(datetime.date(2025, 5, 21), 'tether', Decimal('85.557431'), Decimal('24813.449219'))
(datetime.date(2025, 5, 22), 'bitcoin', Decimal('9387459.456661'), Decimal('24609.699219'))
(datetime.date(2025, 5, 22), 'ethereum', Decimal('219047.575634'), Decimal('24609.699219'))
(datetime.date(2025, 5, 22), 'tether', Decimal('85.631636'), Decimal('24609.699219'))
(datetime.date(2025, 5, 23), 'bitcoin', Decimal('9591418.421810'), Decimal('24853.150391'))
(datetime.date(2025, 5, 23), 'ethereum', Decimal('228450.369638'), Decimal('24853.150391'))
(datetime.date(2025, 5, 23), 'tether', Decimal('85.991152'), Decimal('24853.150391'))
(datetime.date(2025, 5, 26), 'bitcoin', Decimal('9274975.732278'), Decimal('25001.150391'))
(datetime.date(2025, 5, 26), 'ethereum', Decimal('216970.852280'), Decimal('25001.150391'))
(datetime.date(2025, 5, 26), 'tether', Decimal('85.228656'), Decimal('25001.150391'))
(datetime.date(2025, 5, 27), 'bitcoin', Decimal('9314436.685236'), Decimal('24826.199219'))
(datetime.date(2025, 5, 27), 'ethereum', Decimal('218190.675235'), Decimal('24826.199219'))
(datetime.date(2025, 5, 27), 'tether', Decimal('85.180940'), Decimal('24826.199219'))
(datetime.date(2025, 5, 28), 'bitcoin', Decimal('9310175.102672'), Decimal('24752.449219'))
(datetime.date(2025, 5, 28), 'ethereum', Decimal('227238.584850'), Decimal('24752.449219'))
(datetime.date(2025, 5, 28), 'tether', Decimal('85.396693'), Decimal('24752.449219'))
(datetime.date(2025, 5, 29), 'bitcoin', Decimal('9208280.990680'), Decimal('24833.599609'))
(datetime.date(2025, 5, 29), 'ethereum', Decimal('228525.939096'), Decimal('24833.599609'))
(datetime.date(2025, 5, 29), 'tether', Decimal('85.405295'), Decimal('24833.599609'))
(datetime.date(2025, 5, 30), 'bitcoin', Decimal('9026592.666677'), Decimal('24750.699219'))
(datetime.date(2025, 5, 30), 'ethereum', Decimal('224768.844035'), Decimal('24750.699219'))
(datetime.date(2025, 5, 30), 'tether', Decimal('85.357244'), Decimal('24750.699219'))
(datetime.date(2025, 6, 2), 'bitcoin', Decimal('9040802.274014'), Decimal('24716.599609'))
(datetime.date(2025, 6, 2), 'ethereum', Decimal('217089.574074'), Decimal('24716.599609'))
(datetime.date(2025, 6, 2), 'tether', Decimal('85.556353'), Decimal('24716.599609'))
(datetime.date(2025, 6, 3), 'bitcoin', Decimal('9038740.617012'), Decimal('24542.500000'))
(datetime.date(2025, 6, 3), 'ethereum', Decimal('222777.498728'), Decimal('24542.500000'))
(datetime.date(2025, 6, 3), 'tether', Decimal('85.396814'), Decimal('24542.500000'))
(datetime.date(2025, 6, 4), 'bitcoin', Decimal('9036688.899610'), Decimal('24620.199219'))
(datetime.date(2025, 6, 4), 'ethereum', Decimal('222455.178610'), Decimal('24620.199219'))
(datetime.date(2025, 6, 4), 'tether', Decimal('85.756447'), Decimal('24620.199219'))
(datetime.date(2025, 6, 5), 'bitcoin', Decimal('9003749.459209'), Decimal('24750.900391'))
(datetime.date(2025, 6, 5), 'ethereum', Decimal('224236.444163'), Decimal('24750.900391'))
(datetime.date(2025, 6, 5), 'tether', Decimal('85.939135'), Decimal('24750.900391'))
(datetime.date(2025, 6, 6), 'bitcoin', Decimal('8729536.730078'), Decimal('25003.050781'))
(datetime.date(2025, 6, 6), 'ethereum', Decimal('207961.654189'), Decimal('25003.050781'))
(datetime.date(2025, 6, 6), 'tether', Decimal('85.908691'), Decimal('25003.050781'))
(datetime.date(2025, 6, 9), 'bitcoin', Decimal('9066867.468852'), Decimal('25103.199219'))
(datetime.date(2025, 6, 9), 'ethereum', Decimal('215217.423364'), Decimal('25103.199219'))
(datetime.date(2025, 6, 9), 'tether', Decimal('85.815350'), Decimal('25103.199219'))
(datetime.date(2025, 6, 10), 'bitcoin', Decimal('9455619.179044'), Decimal('25104.250000'))
(datetime.date(2025, 6, 10), 'ethereum', Decimal('230255.547118'), Decimal('25104.250000'))
(datetime.date(2025, 6, 10), 'tether', Decimal('85.780845'), Decimal('25104.250000'))
(datetime.date(2025, 6, 11), 'bitcoin', Decimal('9440056.689266'), Decimal('25141.400391'))
(datetime.date(2025, 6, 11), 'ethereum', Decimal('240556.865727'), Decimal('25141.400391'))
(datetime.date(2025, 6, 11), 'tether', Decimal('85.658578'), Decimal('25141.400391'))
(datetime.date(2025, 6, 12), 'bitcoin', Decimal('9288882.881869'), Decimal('24888.199219'))
(datetime.date(2025, 6, 12), 'ethereum', Decimal('237276.581795'), Decimal('24888.199219'))
(datetime.date(2025, 6, 12), 'tether', Decimal('85.482057'), Decimal('24888.199219'))
(datetime.date(2025, 6, 13), 'bitcoin', Decimal('9081227.025134'), Decimal('24718.599609'))
(datetime.date(2025, 6, 13), 'ethereum', Decimal('227345.610242'), Decimal('24718.599609'))
(datetime.date(2025, 6, 13), 'tether', Decimal('85.711863'), Decimal('24718.599609'))
(datetime.date(2025, 6, 16), 'bitcoin', Decimal('9090411.274773'), Decimal('24946.500000'))
(datetime.date(2025, 6, 16), 'ethereum', Decimal('219421.869835'), Decimal('24946.500000'))
(datetime.date(2025, 6, 16), 'tether', Decimal('86.123272'), Decimal('24946.500000'))
(datetime.date(2025, 6, 17), 'bitcoin', Decimal('9208980.453923'), Decimal('24853.400391'))
(datetime.date(2025, 6, 17), 'ethereum', Decimal('220541.897449'), Decimal('24853.400391'))
(datetime.date(2025, 6, 17), 'tether', Decimal('86.136030'), Decimal('24853.400391'))
(datetime.date(2025, 6, 18), 'bitcoin', Decimal('9039952.955659'), Decimal('24812.050781'))
(datetime.date(2025, 6, 18), 'ethereum', Decimal('217182.056291'), Decimal('24812.050781'))
(datetime.date(2025, 6, 18), 'tether', Decimal('86.356991'), Decimal('24812.050781'))
(datetime.date(2025, 6, 19), 'bitcoin', Decimal('9070436.848135'), Decimal('24793.250000'))
(datetime.date(2025, 6, 19), 'ethereum', Decimal('218382.420147'), Decimal('24793.250000'))
(datetime.date(2025, 6, 19), 'tether', Decimal('86.627236'), Decimal('24793.250000'))
(datetime.date(2025, 6, 20), 'bitcoin', Decimal('9080584.318377'), Decimal('25112.400391'))
(datetime.date(2025, 6, 20), 'ethereum', Decimal('218767.013088'), Decimal('25112.400391'))
(datetime.date(2025, 6, 20), 'tether', Decimal('86.742295'), Decimal('25112.400391'))
(datetime.date(2025, 6, 23), 'bitcoin', Decimal('8731873.284684'), Decimal('24971.900391'))
(datetime.date(2025, 6, 23), 'ethereum', Decimal('192852.030967'), Decimal('24971.900391'))
(datetime.date(2025, 6, 23), 'tether', Decimal('86.595800'), Decimal('24971.900391'))
(datetime.date(2025, 6, 24), 'bitcoin', Decimal('9111429.945371'), Decimal('25044.349609'))
(datetime.date(2025, 6, 24), 'ethereum', Decimal('209315.247806'), Decimal('25044.349609'))
(datetime.date(2025, 6, 24), 'tether', Decimal('86.403807'), Decimal('25044.349609'))
(datetime.date(2025, 6, 25), 'bitcoin', Decimal('9111165.386620'), Decimal('25244.750000'))
(datetime.date(2025, 6, 25), 'ethereum', Decimal('210338.280603'), Decimal('25244.750000'))
(datetime.date(2025, 6, 25), 'tether', Decimal('86.009745'), Decimal('25244.750000'))
(datetime.date(2025, 6, 26), 'bitcoin', Decimal('9223086.808659'), Decimal('25549.000000'))
(datetime.date(2025, 6, 26), 'ethereum', Decimal('207894.423633'), Decimal('25549.000000'))
(datetime.date(2025, 6, 26), 'tether', Decimal('86.046758'), Decimal('25549.000000'))
(datetime.date(2025, 6, 27), 'bitcoin', Decimal('9165684.099752'), Decimal('25637.800781'))
(datetime.date(2025, 6, 27), 'ethereum', Decimal('206903.990972'), Decimal('25637.800781'))
(datetime.date(2025, 6, 27), 'tether', Decimal('85.703130'), Decimal('25637.800781'))
(datetime.date(2025, 6, 30), 'bitcoin', Decimal('9263092.465182'), Decimal('25517.050781'))
(datetime.date(2025, 6, 30), 'ethereum', Decimal('213866.808206'), Decimal('25517.050781'))
(datetime.date(2025, 6, 30), 'tether', Decimal('85.466004'), Decimal('25517.050781'))
(datetime.date(2025, 7, 1), 'bitcoin', Decimal('9181709.414668'), Decimal('25541.800781'))
(datetime.date(2025, 7, 1), 'ethereum', Decimal('213247.902754'), Decimal('25541.800781'))
(datetime.date(2025, 7, 1), 'tether', Decimal('85.721851'), Decimal('25541.800781'))
(datetime.date(2025, 7, 2), 'bitcoin', Decimal('9054321.250570'), Decimal('25453.400391'))
(datetime.date(2025, 7, 2), 'ethereum', Decimal('206191.537951'), Decimal('25453.400391'))
(datetime.date(2025, 7, 2), 'tether', Decimal('85.737897'), Decimal('25453.400391'))
(datetime.date(2025, 7, 3), 'bitcoin', Decimal('9325640.339018'), Decimal('25405.300781'))
(datetime.date(2025, 7, 3), 'ethereum', Decimal('220583.067715'), Decimal('25405.300781'))
(datetime.date(2025, 7, 3), 'tether', Decimal('85.722605'), Decimal('25405.300781'))
(datetime.date(2025, 7, 4), 'bitcoin', Decimal('9360532.463405'), Decimal('25461.000000'))
(datetime.date(2025, 7, 4), 'ethereum', Decimal('221209.207186'), Decimal('25461.000000'))
(datetime.date(2025, 7, 4), 'tether', Decimal('85.426201'), Decimal('25461.000000'))
(datetime.date(2025, 7, 7), 'bitcoin', Decimal('9337523.923074'), Decimal('25461.300781'))
(datetime.date(2025, 7, 7), 'ethereum', Decimal('219842.285096'), Decimal('25461.300781'))
(datetime.date(2025, 7, 7), 'tether', Decimal('85.500803'), Decimal('25461.300781'))
(datetime.date(2025, 7, 8), 'bitcoin', Decimal('9302203.177317'), Decimal('25522.500000'))
(datetime.date(2025, 7, 8), 'ethereum', Decimal('218478.507032'), Decimal('25522.500000'))
(datetime.date(2025, 7, 8), 'tether', Decimal('85.893151'), Decimal('25522.500000'))
(datetime.date(2025, 7, 9), 'bitcoin', Decimal('9338122.035801'), Decimal('25476.099609'))
(datetime.date(2025, 7, 9), 'ethereum', Decimal('224192.012935'), Decimal('25476.099609'))
(datetime.date(2025, 7, 9), 'tether', Decimal('85.717453'), Decimal('25476.099609'))
(datetime.date(2025, 7, 10), 'bitcoin', Decimal('9541743.483381'), Decimal('25355.250000'))
(datetime.date(2025, 7, 10), 'ethereum', Decimal('237634.328591'), Decimal('25355.250000'))
(datetime.date(2025, 7, 10), 'tether', Decimal('85.729639'), Decimal('25355.250000'))
(datetime.date(2025, 7, 11), 'bitcoin', Decimal('9934947.612549'), Decimal('25149.849609'))
(datetime.date(2025, 7, 11), 'ethereum', Decimal('252785.182611'), Decimal('25149.849609'))
(datetime.date(2025, 7, 11), 'tether', Decimal('85.736795'), Decimal('25149.849609'))
(datetime.date(2025, 7, 14), 'bitcoin', Decimal('10222853.345055'), Decimal('25082.300781'))
(datetime.date(2025, 7, 14), 'ethereum', Decimal('255256.074912'), Decimal('25082.300781'))
(datetime.date(2025, 7, 14), 'tether', Decimal('85.847134'), Decimal('25082.300781'))
(datetime.date(2025, 7, 15), 'bitcoin', Decimal('10301939.218478'), Decimal('25195.800781'))
(datetime.date(2025, 7, 15), 'ethereum', Decimal('258953.022960'), Decimal('25195.800781'))
(datetime.date(2025, 7, 15), 'tether', Decimal('85.978884'), Decimal('25195.800781'))
(datetime.date(2025, 7, 16), 'bitcoin', Decimal('10119542.204331'), Decimal('25212.050781'))
(datetime.date(2025, 7, 16), 'ethereum', Decimal('269423.172852'), Decimal('25212.050781'))
(datetime.date(2025, 7, 16), 'tether', Decimal('85.996140'), Decimal('25212.050781'))
(datetime.date(2025, 7, 17), 'bitcoin', Decimal('10198739.393321'), Decimal('25111.449219'))
(datetime.date(2025, 7, 17), 'ethereum', Decimal('289273.061958'), Decimal('25111.449219'))
(datetime.date(2025, 7, 17), 'tether', Decimal('85.920924'), Decimal('25111.449219'))
(datetime.date(2025, 7, 18), 'bitcoin', Decimal('10277885.478397'), Decimal('24968.400391'))
(datetime.date(2025, 7, 18), 'ethereum', Decimal('299604.700132'), Decimal('24968.400391'))
(datetime.date(2025, 7, 18), 'tether', Decimal('86.097935'), Decimal('24968.400391'))
(datetime.date(2025, 7, 21), 'bitcoin', Decimal('10101549.352407'), Decimal('25090.699219'))
(datetime.date(2025, 7, 21), 'ethereum', Decimal('323799.563511'), Decimal('25090.699219'))
(datetime.date(2025, 7, 21), 'tether', Decimal('86.183167'), Decimal('25090.699219'))
(datetime.date(2025, 7, 22), 'bitcoin', Decimal('10136533.758092'), Decimal('25060.900391'))
(datetime.date(2025, 7, 22), 'ethereum', Decimal('324888.026671'), Decimal('25060.900391'))
(datetime.date(2025, 7, 22), 'tether', Decimal('86.309316'), Decimal('25060.900391'))
(datetime.date(2025, 7, 23), 'bitcoin', Decimal('10357349.266440'), Decimal('25219.900391'))
(datetime.date(2025, 7, 23), 'ethereum', Decimal('323522.285507'), Decimal('25219.900391'))
(datetime.date(2025, 7, 23), 'tether', Decimal('86.374857'), Decimal('25219.900391'))
(datetime.date(2025, 7, 24), 'bitcoin', Decimal('10249425.749007'), Decimal('25062.099609'))
(datetime.date(2025, 7, 24), 'ethereum', Decimal('313632.809934'), Decimal('25062.099609'))
(datetime.date(2025, 7, 24), 'tether', Decimal('86.430622'), Decimal('25062.099609'))
(datetime.date(2025, 7, 25), 'bitcoin', Decimal('10229427.683390'), Decimal('24837.000000'))
(datetime.date(2025, 7, 25), 'ethereum', Decimal('320521.286638'), Decimal('24837.000000'))
(datetime.date(2025, 7, 25), 'tether', Decimal('86.465494'), Decimal('24837.000000'))
(datetime.date(2025, 7, 28), 'bitcoin', Decimal('10330494.375552'), Decimal('24680.900391'))
(datetime.date(2025, 7, 28), 'ethereum', Decimal('334271.335633'), Decimal('24680.900391'))
(datetime.date(2025, 7, 28), 'tether', Decimal('86.527895'), Decimal('24680.900391'))
(datetime.date(2025, 7, 29), 'bitcoin', Decimal('10240072.841856'), Decimal('24821.099609'))

In [15]:
#Compare stock prices (^GSPC) with crude oil prices on the same dates
cursor.execute("""
SELECT 
    sp.date,
    sp.close AS sp500_price,
    op.price_inr AS oil_price

FROM stock_prices sp

-- Join oil data using same date
JOIN oil_prices op 
ON sp.date = op.date

-- Filter S&P 500
WHERE sp.ticker = '^GSPC'

-- Sort for trend
ORDER BY sp.date
""")

for row in cursor.fetchall():
    print(row)

(datetime.date(2020, 1, 2), Decimal('3257.850098'), Decimal('5077.110000'))
(datetime.date(2020, 1, 3), Decimal('3234.850098'), Decimal('5229.000000'))
(datetime.date(2020, 1, 6), Decimal('3246.280029'), Decimal('5251.410000'))
(datetime.date(2020, 1, 7), Decimal('3237.179932'), Decimal('5204.100000'))
(datetime.date(2020, 1, 8), Decimal('3253.050049'), Decimal('4950.950000'))
(datetime.date(2020, 1, 9), Decimal('3274.699951'), Decimal('4943.480000'))
(datetime.date(2020, 1, 10), Decimal('3265.350098'), Decimal('4898.660000'))
(datetime.date(2020, 1, 13), Decimal('3288.129883'), Decimal('4828.110000'))
(datetime.date(2020, 1, 14), Decimal('3283.149902'), Decimal('4842.220000'))
(datetime.date(2020, 1, 15), Decimal('3289.290039'), Decimal('4802.380000'))
(datetime.date(2020, 1, 16), Decimal('3316.810059'), Decimal('4857.160000'))
(datetime.date(2020, 1, 17), Decimal('3329.620117'), Decimal('4859.650000'))
(datetime.date(2020, 1, 21), Decimal('3320.790039'), Decimal('4834.750000'))
(datetime.date(2020, 1, 22), Decimal('3321.750000'), Decimal('4711.080000'))
(datetime.date(2020, 1, 23), Decimal('3325.540039'), Decimal('4607.330000'))
(datetime.date(2020, 1, 24), Decimal('3295.469971'), Decimal('4489.470000'))
(datetime.date(2020, 1, 27), Decimal('3243.629883'), Decimal('4406.470000'))
(datetime.date(2020, 1, 28), Decimal('3276.239990'), Decimal('4426.390000'))
(datetime.date(2020, 1, 29), Decimal('3273.399902'), Decimal('4423.070000'))
(datetime.date(2020, 1, 30), Decimal('3283.659912'), Decimal('4331.770000'))
(datetime.date(2020, 1, 31), Decimal('3225.520020'), Decimal('4281.140000'))
(datetime.date(2020, 2, 3), Decimal('3248.919922'), Decimal('4154.980000'))
(datetime.date(2020, 2, 4), Decimal('3297.590088'), Decimal('4115.970000'))
(datetime.date(2020, 2, 5), Decimal('3334.689941'), Decimal('4222.210000'))
(datetime.date(2020, 2, 6), Decimal('3345.780029'), Decimal('4228.020000'))
(datetime.date(2020, 2, 7), Decimal('3327.709961'), Decimal('4178.220000'))
(datetime.date(2020, 2, 10), Decimal('3352.090088'), Decimal('4115.970000'))
(datetime.date(2020, 2, 11), Decimal('3357.750000'), Decimal('4150.000000'))
(datetime.date(2020, 2, 12), Decimal('3379.449951'), Decimal('4243.790000'))
(datetime.date(2020, 2, 13), Decimal('3373.939941'), Decimal('4267.030000'))
(datetime.date(2020, 2, 14), Decimal('3380.159912'), Decimal('4318.490000'))
(datetime.date(2020, 2, 18), Decimal('3370.290039'), Decimal('4324.300000'))
(datetime.date(2020, 2, 19), Decimal('3386.149902'), Decimal('4424.730000'))
(datetime.date(2020, 2, 20), Decimal('3373.229980'), Decimal('4462.910000'))
(datetime.date(2020, 2, 21), Decimal('3337.750000'), Decimal('4428.880000'))
(datetime.date(2020, 2, 24), Decimal('3225.889893'), Decimal('4262.880000'))
(datetime.date(2020, 2, 25), Decimal('3128.209961'), Decimal('4131.740000'))
(datetime.date(2020, 2, 26), Decimal('3116.389893'), Decimal('4039.610000'))
(datetime.date(2020, 2, 27), Decimal('2978.760010'), Decimal('3915.110000'))
(datetime.date(2020, 2, 28), Decimal('2954.219971'), Decimal('3720.890000'))
(datetime.date(2020, 3, 2), Decimal('3090.229980'), Decimal('3882.740000'))
(datetime.date(2020, 3, 3), Decimal('3003.370117'), Decimal('3923.410000'))
(datetime.date(2020, 3, 4), Decimal('3130.120117'), Decimal('3882.740000'))
(datetime.date(2020, 3, 5), Decimal('3023.939941'), Decimal('3809.700000'))
(datetime.date(2020, 3, 6), Decimal('2972.370117'), Decimal('3414.620000'))
(datetime.date(2020, 3, 9), Decimal('2746.560059'), Decimal('2577.150000'))
(datetime.date(2020, 3, 10), Decimal('2882.229980'), Decimal('2861.010000'))
(datetime.date(2020, 3, 11), Decimal('2741.379883'), Decimal('2749.790000'))
(datetime.date(2020, 3, 12), Decimal('2480.639893'), Decimal('2619.480000'))
(datetime.date(2020, 3, 13), Decimal('2711.020020'), Decimal('2632.760000'))
(datetime.date(2020, 3, 16), Decimal('2386.129883'), Decimal('2403.680000'))
(datetime.date(2020, 3, 17), Decimal('2529.189941'), Decimal('2237.680000'))
(datetime.date(2020, 3, 18), Decimal('2398.100098'), Decimal('1699.840000'))
(datetime.date(2020, 3, 19), Decimal('2409.389893'), Decimal('2082.470000'))
(datetime.date(2020, 3, 20), Decimal('2304.919922'), Decimal('1616.840000'))
(datetime.date(2020, 3, 23), Decimal('2237.399902'), Decimal('1936.390000'))
(datetime.date(2020, 3, 24), Decimal('2447.330078'), Decimal('1745.490000'))
(datetime.date(2020, 3, 25), Decimal('2475.560059'), Decimal('1722.250000'))
(datetime.date(2020, 3, 26), Decimal('2630.070068'), Decimal('1377.800000'))
(datetime.date(2020, 3, 27), Decimal('2541.469971'), Decimal('1284.840000'))
(datetime.date(2020, 3, 30), Decimal('2626.649902'), Decimal('1170.300000'))
(datetime.date(2020, 3, 31), Decimal('2584.590088'), Decimal('1702.330000'))
(datetime.date(2020, 4, 1), Decimal('2470.500000'), Decimal('1683.240000'))
(datetime.date(2020, 4, 2), Decimal('2526.899902'), Decimal('2089.940000'))
(datetime.date(2020, 4, 3), Decimal('2488.649902'), Decimal('2353.880000'))
(datetime.date(2020, 4, 6), Decimal('2663.679932'), Decimal('2175.430000'))
(datetime.date(2020, 4, 7), Decimal('2659.409912'), Decimal('1953.820000'))
(datetime.date(2020, 4, 8), Decimal('2749.979980'), Decimal('2072.510000'))
(datetime.date(2020, 4, 9), Decimal('2789.820068'), Decimal('1900.700000'))
(datetime.date(2020, 4, 13), Decimal('2761.629883'), Decimal('1855.880000'))
(datetime.date(2020, 4, 14), Decimal('2846.060059'), Decimal('1672.450000'))
(datetime.date(2020, 4, 15), Decimal('2783.360107'), Decimal('1656.680000'))
(datetime.date(2020, 4, 16), Decimal('2799.550049'), Decimal('1645.060000'))
(datetime.date(2020, 4, 17), Decimal('2874.560059'), Decimal('1519.730000'))
(datetime.date(2020, 4, 20), Decimal('2823.159912'), Decimal('-3069.340000'))
(datetime.date(2020, 4, 21), Decimal('2736.560059'), Decimal('739.530000'))
(datetime.date(2020, 4, 22), Decimal('2799.310059'), Decimal('1132.120000'))
(datetime.date(2020, 4, 23), Decimal('2797.800049'), Decimal('1249.980000'))
(datetime.date(2020, 4, 24), Decimal('2836.739990'), Decimal('1327.170000'))
(datetime.date(2020, 4, 27), Decimal('2878.479980'), Decimal('1010.110000'))
(datetime.date(2020, 4, 28), Decimal('2863.389893'), Decimal('1029.200000'))
(datetime.date(2020, 4, 29), Decimal('2939.510010'), Decimal('1248.320000'))
(datetime.date(2020, 4, 30), Decimal('2912.429932'), Decimal('1596.090000'))
(datetime.date(2020, 5, 1), Decimal('2830.709961'), Decimal('1636.760000'))
(datetime.date(2020, 5, 4), Decimal('2842.739990'), Decimal('1699.010000'))
(datetime.date(2020, 5, 5), Decimal('2868.439941'), Decimal('2038.480000'))
(datetime.date(2020, 5, 6), Decimal('2848.419922'), Decimal('1982.040000'))
(datetime.date(2020, 5, 7), Decimal('2881.189941'), Decimal('1965.440000'))
(datetime.date(2020, 5, 8), Decimal('2929.800049'), Decimal('2052.590000'))
(datetime.date(2020, 5, 11), Decimal('2930.189941'), Decimal('1993.660000'))
(datetime.date(2020, 5, 12), Decimal('2870.120117'), Decimal('2138.080000'))
(datetime.date(2020, 5, 13), Decimal('2820.000000'), Decimal('2105.710000'))
(datetime.date(2020, 5, 14), Decimal('2852.500000'), Decimal('2274.200000'))
(datetime.date(2020, 5, 15), Decimal('2863.699951'), Decimal('2443.520000'))
(datetime.date(2020, 5, 18), Decimal('2953.909912'), Decimal('2641.890000'))
(datetime.date(2020, 5, 19), Decimal('2922.939941'), Decimal('2680.900000'))
(datetime.date(2020, 5, 20), Decimal('2971.610107'), Decimal('2785.480000'))
(datetime.date(2020, 5, 21), Decimal('2948.510010'), Decimal('2846.900000'))
(datetime.date(2020, 5, 22), Decimal('2955.449951'), Decimal('2779.670000'))
(datetime.date(2020, 5, 26), Decimal('2991.770020'), Decimal('2880.100000'))
(datetime.date(2020, 5, 27), Decimal('3036.129883'), Decimal('2722.400000'))
(datetime.date(2020, 5, 28), Decimal('3029.729980'), Decimal('2794.610000'))
(datetime.date(2020, 5, 29), Decimal('3044.310059'), Decimal('2952.310000'))
(datetime.date(2020, 6, 1), Decimal('3055.729980'), Decimal('2945.670000'))
(datetime.date(2020, 6, 2), Decimal('3080.820068'), Decimal('3061.040000'))
(datetime.date(2020, 6, 3), Decimal('3122.870117'), Decimal('3098.390000'))
(datetime.date(2020, 6, 4), Decimal('3112.350098'), Decimal('3105.860000'))
(datetime.date(2020, 6, 5), Decimal('3193.929932'), Decimal('3277.670000'))
(datetime.date(2020, 6, 8), Decimal('3232.389893'), Decimal('3168.110000'))
(datetime.date(2020, 6, 9), Decimal('3207.179932'), Decimal('3235.340000'))
(datetime.date(2020, 6, 10), Decimal('3190.139893'), Decimal('3281.820000'))
(datetime.date(2020, 6, 11), Decimal('3002.100098'), Decimal('3023.690000'))
(datetime.date(2020, 6, 12), Decimal('3041.310059'), Decimal('3007.920000'))
(datetime.date(2020, 6, 15), Decimal('3066.590088'), Decimal('3076.810000'))
(datetime.date(2020, 6, 16), Decimal('3124.739990'), Decimal('3175.580000'))
(datetime.date(2020, 6, 17), Decimal('3113.489990'), Decimal('3146.530000'))
(datetime.date(2020, 6, 18), Decimal('3115.340088'), Decimal('3219.570000'))
(datetime.date(2020, 6, 19), Decimal('3097.739990'), Decimal('3296.760000'))
(datetime.date(2020, 6, 22), Decimal('3117.860107'), Decimal('3369.800000'))
(datetime.date(2020, 6, 23), Decimal('3131.290039'), Decimal('3353.200000'))
(datetime.date(2020, 6, 24), Decimal('3050.330078'), Decimal('3146.530000'))
(datetime.date(2020, 6, 25), Decimal('3083.760010'), Decimal('3208.780000'))
(datetime.date(2020, 6, 26), Decimal('3009.050049'), Decimal('3197.990000'))
(datetime.date(2020, 6, 29), Decimal('3053.239990'), Decimal('3292.610000'))
(datetime.date(2020, 6, 30), Decimal('3100.290039'), Decimal('3259.410000'))
(datetime.date(2020, 7, 1), Decimal('3115.860107'), Decimal('3310.040000'))
(datetime.date(2020, 7, 2), Decimal('3130.010010'), Decimal('3367.310000'))
(datetime.date(2020, 7, 6), Decimal('3179.719971'), Decimal('3362.330000'))
(datetime.date(2020, 7, 7), Decimal('3145.320068'), Decimal('3368.970000'))
(datetime.date(2020, 7, 8), Decimal('3169.939941'), Decimal('3395.530000'))
(datetime.date(2020, 7, 9), Decimal('3152.050049'), Decimal('3290.120000'))
(datetime.date(2020, 7, 10), Decimal('3185.040039'), Decimal('3366.480000'))
(datetime.date(2020, 7, 13), Decimal('3155.219971'), Decimal('3324.980000'))
(datetime.date(2020, 7, 14), Decimal('3197.520020'), Decimal('3344.900000'))
(datetime.date(2020, 7, 15), Decimal('3226.560059'), Decimal('3419.600000'))
(datetime.date(2020, 7, 16), Decimal('3215.570068'), Decimal('3381.420000'))
(datetime.date(2020, 7, 17), Decimal('3224.729980'), Decimal('3365.650000'))
(datetime.date(2020, 7, 20), Decimal('3251.840088'), Decimal('3388.890000'))
(datetime.date(2020, 7, 21), Decimal('3257.300049'), Decimal('3466.080000'))
(datetime.date(2020, 7, 22), Decimal('3276.020020'), Decimal('3476.040000'))
(datetime.date(2020, 7, 23), Decimal('3235.659912'), Decimal('3402.170000'))
(datetime.date(2020, 7, 24), Decimal('3215.629883'), Decimal('3422.090000'))
(datetime.date(2020, 7, 27), Decimal('3239.409912'), Decimal('3441.180000'))
(datetime.date(2020, 7, 28), Decimal('3218.439941'), Decimal('3393.870000'))
(datetime.date(2020, 7, 29), Decimal('3258.439941'), Decimal('3413.790000'))
(datetime.date(2020, 7, 30), Decimal('3246.219971'), Decimal('3307.550000'))
(datetime.date(2020, 7, 31), Decimal('3271.120117'), Decimal('3328.300000'))
(datetime.date(2020, 8, 3), Decimal('3294.610107'), Decimal('3388.890000'))
(datetime.date(2020, 8, 4), Decimal('3306.510010'), Decimal('3458.610000'))
(datetime.date(2020, 8, 5), Decimal('3327.770020'), Decimal('3506.750000'))
(datetime.date(2020, 8, 6), Decimal('3349.159912'), Decimal('3480.190000'))
(datetime.date(2020, 8, 7), Decimal('3351.280029'), Decimal('3416.280000'))
(datetime.date(2020, 8, 10), Decimal('3360.469971'), Decimal('3481.020000'))
(datetime.date(2020, 8, 11), Decimal('3333.689941'), Decimal('3446.990000'))
(datetime.date(2020, 8, 12), Decimal('3380.350098'), Decimal('3535.800000'))
(datetime.date(2020, 8, 13), Decimal('3373.429932'), Decimal('3507.580000'))
(datetime.date(2020, 8, 14), Decimal('3372.850098'), Decimal('3490.150000'))
(datetime.date(2020, 8, 17), Decimal('3381.989990'), Decimal('3559.870000'))
(datetime.date(2020, 8, 18), Decimal('3389.780029'), Decimal('3559.870000'))
(datetime.date(2020, 8, 19), Decimal('3374.850098'), Decimal('3561.530000'))
(datetime.date(2020, 8, 20), Decimal('3385.510010'), Decimal('3537.460000'))
(datetime.date(2020, 8, 21), Decimal('3397.159912'), Decimal('3512.560000'))
(datetime.date(2020, 8, 24), Decimal('3431.280029'), Decimal('3522.520000'))
(datetime.date(2020, 8, 25), Decimal('3443.620117'), Decimal('3583.110000'))
(datetime.date(2020, 8, 26), Decimal('3478.729980'), Decimal('3586.430000'))
(datetime.date(2020, 8, 27), Decimal('3484.550049'), Decimal('3559.040000'))
(datetime.date(2020, 8, 28), Decimal('3508.010010'), Decimal('3565.680000'))
(datetime.date(2020, 8, 31), Decimal('3500.310059'), Decimal('3536.630000'))
(datetime.date(2020, 9, 1), Decimal('3526.649902'), Decimal('3549.080000'))
(datetime.date(2020, 9, 2), Decimal('3580.840088'), Decimal('3549.080000'))
(datetime.date(2020, 9, 3), Decimal('3455.060059'), Decimal('3435.370000'))
(datetime.date(2020, 9, 4), Decimal('3426.959961'), Decimal('3294.270000'))
(datetime.date(2020, 9, 8), Decimal('3331.840088'), Decimal('3060.210000'))
(datetime.date(2020, 9, 9), Decimal('3398.959961'), Decimal('3158.150000'))
(datetime.date(2020, 9, 10), Decimal('3339.189941'), Decimal('3091.750000'))
(datetime.date(2020, 9, 11), Decimal('3340.969971'), Decimal('3098.390000'))
(datetime.date(2020, 9, 14), Decimal('3383.540039'), Decimal('3090.090000'))
(datetime.date(2020, 9, 15), Decimal('3401.199951'), Decimal('3178.070000'))
(datetime.date(2020, 9, 16), Decimal('3385.489990'), Decimal('3334.110000'))
(datetime.date(2020, 9, 17), Decimal('3357.010010'), Decimal('3402.170000'))
(datetime.date(2020, 9, 18), Decimal('3319.469971'), Decimal('3410.470000'))
(datetime.date(2020, 9, 21), Decimal('3281.060059'), Decimal('3258.580000'))
(datetime.date(2020, 9, 22), Decimal('3315.570068'), Decimal('3282.650000'))
(datetime.date(2020, 9, 23), Decimal('3236.919922'), Decimal('3313.360000'))
(datetime.date(2020, 9, 24), Decimal('3246.590088'), Decimal('3329.130000'))
(datetime.date(2020, 9, 25), Decimal('3298.459961'), Decimal('3324.980000'))
(datetime.date(2020, 9, 28), Decimal('3351.600098'), Decimal('3359.010000'))
(datetime.date(2020, 9, 29), Decimal('3335.469971'), Decimal('3239.490000'))
(datetime.date(2020, 9, 30), Decimal('3363.000000'), Decimal('3324.150000'))
(datetime.date(2020, 10, 1), Decimal('3380.800049'), Decimal('3196.330000'))
(datetime.date(2020, 10, 2), Decimal('3348.419922'), Decimal('3062.700000'))
(datetime.date(2020, 10, 5), Decimal('3408.600098'), Decimal('3246.960000'))
(datetime.date(2020, 10, 6), Decimal('3360.969971'), Decimal('3363.160000'))
(datetime.date(2020, 10, 7), Decimal('3419.439941'), Decimal('3305.060000'))
(datetime.date(2020, 10, 8), Decimal('3446.830078'), Decimal('3406.320000'))
(datetime.date(2020, 10, 9), Decimal('3477.139893'), Decimal('3356.520000'))
(datetime.date(2020, 10, 12), Decimal('3534.219971'), Decimal('3255.260000'))
(datetime.date(2020, 10, 13), Decimal('3511.929932'), Decimal('3322.490000'))
(datetime.date(2020, 10, 14), Decimal('3488.669922'), Decimal('3391.380000'))
(datetime.date(2020, 10, 15), Decimal('3483.340088'), Decimal('3389.720000'))
(datetime.date(2020, 10, 16), Decimal('3483.810059'), Decimal('3378.100000'))
(datetime.date(2020, 10, 19), Decimal('3426.919922'), Decimal('3377.270000'))
(datetime.date(2020, 10, 20), Decimal('3443.120117'), Decimal('3433.710000'))
(datetime.date(2020, 10, 21), Decimal('3435.560059'), Decimal('3310.040000'))
(datetime.date(2020, 10, 22), Decimal('3453.489990'), Decimal('3358.180000'))
(datetime.date(2020, 10, 23), Decimal('3465.389893'), Decimal('3297.590000'))
(datetime.date(2020, 10, 26), Decimal('3400.969971'), Decimal('3186.370000'))
(datetime.date(2020, 10, 27), Decimal('3390.679932'), Decimal('3265.220000'))
(datetime.date(2020, 10, 28), Decimal('3271.030029'), Decimal('3093.410000'))
(datetime.date(2020, 10, 29), Decimal('3310.110107'), Decimal('2983.020000'))
(datetime.date(2020, 10, 30), Decimal('3269.959961'), Decimal('2958.120000'))
(datetime.date(2020, 11, 2), Decimal('3310.239990'), Decimal('3037.800000'))
(datetime.date(2020, 11, 3), Decimal('3369.159912'), Decimal('3107.520000'))
(datetime.date(2020, 11, 4), Decimal('3443.439941'), Decimal('3234.510000'))
(datetime.date(2020, 11, 5), Decimal('3510.449951'), Decimal('3200.480000'))
(datetime.date(2020, 11, 6), Decimal('3509.439941'), Decimal('3068.510000'))
(datetime.date(2020, 11, 9), Decimal('3550.500000'), Decimal('3324.150000'))
(datetime.date(2020, 11, 10), Decimal('3545.530029'), Decimal('3417.940000'))
(datetime.date(2020, 11, 11), Decimal('3572.659912'), Decimal('3422.090000'))
(datetime.date(2020, 11, 12), Decimal('3537.010010'), Decimal('3394.700000'))
(datetime.date(2020, 11, 13), Decimal('3585.149902'), Decimal('3314.190000'))
(datetime.date(2020, 11, 16), Decimal('3626.909912'), Decimal('3414.620000'))
(datetime.date(2020, 11, 17), Decimal('3609.530029'), Decimal('3422.920000'))
(datetime.date(2020, 11, 18), Decimal('3567.790039'), Decimal('3456.120000'))
(datetime.date(2020, 11, 19), Decimal('3581.870117'), Decimal('3450.310000'))
(datetime.date(2020, 11, 20), Decimal('3557.540039'), Decimal('3485.170000'))
(datetime.date(2020, 11, 23), Decimal('3577.590088'), Decimal('3561.530000'))
(datetime.date(2020, 11, 24), Decimal('3635.409912'), Decimal('3710.930000'))
(datetime.date(2020, 11, 25), Decimal('3629.649902'), Decimal('3783.140000'))
(datetime.date(2020, 11, 30), Decimal('3621.629883'), Decimal('3751.600000'))
(datetime.date(2020, 12, 1), Decimal('3662.449951'), Decimal('3696.820000'))
(datetime.date(2020, 12, 2), Decimal('3669.010010'), Decimal('3754.090000'))
(datetime.date(2020, 12, 3), Decimal('3666.719971'), Decimal('3788.950000'))
(datetime.date(2020, 12, 4), Decimal('3699.120117'), Decimal('3837.090000'))
(datetime.date(2020, 12, 7), Decimal('3691.959961'), Decimal('3794.760000'))
(datetime.date(2020, 12, 8), Decimal('3702.250000'), Decimal('3788.120000'))
(datetime.date(2020, 12, 9), Decimal('3672.820068'), Decimal('3774.840000'))
(datetime.date(2020, 12, 10), Decimal('3668.100098'), Decimal('3881.080000'))
(datetime.date(2020, 12, 11), Decimal('3663.459961'), Decimal('3866.970000'))
(datetime.date(2020, 12, 14), Decimal('3647.489990'), Decimal('3902.660000'))
(datetime.date(2020, 12, 15), Decimal('3694.620117'), Decimal('3949.140000'))
(datetime.date(2020, 12, 16), Decimal('3701.169922'), Decimal('3972.380000'))
(datetime.date(2020, 12, 17), Decimal('3722.479980'), Decimal('4012.220000'))
(datetime.date(2020, 12, 18), Decimal('3709.409912'), Decimal('4070.320000'))
(datetime.date(2020, 12, 21), Decimal('3694.919922'), Decimal('3966.570000'))
(datetime.date(2020, 12, 22), Decimal('3687.260010'), Decimal('3902.660000'))
(datetime.date(2020, 12, 23), Decimal('3690.010010'), Decimal('3979.020000'))
(datetime.date(2020, 12, 24), Decimal('3703.060059'), Decimal('3998.940000'))
(datetime.date(2020, 12, 28), Decimal('3735.360107'), Decimal('3942.500000'))
(datetime.date(2020, 12, 29), Decimal('3727.040039'), Decimal('3971.550000'))
(datetime.date(2020, 12, 30), Decimal('3732.040039'), Decimal('4003.920000'))
(datetime.date(2020, 12, 31), Decimal('3756.070068'), Decimal('4013.050000'))
(datetime.date(2021, 1, 4), Decimal('3700.649902'), Decimal('3940.010000'))
(datetime.date(2021, 1, 5), Decimal('3726.860107'), Decimal('4131.740000'))
(datetime.date(2021, 1, 6), Decimal('3748.139893'), Decimal('4187.350000'))
(datetime.date(2021, 1, 7), Decimal('3803.790039'), Decimal('4202.290000'))
(datetime.date(2021, 1, 8), Decimal('3824.679932'), Decimal('4327.620000'))
(datetime.date(2021, 1, 11), Decimal('3799.610107'), Decimal('4328.450000'))
(datetime.date(2021, 1, 12), Decimal('3801.189941'), Decimal('4405.640000'))

In [16]:
#Correlate Bitcoin closing price with crude oil closing price (same date)
cursor.execute("""
SELECT 
    cp.date,
    cp.price_inr AS bitcoin_price,
    op.price_inr AS oil_price

FROM crypto_prices cp

-- Join oil data using same date
JOIN oil_prices op 
ON cp.date = op.date

WHERE cp.coin_id = 'bitcoin'

ORDER BY cp.date
""")

data = cursor.fetchall()

for row in data:
    print(row)

(datetime.date(2025, 4, 15), Decimal('7271599.950977'), Decimal('5124.420000'))
(datetime.date(2025, 4, 16), Decimal('7171572.949307'), Decimal('5219.040000'))
(datetime.date(2025, 4, 17), Decimal('7201187.297551'), Decimal('5400.810000'))
(datetime.date(2025, 4, 21), Decimal('7263849.726469'), Decimal('5268.840000'))
(datetime.date(2025, 4, 22), Decimal('7447341.987487'), Decimal('5361.800000'))
(datetime.date(2025, 4, 23), Decimal('7975735.892698'), Decimal('5199.120000'))
(datetime.date(2025, 4, 24), Decimal('8003280.213214'), Decimal('5274.650000'))
(datetime.date(2025, 4, 25), Decimal('8000169.783417'), Decimal('5299.550000'))
(datetime.date(2025, 4, 28), Decimal('8009924.381134'), Decimal('5253.900000'))
(datetime.date(2025, 4, 29), Decimal('8092853.390806'), Decimal('5132.720000'))
(datetime.date(2025, 4, 30), Decimal('8027696.597799'), Decimal('4942.650000'))
(datetime.date(2025, 5, 1), Decimal('7968688.759781'), Decimal('5028.970000'))
(datetime.date(2025, 5, 2), Decimal('8167058.515488'), Decimal('4952.610000'))
(datetime.date(2025, 5, 5), Decimal('7973099.086450'), Decimal('4855.500000'))
(datetime.date(2025, 5, 6), Decimal('7980688.008703'), Decimal('5014.860000'))
(datetime.date(2025, 5, 7), Decimal('8207545.052482'), Decimal('4931.860000'))
(datetime.date(2025, 5, 8), Decimal('8229539.783984'), Decimal('5083.750000'))
(datetime.date(2025, 5, 9), Decimal('8868161.595114'), Decimal('5176.710000'))
(datetime.date(2025, 5, 12), Decimal('8882429.185762'), Decimal('5255.560000'))
(datetime.date(2025, 5, 13), Decimal('8739740.641206'), Decimal('5398.320000'))
(datetime.date(2025, 5, 14), Decimal('8860925.913889'), Decimal('5351.840000'))
(datetime.date(2025, 5, 15), Decimal('8854656.259617'), Decimal('5231.490000'))
(datetime.date(2025, 5, 16), Decimal('8861418.050018'), Decimal('5298.720000'))
(datetime.date(2025, 5, 19), Decimal('9065676.354330'), Decimal('5310.340000'))
(datetime.date(2025, 5, 20), Decimal('9017978.281234'), Decimal('5309.510000'))
(datetime.date(2025, 5, 21), Decimal('9134061.037906'), Decimal('5223.190000'))
(datetime.date(2025, 5, 22), Decimal('9387459.456661'), Decimal('5191.650000'))
(datetime.date(2025, 5, 23), Decimal('9591418.421810'), Decimal('5219.870000'))
(datetime.date(2025, 5, 27), Decimal('9314436.685236'), Decimal('5113.630000'))
(datetime.date(2025, 5, 28), Decimal('9310175.102672'), Decimal('5190.820000'))
(datetime.date(2025, 5, 29), Decimal('9208280.990680'), Decimal('5117.780000'))
(datetime.date(2025, 5, 30), Decimal('9026592.666677'), Decimal('5101.180000'))
(datetime.date(2025, 6, 2), Decimal('9040802.274014'), Decimal('5251.410000'))
(datetime.date(2025, 6, 3), Decimal('9038740.617012'), Decimal('5320.300000'))
(datetime.date(2025, 6, 4), Decimal('9036688.899610'), Decimal('5276.310000'))
(datetime.date(2025, 6, 5), Decimal('9003749.459209'), Decimal('5316.980000'))
(datetime.date(2025, 6, 6), Decimal('8729536.730078'), Decimal('5419.900000'))
(datetime.date(2025, 6, 9), Decimal('9066867.468852'), Decimal('5477.170000'))
(datetime.date(2025, 6, 10), Decimal('9455619.179044'), Decimal('5449.780000'))
(datetime.date(2025, 6, 11), Decimal('9440056.689266'), Decimal('5719.530000'))
(datetime.date(2025, 6, 12), Decimal('9288882.881869'), Decimal('5704.590000'))
(datetime.date(2025, 6, 13), Decimal('9081227.025134'), Decimal('6128.720000'))
(datetime.date(2025, 6, 16), Decimal('9090411.274773'), Decimal('6019.990000'))
(datetime.date(2025, 6, 17), Decimal('9208980.453923'), Decimal('6276.460000'))
(datetime.date(2025, 6, 18), Decimal('9039952.955659'), Decimal('6298.870000'))
(datetime.date(2025, 6, 20), Decimal('9080584.318377'), Decimal('6284.760000'))
(datetime.date(2025, 6, 23), Decimal('8731873.284684'), Decimal('5756.880000'))
(datetime.date(2025, 6, 24), Decimal('9111429.945371'), Decimal('5432.350000'))
(datetime.date(2025, 6, 25), Decimal('9111165.386620'), Decimal('5476.340000'))
(datetime.date(2025, 6, 26), Decimal('9223086.808659'), Decimal('5514.520000'))
(datetime.date(2025, 6, 27), Decimal('9165684.099752'), Decimal('5532.780000'))
(datetime.date(2025, 6, 30), Decimal('9263092.465182'), Decimal('5502.900000'))
(datetime.date(2025, 7, 1), Decimal('9181709.414668'), Decimal('5531.120000'))
(datetime.date(2025, 7, 2), Decimal('9054321.250570'), Decimal('5698.780000'))
(datetime.date(2025, 7, 3), Decimal('9325640.339018'), Decimal('5654.790000'))
(datetime.date(2025, 7, 7), Decimal('9337523.923074'), Decimal('5740.280000'))
(datetime.date(2025, 7, 8), Decimal('9302203.177317'), Decimal('5772.650000'))
(datetime.date(2025, 7, 9), Decimal('9338122.035801'), Decimal('5777.630000'))
(datetime.date(2025, 7, 10), Decimal('9541743.483381'), Decimal('5625.740000'))
(datetime.date(2025, 7, 11), Decimal('9934947.612549'), Decimal('5779.290000'))
(datetime.date(2025, 7, 14), Decimal('10222853.345055'), Decimal('5659.770000'))
(datetime.date(2025, 7, 15), Decimal('10301939.218478'), Decimal('5624.080000'))
(datetime.date(2025, 7, 16), Decimal('10119542.204331'), Decimal('5571.790000'))
(datetime.date(2025, 7, 17), Decimal('10198739.393321'), Decimal('5707.080000'))
(datetime.date(2025, 7, 18), Decimal('10277885.478397'), Decimal('5687.990000'))
(datetime.date(2025, 7, 21), Decimal('10101549.352407'), Decimal('5676.370000'))
(datetime.date(2025, 7, 22), Decimal('10136533.758092'), Decimal('5607.480000'))
(datetime.date(2025, 7, 23), Decimal('10357349.266440'), Decimal('5482.150000'))
(datetime.date(2025, 7, 24), Decimal('10249425.749007'), Decimal('5574.280000'))
(datetime.date(2025, 7, 25), Decimal('10229427.683390'), Decimal('5509.540000'))
(datetime.date(2025, 7, 28), Decimal('10330494.375552'), Decimal('5628.230000'))
(datetime.date(2025, 7, 29), Decimal('10240072.841856'), Decimal('5832.410000'))
(datetime.date(2025, 7, 30), Decimal('10260715.669243'), Decimal('5900.470000'))
(datetime.date(2025, 7, 31), Decimal('10330510.927891'), Decimal('5839.880000'))
(datetime.date(2025, 8, 1), Decimal('10122552.718401'), Decimal('5676.370000'))
(datetime.date(2025, 8, 4), Decimal('9963363.104407'), Decimal('5588.390000'))
(datetime.date(2025, 8, 5), Decimal('10119947.866363'), Decimal('5494.600000'))
(datetime.date(2025, 8, 6), Decimal('10011721.550657'), Decimal('5426.540000'))
(datetime.date(2025, 8, 7), Decimal('10094655.435390'), Decimal('5386.700000'))
(datetime.date(2025, 8, 8), Decimal('10270107.263259'), Decimal('5390.020000'))
(datetime.date(2025, 8, 11), Decimal('10434491.300113'), Decimal('5397.490000'))
(datetime.date(2025, 8, 12), Decimal('10412275.449239'), Decimal('5330.260000'))
(datetime.date(2025, 8, 13), Decimal('10529495.638104'), Decimal('5285.440000'))
(datetime.date(2025, 8, 14), Decimal('10805439.783697'), Decimal('5394.170000'))
(datetime.date(2025, 8, 15), Decimal('10383230.847886'), Decimal('5293.740000'))
(datetime.date(2025, 8, 18), Decimal('10286533.101170'), Decimal('5354.330000'))
(datetime.date(2025, 8, 19), Decimal('10148644.242275'), Decimal('5260.540000'))
(datetime.date(2025, 8, 20), Decimal('9819786.419050'), Decimal('5327.770000'))
(datetime.date(2025, 8, 21), Decimal('9942066.543755'), Decimal('5358.480000'))
(datetime.date(2025, 8, 22), Decimal('9813063.277506'), Decimal('5318.640000'))
(datetime.date(2025, 8, 25), Decimal('9903221.350806'), Decimal('5409.940000'))
(datetime.date(2025, 8, 26), Decimal('9653212.189244'), Decimal('5278.800000'))
(datetime.date(2025, 8, 27), Decimal('9801777.668907'), Decimal('5352.670000'))
(datetime.date(2025, 8, 28), Decimal('9749130.258868'), Decimal('5391.680000'))
(datetime.date(2025, 8, 29), Decimal('9856302.068935'), Decimal('5341.880000'))
(datetime.date(2025, 9, 2), Decimal('9606486.079009'), Decimal('5473.850000'))
(datetime.date(2025, 9, 3), Decimal('9784574.242949'), Decimal('5341.880000'))
(datetime.date(2025, 9, 4), Decimal('9838796.609222'), Decimal('5296.230000'))
(datetime.date(2025, 9, 5), Decimal('9765163.284050'), Decimal('5164.260000'))
(datetime.date(2025, 9, 8), Decimal('9800346.003034'), Decimal('5195.800000'))
(datetime.date(2025, 9, 9), Decimal('9856054.849015'), Decimal('5226.510000'))
(datetime.date(2025, 9, 10), Decimal('9840553.151485'), Decimal('5312.830000'))
(datetime.date(2025, 9, 11), Decimal('10035954.764446'), Decimal('5204.930000'))
(datetime.date(2025, 9, 12), Decimal('10195205.098488'), Decimal('5230.660000'))
(datetime.date(2025, 9, 15), Decimal('10184894.127284'), Decimal('5283.780000'))
(datetime.date(2025, 9, 16), Decimal('10169238.650025'), Decimal('5385.870000'))
(datetime.date(2025, 9, 17), Decimal('10261685.530264'), Decimal('5346.030000'))
(datetime.date(2025, 9, 18), Decimal('10237752.888404'), Decimal('5304.530000'))
(datetime.date(2025, 9, 19), Decimal('10333070.257186'), Decimal('5230.660000'))
(datetime.date(2025, 9, 22), Decimal('10158260.693491'), Decimal('5228.170000'))
(datetime.date(2025, 9, 23), Decimal('9951646.271657'), Decimal('5292.080000'))
(datetime.date(2025, 9, 24), Decimal('9948492.512889'), Decimal('5428.200000'))
(datetime.date(2025, 9, 25), Decimal('10060469.351466'), Decimal('5437.330000'))
(datetime.date(2025, 9, 26), Decimal('9673068.167457'), Decimal('5519.500000'))
(datetime.date(2025, 9, 29), Decimal('9944472.608697'), Decimal('5334.410000'))
(datetime.date(2025, 9, 30), Decimal('10139763.924083'), Decimal('5243.110000'))
(datetime.date(2025, 10, 1), Decimal('10130020.723922'), Decimal('5194.970000'))
(datetime.date(2025, 10, 2), Decimal('10509252.859359'), Decimal('5086.240000'))
(datetime.date(2025, 10, 3), Decimal('10700725.995237'), Decimal('5116.950000'))
(datetime.date(2025, 10, 6), Decimal('10959365.064936'), Decimal('5186.670000'))
(datetime.date(2025, 10, 7), Decimal('11070472.246733'), Decimal('5189.160000'))
(datetime.date(2025, 10, 8), Decimal('10783920.730193'), Decimal('5259.710000'))
(datetime.date(2025, 10, 9), Decimal('10949945.979090'), Decimal('5175.880000'))
(datetime.date(2025, 10, 10), Decimal('10814774.599012'), Decimal('4959.250000'))
(datetime.date(2025, 10, 14), Decimal('10216224.051871'), Decimal('4940.160000'))
(datetime.date(2025, 10, 15), Decimal('10046351.075826'), Decimal('4903.640000'))
(datetime.date(2025, 10, 16), Decimal('9721344.884649'), Decimal('4838.070000'))
(datetime.date(2025, 10, 17), Decimal('9509774.024195'), Decimal('4838.900000'))
(datetime.date(2025, 10, 20), Decimal('9558930.877185'), Decimal('4842.220000'))
(datetime.date(2025, 10, 21), Decimal('9720308.914971'), Decimal('4868.780000'))
(datetime.date(2025, 10, 22), Decimal('9549158.301143'), Decimal('4921.900000'))
(datetime.date(2025, 10, 23), Decimal('9442499.946296'), Decimal('5182.520000'))
(datetime.date(2025, 10, 24), Decimal('9659976.397608'), Decimal('5168.410000'))
(datetime.date(2025, 10, 27), Decimal('10055171.794297'), Decimal('5156.790000'))
(datetime.date(2025, 10, 28), Decimal('10073474.454011'), Decimal('5060.510000'))
(datetime.date(2025, 10, 29), Decimal('9965129.220872'), Decimal('5084.580000'))
(datetime.date(2025, 10, 30), Decimal('9722166.865440'), Decimal('5092.880000'))
(datetime.date(2025, 10, 31), Decimal('9593893.171045'), Decimal('5125.250000'))
(datetime.date(2025, 11, 3), Decimal('9824421.072228'), Decimal('5128.570000'))
(datetime.date(2025, 11, 4), Decimal('9450928.858755'), Decimal('5094.540000'))
(datetime.date(2025, 11, 5), Decimal('9018317.599499'), Decimal('5013.200000'))
(datetime.date(2025, 11, 6), Decimal('9199126.082981'), Decimal('4999.920000'))
(datetime.date(2025, 11, 7), Decimal('8984607.813502'), Decimal('5024.820000'))
(datetime.date(2025, 11, 10), Decimal('9283589.006016'), Decimal('5058.020000'))
(datetime.date(2025, 11, 12), Decimal('9108594.696794'), Decimal('4921.900000'))
(datetime.date(2025, 11, 13), Decimal('8994239.327086'), Decimal('4941.820000'))
(datetime.date(2025, 11, 14), Decimal('8857694.854444'), Decimal('5052.210000'))
(datetime.date(2025, 11, 17), Decimal('8373085.239388'), Decimal('5034.780000'))
(datetime.date(2025, 11, 18), Decimal('8157780.455111'), Decimal('5105.330000'))
(datetime.date(2025, 11, 19), Decimal('8219844.429071'), Decimal('5002.410000'))
(datetime.date(2025, 11, 20), Decimal('8084502.705830'), Decimal('4985.810000'))
(datetime.date(2025, 11, 21), Decimal('7685198.360480'), Decimal('4885.380000'))
(datetime.date(2025, 11, 24), Decimal('7778520.446851'), Decimal('4906.130000'))
(datetime.date(2025, 11, 25), Decimal('7865475.253834'), Decimal('4834.750000'))
(datetime.date(2025, 11, 26), Decimal('7783791.323602'), Decimal('4881.230000'))
(datetime.date(2025, 11, 28), Decimal('8157156.351484'), Decimal('4862.140000'))
(datetime.date(2025, 12, 1), Decimal('8078246.317718'), Decimal('4936.010000'))
(datetime.date(2025, 12, 2), Decimal('7731939.315083'), Decimal('4881.230000'))
(datetime.date(2025, 12, 3), Decimal('8213485.439947'), Decimal('4904.470000'))
(datetime.date(2025, 12, 4), Decimal('8441734.894690'), Decimal('4965.060000'))
(datetime.date(2025, 12, 5), Decimal('8277612.193785'), Decimal('4999.090000'))
(datetime.date(2025, 12, 8), Decimal('8110183.521497'), Decimal('4900.320000'))
(datetime.date(2025, 12, 9), Decimal('8167418.756507'), Decimal('4847.200000'))
(datetime.date(2025, 12, 10), Decimal('8337407.116606'), Decimal('4869.610000'))
(datetime.date(2025, 12, 11), Decimal('8261440.281356'), Decimal('4794.080000'))
(datetime.date(2025, 12, 12), Decimal('8347818.307928'), Decimal('4781.630000'))
(datetime.date(2025, 12, 15), Decimal('7992348.231966'), Decimal('4728.510000'))
(datetime.date(2025, 12, 16), Decimal('7844409.288927'), Decimal('4601.520000'))
(datetime.date(2025, 12, 17), Decimal('7987315.985985'), Decimal('4653.810000'))
(datetime.date(2025, 12, 18), Decimal('7781471.915537'), Decimal('4666.260000'))
(datetime.date(2025, 12, 19), Decimal('7712879.171309'), Decimal('4714.400000'))
(datetime.date(2025, 12, 22), Decimal('7933999.654740'), Decimal('4828.940000'))
(datetime.date(2025, 12, 23), Decimal('7929162.759663'), Decimal('4859.650000'))
(datetime.date(2025, 12, 24), Decimal('7820620.968822'), Decimal('4873.760000'))
(datetime.date(2025, 12, 26), Decimal('7860175.221035'), Decimal('4697.800000'))
(datetime.date(2025, 12, 29), Decimal('7887770.596681'), Decimal('4804.870000'))
(datetime.date(2025, 12, 30), Decimal('7835388.056690'), Decimal('4796.570000'))
(datetime.date(2025, 12, 31), Decimal('7936951.056509'), Decimal('4752.580000'))
(datetime.date(2026, 1, 2), Decimal('7982611.090932'), Decimal('4748.430000'))
(datetime.date(2026, 1, 5), Decimal('8224912.970330'), Decimal('4822.300000'))
(datetime.date(2026, 1, 6), Decimal('8475311.204337'), Decimal('4728.510000'))
(datetime.date(2026, 1, 7), Decimal('8443838.294347'), Decimal('4648.830000'))
(datetime.date(2026, 1, 8), Decimal('8200790.873529'), Decimal('4792.420000'))
(datetime.date(2026, 1, 9), Decimal('8179932.125614'), Decimal('4893.680000'))
(datetime.date(2026, 1, 12), Decimal('8196362.955223'), Decimal('4929.370000'))
(datetime.date(2026, 1, 13), Decimal('8214254.506812'), Decimal('5050.550000'))
(datetime.date(2026, 1, 14), Decimal('8600260.479528'), Decimal('5132.720000'))
(datetime.date(2026, 1, 15), Decimal('8754772.557780'), Decimal('4907.790000'))
(datetime.date(2026, 1, 16), Decimal('8637202.771129'), Decimal('4930.200000'))
(datetime.date(2026, 1, 20), Decimal('8414003.970645'), Decimal('5004.900000'))
(datetime.date(2026, 1, 21), Decimal('8046939.830277'), Decimal('5011.540000'))
(datetime.date(2026, 1, 22), Decimal('8179241.969295'), Decimal('4916.920000'))
(datetime.date(2026, 1, 23), Decimal('8189307.776815'), Decimal('5038.100000'))
(datetime.date(2026, 1, 26), Decimal('7931480.810441'), Decimal('5018.180000'))
(datetime.date(2026, 1, 27), Decimal('8098992.121061'), Decimal('5149.320000'))
(datetime.date(2026, 1, 28), Decimal('8165356.488930'), Decimal('5208.250000'))
(datetime.date(2026, 1, 29), Decimal('8206661.924142'), Decimal('5375.910000'))
(datetime.date(2026, 1, 30), Decimal('7762053.970031'), Decimal('5353.500000'))
(datetime.date(2026, 2, 2), Decimal('7055170.474775'), Decimal('5112.800000'))
(datetime.date(2026, 2, 3), Decimal('7124353.514367'), Decimal('5197.460000'))
(datetime.date(2026, 2, 4), Decimal('6839512.652076'), Decimal('5358.480000'))
(datetime.date(2026, 2, 5), Decimal('6617843.606631'), Decimal('5220.700000'))
(datetime.date(2026, 2, 6), Decimal('5676634.189757'), Decimal('5292.910000'))
(datetime.date(2026, 2, 9), Decimal('6388983.809905'), Decimal('5355.990000'))
(datetime.date(2026, 2, 10), Decimal('6363124.007123'), Decimal('5328.600000'))
(datetime.date(2026, 2, 11), Decimal('6230645.199778'), Decimal('5378.400000'))
(datetime.date(2026, 2, 12), Decimal('6073656.888034'), Decimal('5235.640000'))
(datetime.date(2026, 2, 13), Decimal('5993963.255323'), Decimal('5233.150000'))
(datetime.date(2026, 2, 17), Decimal('6255749.578602'), Decimal('5189.990000'))
(datetime.date(2026, 2, 18), Decimal('6116329.755578'), Decimal('5422.390000'))
(datetime.date(2026, 2, 19), Decimal('6033801.765391'), Decimal('5532.780000'))
(datetime.date(2026, 2, 20), Decimal('6092367.347486'), Decimal('5535.270000'))
(datetime.date(2026, 2, 23), Decimal('6132044.383909'), Decimal('5507.880000'))
(datetime.date(2026, 2, 24), Decimal('5877904.816486'), Decimal('5446.460000'))
(datetime.date(2026, 2, 25), Decimal('5825506.041088'), Decimal('5419.900000'))
(datetime.date(2026, 2, 26), Decimal('6179906.746479'), Decimal('5403.300000'))
(datetime.date(2026, 2, 27), Decimal('6139221.658943'), Decimal('5557.680000'))
(datetime.date(2026, 3, 2), Decimal('5984275.487394'), Decimal('5903.790000'))
(datetime.date(2026, 3, 3), Decimal('6305544.630558'), Decimal('6181.840000'))
(datetime.date(2026, 3, 4), Decimal('6286193.488373'), Decimal('6190.140000'))
(datetime.date(2026, 3, 5), Decimal('6694568.064726'), Decimal('6713.040000'))
(datetime.date(2026, 3, 6), Decimal('6505413.051213'), Decimal('7533.910000'))
(datetime.date(2026, 3, 9), Decimal('6071162.609842'), Decimal('7855.950000'))
(datetime.date(2026, 3, 10), Decimal('6319544.712080'), Decimal('6947.930000'))
(datetime.date(2026, 3, 11), Decimal('6427459.132594'), Decimal('7204.400000'))
(datetime.date(2026, 3, 12), Decimal('6476952.781588'), Decimal('7935.630000'))
(datetime.date(2026, 3, 13), Decimal('6517601.857024'), Decimal('8173.840000'))
(datetime.date(2026, 3, 16), Decimal('6727548.658016'), Decimal('7751.370000'))
(datetime.date(2026, 3, 17), Decimal('6906940.623961'), Decimal('7968.830000'))
(datetime.date(2026, 3, 18), Decimal('6829860.404015'), Decimal('7977.960000'))
(datetime.date(2026, 3, 19), Decimal('6639390.135900'), Decimal('7977.130000'))
(datetime.date(2026, 3, 20), Decimal('6504037.303026'), Decimal('8192.930000'))
(datetime.date(2026, 3, 23), Decimal('6364717.089252'), Decimal('7414.390000'))
(datetime.date(2026, 3, 24), Decimal('6614293.785504'), Decimal('7733.940000'))
(datetime.date(2026, 3, 25), Decimal('6649392.307316'), Decimal('7595.330000'))
(datetime.date(2026, 3, 26), Decimal('6712173.732416'), Decimal('7982.940000'))
(datetime.date(2026, 3, 27), Decimal('6487672.474785'), Decimal('8404.580000'))
(datetime.date(2026, 3, 30), Decimal('6252812.763420'), Decimal('8689.270000'))
(datetime.date(2026, 3, 31), Decimal('6293233.346703'), Decimal('8537.380000'))
(datetime.date(2026, 4, 1), Decimal('6378628.791276'), Decimal('8457.700000'))
(datetime.date(2026, 4, 2), Decimal('6307964.144412'), Decimal('9398.090000'))
(datetime.date(2026, 4, 6), Decimal('6414170.630917'), Decimal('9462.830000'))

In [18]:
#step to corelation
import pandas as pd

# Convert SQL result to DataFrame
df = pd.DataFrame(data, columns=["date", "bitcoin_price", "oil_price"])

# Calculate correlation
correlation = df["bitcoin_price"].corr(df["oil_price"])

print("Correlation:", correlation)

Correlation: -0.4005256992697516

In [19]:
#Compare NASDAQ (^IXIC) with Ethereum price trends
cursor.execute("""
SELECT 
    cp.date,
    cp.price_inr AS ethereum_price,
    sp.close AS nasdaq_price

FROM crypto_prices cp

-- Join stock data using same date
JOIN stock_prices sp 
ON cp.date = sp.date

-- Filter Ethereum
WHERE cp.coin_id = 'ethereum'

-- Filter NASDAQ
AND sp.ticker = '^IXIC'

-- Sort for trend
ORDER BY cp.date
""")

data = cursor.fetchall()

for row in data:
    print(row)

(datetime.date(2025, 4, 15), Decimal('139502.269181'), Decimal('16823.169922'))
(datetime.date(2025, 4, 16), Decimal('136118.340300'), Decimal('16307.160156'))
(datetime.date(2025, 4, 17), Decimal('135084.250075'), Decimal('16286.450195'))
(datetime.date(2025, 4, 21), Decimal('135372.221202'), Decimal('15870.900391'))
(datetime.date(2025, 4, 22), Decimal('134334.008185'), Decimal('16300.419922'))
(datetime.date(2025, 4, 23), Decimal('149984.444802'), Decimal('16708.050781'))
(datetime.date(2025, 4, 24), Decimal('153384.691226'), Decimal('17166.039063'))
(datetime.date(2025, 4, 25), Decimal('150793.822639'), Decimal('17382.939453'))
(datetime.date(2025, 4, 28), Decimal('153154.647160'), Decimal('17366.130859'))
(datetime.date(2025, 4, 29), Decimal('153246.471992'), Decimal('17461.320313'))
(datetime.date(2025, 4, 30), Decimal('153045.868306'), Decimal('17446.339844'))
(datetime.date(2025, 5, 1), Decimal('151706.989211'), Decimal('17710.740234'))
(datetime.date(2025, 5, 2), Decimal('155745.169241'), Decimal('17977.730469'))
(datetime.date(2025, 5, 5), Decimal('152837.106066'), Decimal('17844.240234'))
(datetime.date(2025, 5, 6), Decimal('153282.693897'), Decimal('17689.660156'))
(datetime.date(2025, 5, 7), Decimal('153903.860522'), Decimal('17738.160156'))
(datetime.date(2025, 5, 8), Decimal('153546.465434'), Decimal('17928.140625'))
(datetime.date(2025, 5, 9), Decimal('189067.053860'), Decimal('17928.919922'))
(datetime.date(2025, 5, 12), Decimal('214170.100120'), Decimal('18708.339844'))
(datetime.date(2025, 5, 13), Decimal('211740.195869'), Decimal('19010.089844'))
(datetime.date(2025, 5, 14), Decimal('227649.060175'), Decimal('19146.810547'))
(datetime.date(2025, 5, 15), Decimal('222550.861260'), Decimal('19112.320313'))
(datetime.date(2025, 5, 16), Decimal('217226.914605'), Decimal('19211.099609'))
(datetime.date(2025, 5, 19), Decimal('210787.975693'), Decimal('19215.460938'))
(datetime.date(2025, 5, 20), Decimal('215738.556840'), Decimal('19142.710938'))
(datetime.date(2025, 5, 21), Decimal('215915.199355'), Decimal('18872.640625'))
(datetime.date(2025, 5, 22), Decimal('219047.575634'), Decimal('18925.740234'))
(datetime.date(2025, 5, 23), Decimal('228450.369638'), Decimal('18737.210938'))
(datetime.date(2025, 5, 26), Decimal('216970.852280'), None)
(datetime.date(2025, 5, 27), Decimal('218190.675235'), Decimal('19199.160156'))
(datetime.date(2025, 5, 28), Decimal('227238.584850'), Decimal('19100.939453'))
(datetime.date(2025, 5, 29), Decimal('228525.939096'), Decimal('19175.869141'))
(datetime.date(2025, 5, 30), Decimal('224768.844035'), Decimal('19113.769531'))
(datetime.date(2025, 6, 2), Decimal('217089.574074'), Decimal('19242.609375'))
(datetime.date(2025, 6, 3), Decimal('222777.498728'), Decimal('19398.960938'))
(datetime.date(2025, 6, 4), Decimal('222455.178610'), Decimal('19460.490234'))
(datetime.date(2025, 6, 5), Decimal('224236.444163'), Decimal('19298.449219'))
(datetime.date(2025, 6, 6), Decimal('207961.654189'), Decimal('19529.949219'))
(datetime.date(2025, 6, 9), Decimal('215217.423364'), Decimal('19591.240234'))
(datetime.date(2025, 6, 10), Decimal('230255.547118'), Decimal('19714.990234'))
(datetime.date(2025, 6, 11), Decimal('240556.865727'), Decimal('19615.880859'))
(datetime.date(2025, 6, 12), Decimal('237276.581795'), Decimal('19662.490234'))
(datetime.date(2025, 6, 13), Decimal('227345.610242'), Decimal('19406.830078'))
(datetime.date(2025, 6, 16), Decimal('219421.869835'), Decimal('19701.210938'))
(datetime.date(2025, 6, 17), Decimal('220541.897449'), Decimal('19521.089844'))
(datetime.date(2025, 6, 18), Decimal('217182.056291'), Decimal('19546.269531'))
(datetime.date(2025, 6, 19), Decimal('218382.420147'), None)
(datetime.date(2025, 6, 20), Decimal('218767.013088'), Decimal('19447.410156'))
(datetime.date(2025, 6, 23), Decimal('192852.030967'), Decimal('19630.970703'))
(datetime.date(2025, 6, 24), Decimal('209315.247806'), Decimal('19912.529297'))
(datetime.date(2025, 6, 25), Decimal('210338.280603'), Decimal('19973.550781'))
(datetime.date(2025, 6, 26), Decimal('207894.423633'), Decimal('20167.910156'))
(datetime.date(2025, 6, 27), Decimal('206903.990972'), Decimal('20273.460938'))
(datetime.date(2025, 6, 30), Decimal('213866.808206'), Decimal('20369.730469'))
(datetime.date(2025, 7, 1), Decimal('213247.902754'), Decimal('20202.890625'))
(datetime.date(2025, 7, 2), Decimal('206191.537951'), Decimal('20393.130859'))
(datetime.date(2025, 7, 3), Decimal('220583.067715'), Decimal('20601.099609'))
(datetime.date(2025, 7, 4), Decimal('221209.207186'), None)
(datetime.date(2025, 7, 7), Decimal('219842.285096'), Decimal('20412.519531'))
(datetime.date(2025, 7, 8), Decimal('218478.507032'), Decimal('20418.460938'))
(datetime.date(2025, 7, 9), Decimal('224192.012935'), Decimal('20611.339844'))
(datetime.date(2025, 7, 10), Decimal('237634.328591'), Decimal('20630.660156'))
(datetime.date(2025, 7, 11), Decimal('252785.182611'), Decimal('20585.529297'))
(datetime.date(2025, 7, 14), Decimal('255256.074912'), Decimal('20640.330078'))
(datetime.date(2025, 7, 15), Decimal('258953.022960'), Decimal('20677.800781'))
(datetime.date(2025, 7, 16), Decimal('269423.172852'), Decimal('20730.490234'))
(datetime.date(2025, 7, 17), Decimal('289273.061958'), Decimal('20885.650391'))
(datetime.date(2025, 7, 18), Decimal('299604.700132'), Decimal('20895.650391'))
(datetime.date(2025, 7, 21), Decimal('323799.563511'), Decimal('20974.179688'))
(datetime.date(2025, 7, 22), Decimal('324888.026671'), Decimal('20892.689453'))
(datetime.date(2025, 7, 23), Decimal('323522.285507'), Decimal('21020.019531'))
(datetime.date(2025, 7, 24), Decimal('313632.809934'), Decimal('21057.960938'))
(datetime.date(2025, 7, 25), Decimal('320521.286638'), Decimal('21108.320313'))
(datetime.date(2025, 7, 28), Decimal('334271.335633'), Decimal('21178.580078'))
(datetime.date(2025, 7, 29), Decimal('328567.307202'), Decimal('21098.289063'))
(datetime.date(2025, 7, 30), Decimal('329848.444896'), Decimal('21129.669922'))
(datetime.date(2025, 7, 31), Decimal('333798.497867'), Decimal('21122.449219'))
(datetime.date(2025, 8, 1), Decimal('323419.739184'), Decimal('20650.130859'))
(datetime.date(2025, 8, 4), Decimal('305147.659724'), Decimal('21053.580078'))
(datetime.date(2025, 8, 5), Decimal('326586.856083'), Decimal('20916.550781'))
(datetime.date(2025, 8, 6), Decimal('316895.551838'), Decimal('21169.419922'))
(datetime.date(2025, 8, 7), Decimal('323322.001028'), Decimal('21242.699219'))
(datetime.date(2025, 8, 8), Decimal('341975.042294'), Decimal('21450.019531'))
(datetime.date(2025, 8, 11), Decimal('372140.597063'), Decimal('21385.400391'))
(datetime.date(2025, 8, 12), Decimal('370718.817449'), Decimal('21681.900391'))
(datetime.date(2025, 8, 13), Decimal('403547.061908'), Decimal('21713.140625'))
(datetime.date(2025, 8, 14), Decimal('416582.605127'), Decimal('21710.669922'))
(datetime.date(2025, 8, 15), Decimal('399375.212719'), Decimal('21622.980469'))
(datetime.date(2025, 8, 18), Decimal('392681.418991'), Decimal('21629.769531'))
(datetime.date(2025, 8, 19), Decimal('376878.098282'), Decimal('21314.949219'))
(datetime.date(2025, 8, 20), Decimal('354772.704309'), Decimal('21172.859375'))
(datetime.date(2025, 8, 21), Decimal('376832.666663'), Decimal('21100.310547'))
(datetime.date(2025, 8, 22), Decimal('368766.663947'), Decimal('21496.539063'))
(datetime.date(2025, 8, 25), Decimal('417273.907118'), Decimal('21449.289063'))
(datetime.date(2025, 8, 26), Decimal('383869.230416'), Decimal('21544.269531'))
(datetime.date(2025, 8, 27), Decimal('403346.846734'), Decimal('21590.140625'))
(datetime.date(2025, 8, 28), Decimal('394479.821080'), Decimal('21705.160156'))
(datetime.date(2025, 8, 29), Decimal('394824.628584'), Decimal('21455.550781'))
(datetime.date(2025, 9, 1), Decimal('386992.074421'), None)
(datetime.date(2025, 9, 2), Decimal('378688.487081'), Decimal('21279.630859'))
(datetime.date(2025, 9, 3), Decimal('380669.060827'), Decimal('21497.730469'))
(datetime.date(2025, 9, 4), Decimal('391914.257365'), Decimal('21707.689453'))
(datetime.date(2025, 9, 5), Decimal('379062.507112'), Decimal('21700.390625'))
(datetime.date(2025, 9, 8), Decimal('379557.731567'), Decimal('21798.699219'))
(datetime.date(2025, 9, 9), Decimal('379169.380394'), Decimal('21879.490234'))
(datetime.date(2025, 9, 10), Decimal('380163.959897'), Decimal('21886.060547'))
(datetime.date(2025, 9, 11), Decimal('382811.635601'), Decimal('22043.070313'))
(datetime.date(2025, 9, 12), Decimal('393614.073912'), Decimal('22141.099609'))
(datetime.date(2025, 9, 15), Decimal('406940.596240'), Decimal('22348.750000'))
(datetime.date(2025, 9, 16), Decimal('398693.429952'), Decimal('22333.960938'))
(datetime.date(2025, 9, 17), Decimal('395856.797623'), Decimal('22261.330078'))
(datetime.date(2025, 9, 18), Decimal('403666.756890'), Decimal('22470.720703'))
(datetime.date(2025, 9, 19), Decimal('404926.983275'), Decimal('22631.480469'))
(datetime.date(2025, 9, 22), Decimal('392295.475243'), Decimal('22788.980469'))
(datetime.date(2025, 9, 23), Decimal('370875.271422'), Decimal('22573.470703'))
(datetime.date(2025, 9, 24), Decimal('369992.091901'), Decimal('22497.859375'))
(datetime.date(2025, 9, 25), Decimal('368312.965606'), Decimal('22384.699219'))
(datetime.date(2025, 9, 26), Decimal('342937.444019'), Decimal('22484.070313'))
(datetime.date(2025, 9, 29), Decimal('367286.122984'), Decimal('22591.150391'))
(datetime.date(2025, 9, 30), Decimal('373944.853294'), Decimal('22660.009766'))
(datetime.date(2025, 10, 1), Decimal('368177.371385'), Decimal('22755.160156'))
(datetime.date(2025, 10, 2), Decimal('385235.779735'), Decimal('22844.050781'))
(datetime.date(2025, 10, 3), Decimal('397823.051940'), Decimal('22780.509766'))
(datetime.date(2025, 10, 6), Decimal('400668.642140'), Decimal('22941.669922'))
(datetime.date(2025, 10, 7), Decimal('416041.060854'), Decimal('22788.359375'))
(datetime.date(2025, 10, 8), Decimal('395289.802631'), Decimal('23043.380859'))
(datetime.date(2025, 10, 9), Decimal('401911.048471'), Decimal('23024.630859'))
(datetime.date(2025, 10, 10), Decimal('388222.872053'), Decimal('22204.429688'))
(datetime.date(2025, 10, 13), Decimal('369207.336266'), Decimal('22694.609375'))
(datetime.date(2025, 10, 14), Decimal('376492.357405'), Decimal('22521.699219'))
(datetime.date(2025, 10, 15), Decimal('366574.058384'), Decimal('22670.080078'))
(datetime.date(2025, 10, 16), Decimal('349761.388471'), Decimal('22562.539063'))
(datetime.date(2025, 10, 17), Decimal('342302.332206'), Decimal('22679.970703'))
(datetime.date(2025, 10, 20), Decimal('350696.680434'), Decimal('22990.539063'))
(datetime.date(2025, 10, 21), Decimal('349657.073531'), Decimal('22953.669922'))
(datetime.date(2025, 10, 22), Decimal('341303.984264'), Decimal('22740.400391'))
(datetime.date(2025, 10, 23), Decimal('333571.215359'), Decimal('22941.800781'))
(datetime.date(2025, 10, 24), Decimal('338462.929082'), Decimal('23204.869141'))
(datetime.date(2025, 10, 27), Decimal('365539.562112'), Decimal('23637.460938'))
(datetime.date(2025, 10, 28), Decimal('363758.942322'), Decimal('23827.490234'))
(datetime.date(2025, 10, 29), Decimal('351342.532572'), Decimal('23958.470703'))
(datetime.date(2025, 10, 30), Decimal('344315.528945'), Decimal('23581.140625'))
(datetime.date(2025, 10, 31), Decimal('337015.499062'), Decimal('23724.960938'))
(datetime.date(2025, 11, 3), Decimal('347169.858003'), Decimal('23834.720703'))
(datetime.date(2025, 11, 4), Decimal('319468.258320'), Decimal('23348.640625'))
(datetime.date(2025, 11, 5), Decimal('292527.201423'), Decimal('23499.800781'))
(datetime.date(2025, 11, 6), Decimal('303546.180795'), Decimal('23053.990234'))
(datetime.date(2025, 11, 7), Decimal('293412.527668'), Decimal('23004.539063'))
(datetime.date(2025, 11, 10), Decimal('317071.729162'), Decimal('23527.169922'))
(datetime.date(2025, 11, 11), Decimal('316207.159735'), Decimal('23468.300781'))
(datetime.date(2025, 11, 12), Decimal('302271.191060'), Decimal('23406.460938'))
(datetime.date(2025, 11, 13), Decimal('302072.225249'), Decimal('22870.359375'))
(datetime.date(2025, 11, 14), Decimal('287385.518250'), Decimal('22900.589844'))
(datetime.date(2025, 11, 17), Decimal('275080.205979'), Decimal('22708.070313'))
(datetime.date(2025, 11, 18), Decimal('267796.573111'), Decimal('22432.849609'))
(datetime.date(2025, 11, 19), Decimal('276052.048981'), Decimal('22564.230469'))
(datetime.date(2025, 11, 20), Decimal('267032.830083'), Decimal('22078.050781'))
(datetime.date(2025, 11, 21), Decimal('251183.081268'), Decimal('22273.080078'))
(datetime.date(2025, 11, 24), Decimal('250950.128363'), Decimal('22872.009766'))
(datetime.date(2025, 11, 25), Decimal('263283.403583'), Decimal('23025.589844'))
(datetime.date(2025, 11, 26), Decimal('263444.939990'), Decimal('23214.689453'))
(datetime.date(2025, 11, 27), Decimal('269938.197095'), None)
(datetime.date(2025, 11, 28), Decimal('269490.252798'), Decimal('23365.689453'))
(datetime.date(2025, 12, 1), Decimal('267424.459259'), Decimal('23275.919922'))
(datetime.date(2025, 12, 2), Decimal('250829.944089'), Decimal('23413.669922'))
(datetime.date(2025, 12, 3), Decimal('269370.304182'), Decimal('23454.089844'))
(datetime.date(2025, 12, 4), Decimal('288132.425357'), Decimal('23505.140625'))
(datetime.date(2025, 12, 5), Decimal('281520.951599'), Decimal('23578.130859'))
(datetime.date(2025, 12, 8), Decimal('274616.237564'), Decimal('23545.900391'))
(datetime.date(2025, 12, 9), Decimal('281685.692185'), Decimal('23576.490234'))
(datetime.date(2025, 12, 10), Decimal('298746.963031'), Decimal('23654.150391'))
(datetime.date(2025, 12, 11), Decimal('298675.714749'), Decimal('23593.859375'))
(datetime.date(2025, 12, 12), Decimal('292065.557142'), Decimal('23195.169922'))
(datetime.date(2025, 12, 15), Decimal('277686.257525'), Decimal('23057.410156'))
(datetime.date(2025, 12, 16), Decimal('269107.822475'), Decimal('23111.460938'))
(datetime.date(2025, 12, 17), Decimal('269596.837410'), Decimal('22693.320313'))
(datetime.date(2025, 12, 18), Decimal('255672.948161'), Decimal('23006.359375'))
(datetime.date(2025, 12, 19), Decimal('255132.826415'), Decimal('23307.619141'))
(datetime.date(2025, 12, 22), Decimal('268857.457211'), Decimal('23428.830078'))
(datetime.date(2025, 12, 23), Decimal('269330.668986'), Decimal('23561.839844'))
(datetime.date(2025, 12, 24), Decimal('265308.330577'), Decimal('23613.310547'))
(datetime.date(2025, 12, 26), Decimal('261698.838882'), Decimal('23593.099609'))
(datetime.date(2025, 12, 29), Decimal('264760.550466'), Decimal('23474.349609'))
(datetime.date(2025, 12, 30), Decimal('263786.422730'), Decimal('23419.080078'))
(datetime.date(2025, 12, 31), Decimal('266620.867155'), Decimal('23241.990234'))
(datetime.date(2026, 1, 1), Decimal('266951.631246'), None)
(datetime.date(2026, 1, 2), Decimal('269940.356920'), Decimal('23235.630859'))
(datetime.date(2026, 1, 5), Decimal('282560.603013'), Decimal('23395.820313'))
(datetime.date(2026, 1, 6), Decimal('291299.356865'), Decimal('23547.169922'))
(datetime.date(2026, 1, 7), Decimal('297045.365799'), Decimal('23584.279297'))
(datetime.date(2026, 1, 8), Decimal('284403.121916'), Decimal('23480.019531'))
(datetime.date(2026, 1, 9), Decimal('279086.945835'), Decimal('23671.349609'))
(datetime.date(2026, 1, 12), Decimal('281519.501243'), Decimal('23733.900391'))
(datetime.date(2026, 1, 13), Decimal('278535.988919'), Decimal('23709.869141'))
(datetime.date(2026, 1, 14), Decimal('299728.917769'), Decimal('23471.750000'))
(datetime.date(2026, 1, 15), Decimal('302917.584443'), Decimal('23530.019531'))
(datetime.date(2026, 1, 16), Decimal('299838.361580'), Decimal('23515.390625'))
(datetime.date(2026, 1, 19), Decimal('297943.760244'), None)
(datetime.date(2026, 1, 20), Decimal('289592.031656'), Decimal('22954.320313'))
(datetime.date(2026, 1, 21), Decimal('267489.810962'), Decimal('23224.820313'))
(datetime.date(2026, 1, 22), Decimal('272419.057136'), Decimal('23436.019531'))
(datetime.date(2026, 1, 23), Decimal('269940.048570'), Decimal('23501.240234'))
(datetime.date(2026, 1, 26), Decimal('257898.210111'), Decimal('23601.359375'))
(datetime.date(2026, 1, 27), Decimal('268521.112403'), Decimal('23817.099609'))
(datetime.date(2026, 1, 28), Decimal('276537.237356'), Decimal('23857.449219'))
(datetime.date(2026, 1, 29), Decimal('276752.681611'), Decimal('23685.119141'))
(datetime.date(2026, 1, 30), Decimal('258717.166423'), Decimal('23461.820313'))
(datetime.date(2026, 2, 2), Decimal('208098.685692'), Decimal('23592.109375'))
(datetime.date(2026, 2, 3), Decimal('212055.741670'), Decimal('23255.189453'))
(datetime.date(2026, 2, 4), Decimal('201371.053946'), Decimal('22904.580078'))
(datetime.date(2026, 2, 5), Decimal('194638.911472'), Decimal('22540.589844'))
(datetime.date(2026, 2, 6), Decimal('164424.809305'), Decimal('23031.210938'))
(datetime.date(2026, 2, 9), Decimal('189754.818713'), Decimal('23238.669922'))
(datetime.date(2026, 2, 10), Decimal('191035.838887'), Decimal('23102.470703'))
(datetime.date(2026, 2, 11), Decimal('182890.582231'), Decimal('23066.470703'))
(datetime.date(2026, 2, 12), Decimal('175976.564045'), Decimal('22597.150391'))
(datetime.date(2026, 2, 13), Decimal('176214.238345'), Decimal('22546.669922'))
(datetime.date(2026, 2, 16), Decimal('177856.250639'), None)
(datetime.date(2026, 2, 17), Decimal('181624.154700'), Decimal('22578.380859'))
(datetime.date(2026, 2, 18), Decimal('180528.328343'), Decimal('22753.630859'))
(datetime.date(2026, 2, 19), Decimal('177478.459914'), Decimal('22682.730469'))
(datetime.date(2026, 2, 20), Decimal('177249.247482'), Decimal('22886.070313'))
(datetime.date(2026, 2, 23), Decimal('177305.132105'), Decimal('22627.269531'))
(datetime.date(2026, 2, 24), Decimal('168724.996141'), Decimal('22863.679688'))
(datetime.date(2026, 2, 25), Decimal('168454.269455'), Decimal('23152.080078'))
(datetime.date(2026, 2, 26), Decimal('186740.273499'), Decimal('22878.380859'))
(datetime.date(2026, 2, 27), Decimal('184470.530870'), Decimal('22668.210938'))
(datetime.date(2026, 3, 2), Decimal('176523.675178'), Decimal('22748.859375'))
(datetime.date(2026, 3, 3), Decimal('185826.307234'), Decimal('22516.689453'))
(datetime.date(2026, 3, 4), Decimal('182403.706392'), Decimal('22807.480469'))
(datetime.date(2026, 3, 5), Decimal('195838.576297'), Decimal('22748.990234'))
(datetime.date(2026, 3, 6), Decimal('190414.484773'), Decimal('22387.679688'))
(datetime.date(2026, 3, 9), Decimal('178231.253138'), Decimal('22695.949219'))
(datetime.date(2026, 3, 10), Decimal('183916.211871'), Decimal('22697.099609'))
(datetime.date(2026, 3, 11), Decimal('187187.451633'), Decimal('22716.130859'))
(datetime.date(2026, 3, 12), Decimal('189229.216518'), Decimal('22311.980469'))
(datetime.date(2026, 3, 13), Decimal('191849.404941'), Decimal('22105.359375'))
(datetime.date(2026, 3, 16), Decimal('201326.860562'), Decimal('22374.179688'))
(datetime.date(2026, 3, 17), Decimal('216935.792601'), Decimal('22479.529297'))
(datetime.date(2026, 3, 18), Decimal('214165.158931'), Decimal('22152.419922'))
(datetime.date(2026, 3, 19), Decimal('205303.803871'), Decimal('22090.689453'))
(datetime.date(2026, 3, 20), Decimal('198966.165564'), Decimal('21647.609375'))
(datetime.date(2026, 3, 23), Decimal('192599.900716'), Decimal('21946.759766'))
(datetime.date(2026, 3, 24), Decimal('200734.573905'), Decimal('21761.890625'))
(datetime.date(2026, 3, 25), Decimal('203248.109901'), Decimal('21929.820313'))
(datetime.date(2026, 3, 26), Decimal('204093.187222'), Decimal('21408.080078'))
(datetime.date(2026, 3, 27), Decimal('194215.144520'), Decimal('20948.359375'))
(datetime.date(2026, 3, 30), Decimal('187970.268869'), Decimal('20794.640625'))
(datetime.date(2026, 3, 31), Decimal('190952.553975'), Decimal('21590.630859'))
(datetime.date(2026, 4, 1), Decimal('196773.650908'), Decimal('21840.949219'))
(datetime.date(2026, 4, 2), Decimal('198168.419126'), Decimal('21879.179688'))

In [20]:
#step to corelation
import pandas as pd

df = pd.DataFrame(data, columns=["date", "ethereum_price", "nasdaq_price"])

correlation = df["ethereum_price"].corr(df["nasdaq_price"])

print("Correlation:", correlation)

Correlation: 0.45183765866000125

In [21]:
#Join top 3 crypto coins with stock indices for 2025
cursor.execute("""
SELECT 
    cp.date,
    cp.coin_id,
    cp.price_inr AS crypto_price,

    sp.ticker,
    sp.close AS stock_price

FROM crypto_prices cp

-- Join with stock data
JOIN stock_prices sp 
ON cp.date = sp.date

-- Top 3 coins
WHERE cp.coin_id IN ('bitcoin', 'ethereum', 'tether')

-- Stock indices
AND sp.ticker IN ('^GSPC', '^IXIC', '^NSEI')

-- Year filter (change if needed)
AND YEAR(cp.date) = 2025

-- Sort nicely
ORDER BY cp.date, cp.coin_id, sp.ticker
""")

data = cursor.fetchall()

for row in data:
    print(row)

(datetime.date(2025, 4, 15), 'bitcoin', Decimal('7271599.950977'), '^GSPC', Decimal('5396.629883'))
(datetime.date(2025, 4, 15), 'bitcoin', Decimal('7271599.950977'), '^IXIC', Decimal('16823.169922'))
(datetime.date(2025, 4, 15), 'bitcoin', Decimal('7271599.950977'), '^NSEI', Decimal('23328.550781'))
(datetime.date(2025, 4, 15), 'ethereum', Decimal('139502.269181'), '^GSPC', Decimal('5396.629883'))
(datetime.date(2025, 4, 15), 'ethereum', Decimal('139502.269181'), '^IXIC', Decimal('16823.169922'))
(datetime.date(2025, 4, 15), 'ethereum', Decimal('139502.269181'), '^NSEI', Decimal('23328.550781'))
(datetime.date(2025, 4, 15), 'tether', Decimal('86.024832'), '^GSPC', Decimal('5396.629883'))
(datetime.date(2025, 4, 15), 'tether', Decimal('86.024832'), '^IXIC', Decimal('16823.169922'))
(datetime.date(2025, 4, 15), 'tether', Decimal('86.024832'), '^NSEI', Decimal('23328.550781'))
(datetime.date(2025, 4, 16), 'bitcoin', Decimal('7171572.949307'), '^GSPC', Decimal('5275.700195'))
(datetime.date(2025, 4, 16), 'bitcoin', Decimal('7171572.949307'), '^IXIC', Decimal('16307.160156'))
(datetime.date(2025, 4, 16), 'bitcoin', Decimal('7171572.949307'), '^NSEI', Decimal('23437.199219'))
(datetime.date(2025, 4, 16), 'ethereum', Decimal('136118.340300'), '^GSPC', Decimal('5275.700195'))
(datetime.date(2025, 4, 16), 'ethereum', Decimal('136118.340300'), '^IXIC', Decimal('16307.160156'))
(datetime.date(2025, 4, 16), 'ethereum', Decimal('136118.340300'), '^NSEI', Decimal('23437.199219'))
(datetime.date(2025, 4, 16), 'tether', Decimal('85.722129'), '^GSPC', Decimal('5275.700195'))
(datetime.date(2025, 4, 16), 'tether', Decimal('85.722129'), '^IXIC', Decimal('16307.160156'))
(datetime.date(2025, 4, 16), 'tether', Decimal('85.722129'), '^NSEI', Decimal('23437.199219'))
(datetime.date(2025, 4, 17), 'bitcoin', Decimal('7201187.297551'), '^GSPC', Decimal('5282.700195'))
(datetime.date(2025, 4, 17), 'bitcoin', Decimal('7201187.297551'), '^IXIC', Decimal('16286.450195'))
(datetime.date(2025, 4, 17), 'bitcoin', Decimal('7201187.297551'), '^NSEI', Decimal('23851.650391'))
(datetime.date(2025, 4, 17), 'ethereum', Decimal('135084.250075'), '^GSPC', Decimal('5282.700195'))
(datetime.date(2025, 4, 17), 'ethereum', Decimal('135084.250075'), '^IXIC', Decimal('16286.450195'))
(datetime.date(2025, 4, 17), 'ethereum', Decimal('135084.250075'), '^NSEI', Decimal('23851.650391'))
(datetime.date(2025, 4, 17), 'tether', Decimal('85.620824'), '^GSPC', Decimal('5282.700195'))
(datetime.date(2025, 4, 17), 'tether', Decimal('85.620824'), '^IXIC', Decimal('16286.450195'))
(datetime.date(2025, 4, 17), 'tether', Decimal('85.620824'), '^NSEI', Decimal('23851.650391'))
(datetime.date(2025, 4, 21), 'bitcoin', Decimal('7263849.726469'), '^GSPC', Decimal('5158.200195'))
(datetime.date(2025, 4, 21), 'bitcoin', Decimal('7263849.726469'), '^IXIC', Decimal('15870.900391'))
(datetime.date(2025, 4, 21), 'bitcoin', Decimal('7263849.726469'), '^NSEI', Decimal('24125.550781'))
(datetime.date(2025, 4, 21), 'ethereum', Decimal('135372.221202'), '^GSPC', Decimal('5158.200195'))
(datetime.date(2025, 4, 21), 'ethereum', Decimal('135372.221202'), '^IXIC', Decimal('15870.900391'))
(datetime.date(2025, 4, 21), 'ethereum', Decimal('135372.221202'), '^NSEI', Decimal('24125.550781'))
(datetime.date(2025, 4, 21), 'tether', Decimal('85.381519'), '^GSPC', Decimal('5158.200195'))
(datetime.date(2025, 4, 21), 'tether', Decimal('85.381519'), '^IXIC', Decimal('15870.900391'))
(datetime.date(2025, 4, 21), 'tether', Decimal('85.381519'), '^NSEI', Decimal('24125.550781'))
(datetime.date(2025, 4, 22), 'bitcoin', Decimal('7447341.987487'), '^GSPC', Decimal('5287.759766'))
(datetime.date(2025, 4, 22), 'bitcoin', Decimal('7447341.987487'), '^IXIC', Decimal('16300.419922'))
(datetime.date(2025, 4, 22), 'bitcoin', Decimal('7447341.987487'), '^NSEI', Decimal('24167.250000'))
(datetime.date(2025, 4, 22), 'ethereum', Decimal('134334.008185'), '^GSPC', Decimal('5287.759766'))
(datetime.date(2025, 4, 22), 'ethereum', Decimal('134334.008185'), '^IXIC', Decimal('16300.419922'))
(datetime.date(2025, 4, 22), 'ethereum', Decimal('134334.008185'), '^NSEI', Decimal('24167.250000'))
(datetime.date(2025, 4, 22), 'tether', Decimal('85.159972'), '^GSPC', Decimal('5287.759766'))
(datetime.date(2025, 4, 22), 'tether', Decimal('85.159972'), '^IXIC', Decimal('16300.419922'))
(datetime.date(2025, 4, 22), 'tether', Decimal('85.159972'), '^NSEI', Decimal('24167.250000'))
(datetime.date(2025, 4, 23), 'bitcoin', Decimal('7975735.892698'), '^GSPC', Decimal('5375.859863'))
(datetime.date(2025, 4, 23), 'bitcoin', Decimal('7975735.892698'), '^IXIC', Decimal('16708.050781'))
(datetime.date(2025, 4, 23), 'bitcoin', Decimal('7975735.892698'), '^NSEI', Decimal('24328.949219'))
(datetime.date(2025, 4, 23), 'ethereum', Decimal('149984.444802'), '^GSPC', Decimal('5375.859863'))
(datetime.date(2025, 4, 23), 'ethereum', Decimal('149984.444802'), '^IXIC', Decimal('16708.050781'))
(datetime.date(2025, 4, 23), 'ethereum', Decimal('149984.444802'), '^NSEI', Decimal('24328.949219'))
(datetime.date(2025, 4, 23), 'tether', Decimal('85.269284'), '^GSPC', Decimal('5375.859863'))
(datetime.date(2025, 4, 23), 'tether', Decimal('85.269284'), '^IXIC', Decimal('16708.050781'))
(datetime.date(2025, 4, 23), 'tether', Decimal('85.269284'), '^NSEI', Decimal('24328.949219'))
(datetime.date(2025, 4, 24), 'bitcoin', Decimal('8003280.213214'), '^GSPC', Decimal('5484.770020'))
(datetime.date(2025, 4, 24), 'bitcoin', Decimal('8003280.213214'), '^IXIC', Decimal('17166.039063'))
(datetime.date(2025, 4, 24), 'bitcoin', Decimal('8003280.213214'), '^NSEI', Decimal('24246.699219'))
(datetime.date(2025, 4, 24), 'ethereum', Decimal('153384.691226'), '^GSPC', Decimal('5484.770020'))
(datetime.date(2025, 4, 24), 'ethereum', Decimal('153384.691226'), '^IXIC', Decimal('17166.039063'))
(datetime.date(2025, 4, 24), 'ethereum', Decimal('153384.691226'), '^NSEI', Decimal('24246.699219'))
(datetime.date(2025, 4, 24), 'tether', Decimal('85.533091'), '^GSPC', Decimal('5484.770020'))
(datetime.date(2025, 4, 24), 'tether', Decimal('85.533091'), '^IXIC', Decimal('17166.039063'))
(datetime.date(2025, 4, 24), 'tether', Decimal('85.533091'), '^NSEI', Decimal('24246.699219'))
(datetime.date(2025, 4, 25), 'bitcoin', Decimal('8000169.783417'), '^GSPC', Decimal('5525.209961'))
(datetime.date(2025, 4, 25), 'bitcoin', Decimal('8000169.783417'), '^IXIC', Decimal('17382.939453'))
(datetime.date(2025, 4, 25), 'bitcoin', Decimal('8000169.783417'), '^NSEI', Decimal('24039.349609'))
(datetime.date(2025, 4, 25), 'ethereum', Decimal('150793.822639'), '^GSPC', Decimal('5525.209961'))
(datetime.date(2025, 4, 25), 'ethereum', Decimal('150793.822639'), '^IXIC', Decimal('17382.939453'))
(datetime.date(2025, 4, 25), 'ethereum', Decimal('150793.822639'), '^NSEI', Decimal('24039.349609'))
(datetime.date(2025, 4, 25), 'tether', Decimal('85.256652'), '^GSPC', Decimal('5525.209961'))
(datetime.date(2025, 4, 25), 'tether', Decimal('85.256652'), '^IXIC', Decimal('17382.939453'))
(datetime.date(2025, 4, 25), 'tether', Decimal('85.256652'), '^NSEI', Decimal('24039.349609'))
(datetime.date(2025, 4, 28), 'bitcoin', Decimal('8009924.381134'), '^GSPC', Decimal('5528.750000'))
(datetime.date(2025, 4, 28), 'bitcoin', Decimal('8009924.381134'), '^IXIC', Decimal('17366.130859'))
(datetime.date(2025, 4, 28), 'bitcoin', Decimal('8009924.381134'), '^NSEI', Decimal('24328.500000'))
(datetime.date(2025, 4, 28), 'ethereum', Decimal('153154.647160'), '^GSPC', Decimal('5528.750000'))
(datetime.date(2025, 4, 28), 'ethereum', Decimal('153154.647160'), '^IXIC', Decimal('17366.130859'))
(datetime.date(2025, 4, 28), 'ethereum', Decimal('153154.647160'), '^NSEI', Decimal('24328.500000'))
(datetime.date(2025, 4, 28), 'tether', Decimal('85.413648'), '^GSPC', Decimal('5528.750000'))
(datetime.date(2025, 4, 28), 'tether', Decimal('85.413648'), '^IXIC', Decimal('17366.130859'))
(datetime.date(2025, 4, 28), 'tether', Decimal('85.413648'), '^NSEI', Decimal('24328.500000'))
(datetime.date(2025, 4, 29), 'bitcoin', Decimal('8092853.390806'), '^GSPC', Decimal('5560.830078'))
(datetime.date(2025, 4, 29), 'bitcoin', Decimal('8092853.390806'), '^IXIC', Decimal('17461.320313'))
(datetime.date(2025, 4, 29), 'bitcoin', Decimal('8092853.390806'), '^NSEI', Decimal('24335.949219'))
(datetime.date(2025, 4, 29), 'ethereum', Decimal('153246.471992'), '^GSPC', Decimal('5560.830078'))
(datetime.date(2025, 4, 29), 'ethereum', Decimal('153246.471992'), '^IXIC', Decimal('17461.320313'))
(datetime.date(2025, 4, 29), 'ethereum', Decimal('153246.471992'), '^NSEI', Decimal('24335.949219'))
(datetime.date(2025, 4, 29), 'tether', Decimal('85.179249'), '^GSPC', Decimal('5560.830078'))
(datetime.date(2025, 4, 29), 'tether', Decimal('85.179249'), '^IXIC', Decimal('17461.320313'))
(datetime.date(2025, 4, 29), 'tether', Decimal('85.179249'), '^NSEI', Decimal('24335.949219'))
(datetime.date(2025, 4, 30), 'bitcoin', Decimal('8027696.597799'), '^GSPC', Decimal('5569.060059'))
(datetime.date(2025, 4, 30), 'bitcoin', Decimal('8027696.597799'), '^IXIC', Decimal('17446.339844'))
(datetime.date(2025, 4, 30), 'bitcoin', Decimal('8027696.597799'), '^NSEI', Decimal('24334.199219'))
(datetime.date(2025, 4, 30), 'ethereum', Decimal('153045.868306'), '^GSPC', Decimal('5569.060059'))
(datetime.date(2025, 4, 30), 'ethereum', Decimal('153045.868306'), '^IXIC', Decimal('17446.339844'))
(datetime.date(2025, 4, 30), 'ethereum', Decimal('153045.868306'), '^NSEI', Decimal('24334.199219'))
(datetime.date(2025, 4, 30), 'tether', Decimal('85.191867'), '^GSPC', Decimal('5569.060059'))
(datetime.date(2025, 4, 30), 'tether', Decimal('85.191867'), '^IXIC', Decimal('17446.339844'))
(datetime.date(2025, 4, 30), 'tether', Decimal('85.191867'), '^NSEI', Decimal('24334.199219'))
(datetime.date(2025, 5, 1), 'bitcoin', Decimal('7968688.759781'), '^GSPC', Decimal('5604.140137'))
(datetime.date(2025, 5, 1), 'bitcoin', Decimal('7968688.759781'), '^IXIC', Decimal('17710.740234'))
(datetime.date(2025, 5, 1), 'bitcoin', Decimal('7968688.759781'), '^NSEI', None)
(datetime.date(2025, 5, 1), 'ethereum', Decimal('151706.989211'), '^GSPC', Decimal('5604.140137'))
(datetime.date(2025, 5, 1), 'ethereum', Decimal('151706.989211'), '^IXIC', Decimal('17710.740234'))
(datetime.date(2025, 5, 1), 'ethereum', Decimal('151706.989211'), '^NSEI', None)
(datetime.date(2025, 5, 1), 'tether', Decimal('84.568425'), '^GSPC', Decimal('5604.140137'))
(datetime.date(2025, 5, 1), 'tether', Decimal('84.568425'), '^IXIC', Decimal('17710.740234'))
(datetime.date(2025, 5, 1), 'tether', Decimal('84.568425'), '^NSEI', None)
(datetime.date(2025, 5, 2), 'bitcoin', Decimal('8167058.515488'), '^GSPC', Decimal('5686.669922'))
(datetime.date(2025, 5, 2), 'bitcoin', Decimal('8167058.515488'), '^IXIC', Decimal('17977.730469'))
(datetime.date(2025, 5, 2), 'bitcoin', Decimal('8167058.515488'), '^NSEI', Decimal('24346.699219'))
(datetime.date(2025, 5, 2), 'ethereum', Decimal('155745.169241'), '^GSPC', Decimal('5686.669922'))
(datetime.date(2025, 5, 2), 'ethereum', Decimal('155745.169241'), '^IXIC', Decimal('17977.730469'))
(datetime.date(2025, 5, 2), 'ethereum', Decimal('155745.169241'), '^NSEI', Decimal('24346.699219'))
(datetime.date(2025, 5, 2), 'tether', Decimal('84.721437'), '^GSPC', Decimal('5686.669922'))
(datetime.date(2025, 5, 2), 'tether', Decimal('84.721437'), '^IXIC', Decimal('17977.730469'))
(datetime.date(2025, 5, 2), 'tether', Decimal('84.721437'), '^NSEI', Decimal('24346.699219'))
(datetime.date(2025, 5, 5), 'bitcoin', Decimal('7973099.086450'), '^GSPC', Decimal('5650.379883'))
(datetime.date(2025, 5, 5), 'bitcoin', Decimal('7973099.086450'), '^IXIC', Decimal('17844.240234'))
(datetime.date(2025, 5, 5), 'bitcoin', Decimal('7973099.086450'), '^NSEI', Decimal('24461.150391'))
(datetime.date(2025, 5, 5), 'ethereum', Decimal('152837.106066'), '^GSPC', Decimal('5650.379883'))
(datetime.date(2025, 5, 5), 'ethereum', Decimal('152837.106066'), '^IXIC', Decimal('17844.240234'))
(datetime.date(2025, 5, 5), 'ethereum', Decimal('152837.106066'), '^NSEI', Decimal('24461.150391'))
(datetime.date(2025, 5, 5), 'tether', Decimal('84.529781'), '^GSPC', Decimal('5650.379883'))
(datetime.date(2025, 5, 5), 'tether', Decimal('84.529781'), '^IXIC', Decimal('17844.240234'))
(datetime.date(2025, 5, 5), 'tether', Decimal('84.529781'), '^NSEI', Decimal('24461.150391'))
(datetime.date(2025, 5, 6), 'bitcoin', Decimal('7980688.008703'), '^GSPC', Decimal('5606.910156'))
(datetime.date(2025, 5, 6), 'bitcoin', Decimal('7980688.008703'), '^IXIC', Decimal('17689.660156'))
(datetime.date(2025, 5, 6), 'bitcoin', Decimal('7980688.008703'), '^NSEI', Decimal('24379.599609'))
(datetime.date(2025, 5, 6), 'ethereum', Decimal('153282.693897'), '^GSPC', Decimal('5606.910156'))
(datetime.date(2025, 5, 6), 'ethereum', Decimal('153282.693897'), '^IXIC', Decimal('17689.660156'))
(datetime.date(2025, 5, 6), 'ethereum', Decimal('153282.693897'), '^NSEI', Decimal('24379.599609'))
(datetime.date(2025, 5, 6), 'tether', Decimal('84.214175'), '^GSPC', Decimal('5606.910156'))
(datetime.date(2025, 5, 6), 'tether', Decimal('84.214175'), '^IXIC', Decimal('17689.660156'))
(datetime.date(2025, 5, 6), 'tether', Decimal('84.214175'), '^NSEI', Decimal('24379.599609'))
(datetime.date(2025, 5, 7), 'bitcoin', Decimal('8207545.052482'), '^GSPC', Decimal('5631.279785'))
(datetime.date(2025, 5, 7), 'bitcoin', Decimal('8207545.052482'), '^IXIC', Decimal('17738.160156'))
(datetime.date(2025, 5, 7), 'bitcoin', Decimal('8207545.052482'), '^NSEI', Decimal('24414.400391'))
(datetime.date(2025, 5, 7), 'ethereum', Decimal('153903.860522'), '^GSPC', Decimal('5631.279785'))
(datetime.date(2025, 5, 7), 'ethereum', Decimal('153903.860522'), '^IXIC', Decimal('17738.160156'))
(datetime.date(2025, 5, 7), 'ethereum', Decimal('153903.860522'), '^NSEI', Decimal('24414.400391'))
(datetime.date(2025, 5, 7), 'tether', Decimal('84.735990'), '^GSPC', Decimal('5631.279785'))
(datetime.date(2025, 5, 7), 'tether', Decimal('84.735990'), '^IXIC', Decimal('17738.160156'))
(datetime.date(2025, 5, 7), 'tether', Decimal('84.735990'), '^NSEI', Decimal('24414.400391'))
(datetime.date(2025, 5, 8), 'bitcoin', Decimal('8229539.783984'), '^GSPC', Decimal('5663.939941'))
(datetime.date(2025, 5, 8), 'bitcoin', Decimal('8229539.783984'), '^IXIC', Decimal('17928.140625'))
(datetime.date(2025, 5, 8), 'bitcoin', Decimal('8229539.783984'), '^NSEI', Decimal('24273.800781'))
(datetime.date(2025, 5, 8), 'ethereum', Decimal('153546.465434'), '^GSPC', Decimal('5663.939941'))
(datetime.date(2025, 5, 8), 'ethereum', Decimal('153546.465434'), '^IXIC', Decimal('17928.140625'))
(datetime.date(2025, 5, 8), 'ethereum', Decimal('153546.465434'), '^NSEI', Decimal('24273.800781'))
(datetime.date(2025, 5, 8), 'tether', Decimal('84.832827'), '^GSPC', Decimal('5663.939941'))
(datetime.date(2025, 5, 8), 'tether', Decimal('84.832827'), '^IXIC', Decimal('17928.140625'))
(datetime.date(2025, 5, 8), 'tether', Decimal('84.832827'), '^NSEI', Decimal('24273.800781'))
(datetime.date(2025, 5, 9), 'bitcoin', Decimal('8868161.595114'), '^GSPC', Decimal('5659.910156'))
(datetime.date(2025, 5, 9), 'bitcoin', Decimal('8868161.595114'), '^IXIC', Decimal('17928.919922'))
(datetime.date(2025, 5, 9), 'bitcoin', Decimal('8868161.595114'), '^NSEI', Decimal('24008.000000'))
(datetime.date(2025, 5, 9), 'ethereum', Decimal('189067.053860'), '^GSPC', Decimal('5659.910156'))
(datetime.date(2025, 5, 9), 'ethereum', Decimal('189067.053860'), '^IXIC', Decimal('17928.919922'))
(datetime.date(2025, 5, 9), 'ethereum', Decimal('189067.053860'), '^NSEI', Decimal('24008.000000'))
(datetime.date(2025, 5, 9), 'tether', Decimal('86.029149'), '^GSPC', Decimal('5659.910156'))
(datetime.date(2025, 5, 9), 'tether', Decimal('86.029149'), '^IXIC', Decimal('17928.919922'))
(datetime.date(2025, 5, 9), 'tether', Decimal('86.029149'), '^NSEI', Decimal('24008.000000'))
(datetime.date(2025, 5, 12), 'bitcoin', Decimal('8882429.185762'), '^GSPC', Decimal('5844.189941'))
(datetime.date(2025, 5, 12), 'bitcoin', Decimal('8882429.185762'), '^IXIC', Decimal('18708.339844'))
(datetime.date(2025, 5, 12), 'bitcoin', Decimal('8882429.185762'), '^NSEI', Decimal('24924.699219'))
(datetime.date(2025, 5, 12), 'ethereum', Decimal('214170.100120'), '^GSPC', Decimal('5844.189941'))
(datetime.date(2025, 5, 12), 'ethereum', Decimal('214170.100120'), '^IXIC', Decimal('18708.339844'))
(datetime.date(2025, 5, 12), 'ethereum', Decimal('214170.100120'), '^NSEI', Decimal('24924.699219'))
(datetime.date(2025, 5, 12), 'tether', Decimal('85.428990'), '^GSPC', Decimal('5844.189941'))
(datetime.date(2025, 5, 12), 'tether', Decimal('85.428990'), '^IXIC', Decimal('18708.339844'))
(datetime.date(2025, 5, 12), 'tether', Decimal('85.428990'), '^NSEI', Decimal('24924.699219'))
(datetime.date(2025, 5, 13), 'bitcoin', Decimal('8739740.641206'), '^GSPC', Decimal('5886.549805'))
(datetime.date(2025, 5, 13), 'bitcoin', Decimal('8739740.641206'), '^IXIC', Decimal('19010.089844'))
(datetime.date(2025, 5, 13), 'bitcoin', Decimal('8739740.641206'), '^NSEI', Decimal('24578.349609'))
(datetime.date(2025, 5, 13), 'ethereum', Decimal('211740.195869'), '^GSPC', Decimal('5886.549805'))
(datetime.date(2025, 5, 13), 'ethereum', Decimal('211740.195869'), '^IXIC', Decimal('19010.089844'))
(datetime.date(2025, 5, 13), 'ethereum', Decimal('211740.195869'), '^NSEI', Decimal('24578.349609'))
(datetime.date(2025, 5, 13), 'tether', Decimal('84.956521'), '^GSPC', Decimal('5886.549805'))
(datetime.date(2025, 5, 13), 'tether', Decimal('84.956521'), '^IXIC', Decimal('19010.089844'))
(datetime.date(2025, 5, 13), 'tether', Decimal('84.956521'), '^NSEI', Decimal('24578.349609'))
(datetime.date(2025, 5, 14), 'bitcoin', Decimal('8860925.913889'), '^GSPC', Decimal('5892.580078'))
(datetime.date(2025, 5, 14), 'bitcoin', Decimal('8860925.913889'), '^IXIC', Decimal('19146.810547'))
(datetime.date(2025, 5, 14), 'bitcoin', Decimal('8860925.913889'), '^NSEI', Decimal('24666.900391'))
(datetime.date(2025, 5, 14), 'ethereum', Decimal('227649.060175'), '^GSPC', Decimal('5892.580078'))
(datetime.date(2025, 5, 14), 'ethereum', Decimal('227649.060175'), '^IXIC', Decimal('19146.810547'))
(datetime.date(2025, 5, 14), 'ethereum', Decimal('227649.060175'), '^NSEI', Decimal('24666.900391'))
(datetime.date(2025, 5, 14), 'tether', Decimal('85.061564'), '^GSPC', Decimal('5892.580078'))
(datetime.date(2025, 5, 14), 'tether', Decimal('85.061564'), '^IXIC', Decimal('19146.810547'))
(datetime.date(2025, 5, 14), 'tether', Decimal('85.061564'), '^NSEI', Decimal('24666.900391'))
(datetime.date(2025, 5, 15), 'bitcoin', Decimal('8854656.259617'), '^GSPC', Decimal('5916.930176'))
(datetime.date(2025, 5, 15), 'bitcoin', Decimal('8854656.259617'), '^IXIC', Decimal('19112.320313'))
(datetime.date(2025, 5, 15), 'bitcoin', Decimal('8854656.259617'), '^NSEI', Decimal('25062.099609'))
(datetime.date(2025, 5, 15), 'ethereum', Decimal('222550.861260'), '^GSPC', Decimal('5916.930176'))
(datetime.date(2025, 5, 15), 'ethereum', Decimal('222550.861260'), '^IXIC', Decimal('19112.320313'))
(datetime.date(2025, 5, 15), 'ethereum', Decimal('222550.861260'), '^NSEI', Decimal('25062.099609'))
(datetime.date(2025, 5, 15), 'tether', Decimal('85.488237'), '^GSPC', Decimal('5916.930176'))
(datetime.date(2025, 5, 15), 'tether', Decimal('85.488237'), '^IXIC', Decimal('19112.320313'))
(datetime.date(2025, 5, 15), 'tether', Decimal('85.488237'), '^NSEI', Decimal('25062.099609'))
(datetime.date(2025, 5, 16), 'bitcoin', Decimal('8861418.050018'), '^GSPC', Decimal('5958.379883'))
(datetime.date(2025, 5, 16), 'bitcoin', Decimal('8861418.050018'), '^IXIC', Decimal('19211.099609'))
(datetime.date(2025, 5, 16), 'bitcoin', Decimal('8861418.050018'), '^NSEI', Decimal('25019.800781'))
(datetime.date(2025, 5, 16), 'ethereum', Decimal('217226.914605'), '^GSPC', Decimal('5958.379883'))
(datetime.date(2025, 5, 16), 'ethereum', Decimal('217226.914605'), '^IXIC', Decimal('19211.099609'))

In [22]:
#Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison
cursor.execute("""
SELECT 
    cp.date,

    -- Bitcoin
    cp.price_inr AS bitcoin_price,

    -- Stock (S&P 500)
    sp.close AS stock_price,

    -- Oil
    op.price_inr AS oil_price

FROM crypto_prices cp

-- Join stock data
JOIN stock_prices sp 
ON cp.date = sp.date

-- Join oil data
JOIN oil_prices op 
ON cp.date = op.date

-- Filter Bitcoin
WHERE cp.coin_id = 'bitcoin'

-- Choose stock index (you can change)
AND sp.ticker = '^GSPC'

-- Sort for daily comparison
ORDER BY cp.date
""")

data = cursor.fetchall()

for row in data:
    print(row)

(datetime.date(2025, 4, 15), Decimal('7271599.950977'), Decimal('5396.629883'), Decimal('5124.420000'))
(datetime.date(2025, 4, 16), Decimal('7171572.949307'), Decimal('5275.700195'), Decimal('5219.040000'))
(datetime.date(2025, 4, 17), Decimal('7201187.297551'), Decimal('5282.700195'), Decimal('5400.810000'))
(datetime.date(2025, 4, 21), Decimal('7263849.726469'), Decimal('5158.200195'), Decimal('5268.840000'))
(datetime.date(2025, 4, 22), Decimal('7447341.987487'), Decimal('5287.759766'), Decimal('5361.800000'))
(datetime.date(2025, 4, 23), Decimal('7975735.892698'), Decimal('5375.859863'), Decimal('5199.120000'))
(datetime.date(2025, 4, 24), Decimal('8003280.213214'), Decimal('5484.770020'), Decimal('5274.650000'))
(datetime.date(2025, 4, 25), Decimal('8000169.783417'), Decimal('5525.209961'), Decimal('5299.550000'))
(datetime.date(2025, 4, 28), Decimal('8009924.381134'), Decimal('5528.750000'), Decimal('5253.900000'))
(datetime.date(2025, 4, 29), Decimal('8092853.390806'), Decimal('5560.830078'), Decimal('5132.720000'))
(datetime.date(2025, 4, 30), Decimal('8027696.597799'), Decimal('5569.060059'), Decimal('4942.650000'))
(datetime.date(2025, 5, 1), Decimal('7968688.759781'), Decimal('5604.140137'), Decimal('5028.970000'))
(datetime.date(2025, 5, 2), Decimal('8167058.515488'), Decimal('5686.669922'), Decimal('4952.610000'))
(datetime.date(2025, 5, 5), Decimal('7973099.086450'), Decimal('5650.379883'), Decimal('4855.500000'))
(datetime.date(2025, 5, 6), Decimal('7980688.008703'), Decimal('5606.910156'), Decimal('5014.860000'))
(datetime.date(2025, 5, 7), Decimal('8207545.052482'), Decimal('5631.279785'), Decimal('4931.860000'))
(datetime.date(2025, 5, 8), Decimal('8229539.783984'), Decimal('5663.939941'), Decimal('5083.750000'))
(datetime.date(2025, 5, 9), Decimal('8868161.595114'), Decimal('5659.910156'), Decimal('5176.710000'))
(datetime.date(2025, 5, 12), Decimal('8882429.185762'), Decimal('5844.189941'), Decimal('5255.560000'))
(datetime.date(2025, 5, 13), Decimal('8739740.641206'), Decimal('5886.549805'), Decimal('5398.320000'))
(datetime.date(2025, 5, 14), Decimal('8860925.913889'), Decimal('5892.580078'), Decimal('5351.840000'))
(datetime.date(2025, 5, 15), Decimal('8854656.259617'), Decimal('5916.930176'), Decimal('5231.490000'))
(datetime.date(2025, 5, 16), Decimal('8861418.050018'), Decimal('5958.379883'), Decimal('5298.720000'))
(datetime.date(2025, 5, 19), Decimal('9065676.354330'), Decimal('5963.600098'), Decimal('5310.340000'))
(datetime.date(2025, 5, 20), Decimal('9017978.281234'), Decimal('5940.459961'), Decimal('5309.510000'))
(datetime.date(2025, 5, 21), Decimal('9134061.037906'), Decimal('5844.609863'), Decimal('5223.190000'))
(datetime.date(2025, 5, 22), Decimal('9387459.456661'), Decimal('5842.009766'), Decimal('5191.650000'))
(datetime.date(2025, 5, 23), Decimal('9591418.421810'), Decimal('5802.819824'), Decimal('5219.870000'))
(datetime.date(2025, 5, 27), Decimal('9314436.685236'), Decimal('5921.540039'), Decimal('5113.630000'))
(datetime.date(2025, 5, 28), Decimal('9310175.102672'), Decimal('5888.549805'), Decimal('5190.820000'))
(datetime.date(2025, 5, 29), Decimal('9208280.990680'), Decimal('5912.169922'), Decimal('5117.780000'))
(datetime.date(2025, 5, 30), Decimal('9026592.666677'), Decimal('5911.689941'), Decimal('5101.180000'))
(datetime.date(2025, 6, 2), Decimal('9040802.274014'), Decimal('5935.939941'), Decimal('5251.410000'))
(datetime.date(2025, 6, 3), Decimal('9038740.617012'), Decimal('5970.370117'), Decimal('5320.300000'))
(datetime.date(2025, 6, 4), Decimal('9036688.899610'), Decimal('5970.810059'), Decimal('5276.310000'))
(datetime.date(2025, 6, 5), Decimal('9003749.459209'), Decimal('5939.299805'), Decimal('5316.980000'))
(datetime.date(2025, 6, 6), Decimal('8729536.730078'), Decimal('6000.359863'), Decimal('5419.900000'))
(datetime.date(2025, 6, 9), Decimal('9066867.468852'), Decimal('6005.879883'), Decimal('5477.170000'))
(datetime.date(2025, 6, 10), Decimal('9455619.179044'), Decimal('6038.810059'), Decimal('5449.780000'))
(datetime.date(2025, 6, 11), Decimal('9440056.689266'), Decimal('6022.240234'), Decimal('5719.530000'))
(datetime.date(2025, 6, 12), Decimal('9288882.881869'), Decimal('6045.259766'), Decimal('5704.590000'))
(datetime.date(2025, 6, 13), Decimal('9081227.025134'), Decimal('5976.970215'), Decimal('6128.720000'))
(datetime.date(2025, 6, 16), Decimal('9090411.274773'), Decimal('6033.109863'), Decimal('6019.990000'))
(datetime.date(2025, 6, 17), Decimal('9208980.453923'), Decimal('5982.720215'), Decimal('6276.460000'))
(datetime.date(2025, 6, 18), Decimal('9039952.955659'), Decimal('5980.870117'), Decimal('6298.870000'))
(datetime.date(2025, 6, 20), Decimal('9080584.318377'), Decimal('5967.839844'), Decimal('6284.760000'))
(datetime.date(2025, 6, 23), Decimal('8731873.284684'), Decimal('6025.169922'), Decimal('5756.880000'))
(datetime.date(2025, 6, 24), Decimal('9111429.945371'), Decimal('6092.180176'), Decimal('5432.350000'))
(datetime.date(2025, 6, 25), Decimal('9111165.386620'), Decimal('6092.160156'), Decimal('5476.340000'))
(datetime.date(2025, 6, 26), Decimal('9223086.808659'), Decimal('6141.020020'), Decimal('5514.520000'))
(datetime.date(2025, 6, 27), Decimal('9165684.099752'), Decimal('6173.069824'), Decimal('5532.780000'))
(datetime.date(2025, 6, 30), Decimal('9263092.465182'), Decimal('6204.950195'), Decimal('5502.900000'))
(datetime.date(2025, 7, 1), Decimal('9181709.414668'), Decimal('6198.009766'), Decimal('5531.120000'))
(datetime.date(2025, 7, 2), Decimal('9054321.250570'), Decimal('6227.419922'), Decimal('5698.780000'))
(datetime.date(2025, 7, 3), Decimal('9325640.339018'), Decimal('6279.350098'), Decimal('5654.790000'))
(datetime.date(2025, 7, 7), Decimal('9337523.923074'), Decimal('6229.979980'), Decimal('5740.280000'))
(datetime.date(2025, 7, 8), Decimal('9302203.177317'), Decimal('6225.520020'), Decimal('5772.650000'))
(datetime.date(2025, 7, 9), Decimal('9338122.035801'), Decimal('6263.259766'), Decimal('5777.630000'))
(datetime.date(2025, 7, 10), Decimal('9541743.483381'), Decimal('6280.459961'), Decimal('5625.740000'))
(datetime.date(2025, 7, 11), Decimal('9934947.612549'), Decimal('6259.750000'), Decimal('5779.290000'))
(datetime.date(2025, 7, 14), Decimal('10222853.345055'), Decimal('6268.560059'), Decimal('5659.770000'))
(datetime.date(2025, 7, 15), Decimal('10301939.218478'), Decimal('6243.759766'), Decimal('5624.080000'))
(datetime.date(2025, 7, 16), Decimal('10119542.204331'), Decimal('6263.700195'), Decimal('5571.790000'))
(datetime.date(2025, 7, 17), Decimal('10198739.393321'), Decimal('6297.359863'), Decimal('5707.080000'))
(datetime.date(2025, 7, 18), Decimal('10277885.478397'), Decimal('6296.790039'), Decimal('5687.990000'))
(datetime.date(2025, 7, 21), Decimal('10101549.352407'), Decimal('6305.600098'), Decimal('5676.370000'))
(datetime.date(2025, 7, 22), Decimal('10136533.758092'), Decimal('6309.620117'), Decimal('5607.480000'))
(datetime.date(2025, 7, 23), Decimal('10357349.266440'), Decimal('6358.910156'), Decimal('5482.150000'))
(datetime.date(2025, 7, 24), Decimal('10249425.749007'), Decimal('6363.350098'), Decimal('5574.280000'))
(datetime.date(2025, 7, 25), Decimal('10229427.683390'), Decimal('6388.640137'), Decimal('5509.540000'))
(datetime.date(2025, 7, 28), Decimal('10330494.375552'), Decimal('6389.770020'), Decimal('5628.230000'))
(datetime.date(2025, 7, 29), Decimal('10240072.841856'), Decimal('6370.859863'), Decimal('5832.410000'))
(datetime.date(2025, 7, 30), Decimal('10260715.669243'), Decimal('6362.899902'), Decimal('5900.470000'))
(datetime.date(2025, 7, 31), Decimal('10330510.927891'), Decimal('6339.390137'), Decimal('5839.880000'))
(datetime.date(2025, 8, 1), Decimal('10122552.718401'), Decimal('6238.009766'), Decimal('5676.370000'))
(datetime.date(2025, 8, 4), Decimal('9963363.104407'), Decimal('6329.939941'), Decimal('5588.390000'))
(datetime.date(2025, 8, 5), Decimal('10119947.866363'), Decimal('6299.189941'), Decimal('5494.600000'))
(datetime.date(2025, 8, 6), Decimal('10011721.550657'), Decimal('6345.060059'), Decimal('5426.540000'))
(datetime.date(2025, 8, 7), Decimal('10094655.435390'), Decimal('6340.000000'), Decimal('5386.700000'))
(datetime.date(2025, 8, 8), Decimal('10270107.263259'), Decimal('6389.450195'), Decimal('5390.020000'))
(datetime.date(2025, 8, 11), Decimal('10434491.300113'), Decimal('6373.450195'), Decimal('5397.490000'))
(datetime.date(2025, 8, 12), Decimal('10412275.449239'), Decimal('6445.759766'), Decimal('5330.260000'))
(datetime.date(2025, 8, 13), Decimal('10529495.638104'), Decimal('6466.580078'), Decimal('5285.440000'))
(datetime.date(2025, 8, 14), Decimal('10805439.783697'), Decimal('6468.540039'), Decimal('5394.170000'))
(datetime.date(2025, 8, 15), Decimal('10383230.847886'), Decimal('6449.799805'), Decimal('5293.740000'))
(datetime.date(2025, 8, 18), Decimal('10286533.101170'), Decimal('6449.149902'), Decimal('5354.330000'))
(datetime.date(2025, 8, 19), Decimal('10148644.242275'), Decimal('6411.370117'), Decimal('5260.540000'))
(datetime.date(2025, 8, 20), Decimal('9819786.419050'), Decimal('6395.779785'), Decimal('5327.770000'))
(datetime.date(2025, 8, 21), Decimal('9942066.543755'), Decimal('6370.169922'), Decimal('5358.480000'))
(datetime.date(2025, 8, 22), Decimal('9813063.277506'), Decimal('6466.910156'), Decimal('5318.640000'))
(datetime.date(2025, 8, 25), Decimal('9903221.350806'), Decimal('6439.319824'), Decimal('5409.940000'))
(datetime.date(2025, 8, 26), Decimal('9653212.189244'), Decimal('6465.939941'), Decimal('5278.800000'))
(datetime.date(2025, 8, 27), Decimal('9801777.668907'), Decimal('6481.399902'), Decimal('5352.670000'))
(datetime.date(2025, 8, 28), Decimal('9749130.258868'), Decimal('6501.859863'), Decimal('5391.680000'))
(datetime.date(2025, 8, 29), Decimal('9856302.068935'), Decimal('6460.259766'), Decimal('5341.880000'))
(datetime.date(2025, 9, 2), Decimal('9606486.079009'), Decimal('6415.540039'), Decimal('5473.850000'))
(datetime.date(2025, 9, 3), Decimal('9784574.242949'), Decimal('6448.259766'), Decimal('5341.880000'))
(datetime.date(2025, 9, 4), Decimal('9838796.609222'), Decimal('6502.080078'), Decimal('5296.230000'))
(datetime.date(2025, 9, 5), Decimal('9765163.284050'), Decimal('6481.500000'), Decimal('5164.260000'))
(datetime.date(2025, 9, 8), Decimal('9800346.003034'), Decimal('6495.149902'), Decimal('5195.800000'))
(datetime.date(2025, 9, 9), Decimal('9856054.849015'), Decimal('6512.609863'), Decimal('5226.510000'))
(datetime.date(2025, 9, 10), Decimal('9840553.151485'), Decimal('6532.040039'), Decimal('5312.830000'))
(datetime.date(2025, 9, 11), Decimal('10035954.764446'), Decimal('6587.470215'), Decimal('5204.930000'))
(datetime.date(2025, 9, 12), Decimal('10195205.098488'), Decimal('6584.290039'), Decimal('5230.660000'))
(datetime.date(2025, 9, 15), Decimal('10184894.127284'), Decimal('6615.279785'), Decimal('5283.780000'))
(datetime.date(2025, 9, 16), Decimal('10169238.650025'), Decimal('6606.759766'), Decimal('5385.870000'))
(datetime.date(2025, 9, 17), Decimal('10261685.530264'), Decimal('6600.350098'), Decimal('5346.030000'))
(datetime.date(2025, 9, 18), Decimal('10237752.888404'), Decimal('6631.959961'), Decimal('5304.530000'))
(datetime.date(2025, 9, 19), Decimal('10333070.257186'), Decimal('6664.359863'), Decimal('5230.660000'))
(datetime.date(2025, 9, 22), Decimal('10158260.693491'), Decimal('6693.750000'), Decimal('5228.170000'))
(datetime.date(2025, 9, 23), Decimal('9951646.271657'), Decimal('6656.919922'), Decimal('5292.080000'))
(datetime.date(2025, 9, 24), Decimal('9948492.512889'), Decimal('6637.970215'), Decimal('5428.200000'))
(datetime.date(2025, 9, 25), Decimal('10060469.351466'), Decimal('6604.720215'), Decimal('5437.330000'))
(datetime.date(2025, 9, 26), Decimal('9673068.167457'), Decimal('6643.700195'), Decimal('5519.500000'))
(datetime.date(2025, 9, 29), Decimal('9944472.608697'), Decimal('6661.209961'), Decimal('5334.410000'))
(datetime.date(2025, 9, 30), Decimal('10139763.924083'), Decimal('6688.459961'), Decimal('5243.110000'))
(datetime.date(2025, 10, 1), Decimal('10130020.723922'), Decimal('6711.200195'), Decimal('5194.970000'))
(datetime.date(2025, 10, 2), Decimal('10509252.859359'), Decimal('6715.350098'), Decimal('5086.240000'))
(datetime.date(2025, 10, 3), Decimal('10700725.995237'), Decimal('6715.790039'), Decimal('5116.950000'))
(datetime.date(2025, 10, 6), Decimal('10959365.064936'), Decimal('6740.279785'), Decimal('5186.670000'))
(datetime.date(2025, 10, 7), Decimal('11070472.246733'), Decimal('6714.589844'), Decimal('5189.160000'))
(datetime.date(2025, 10, 8), Decimal('10783920.730193'), Decimal('6753.720215'), Decimal('5259.710000'))
(datetime.date(2025, 10, 9), Decimal('10949945.979090'), Decimal('6735.109863'), Decimal('5175.880000'))
(datetime.date(2025, 10, 10), Decimal('10814774.599012'), Decimal('6552.509766'), Decimal('4959.250000'))
(datetime.date(2025, 10, 14), Decimal('10216224.051871'), Decimal('6644.310059'), Decimal('4940.160000'))
(datetime.date(2025, 10, 15), Decimal('10046351.075826'), Decimal('6671.060059'), Decimal('4903.640000'))
(datetime.date(2025, 10, 16), Decimal('9721344.884649'), Decimal('6629.069824'), Decimal('4838.070000'))
(datetime.date(2025, 10, 17), Decimal('9509774.024195'), Decimal('6664.009766'), Decimal('4838.900000'))
(datetime.date(2025, 10, 20), Decimal('9558930.877185'), Decimal('6735.129883'), Decimal('4842.220000'))
(datetime.date(2025, 10, 21), Decimal('9720308.914971'), Decimal('6735.350098'), Decimal('4868.780000'))
(datetime.date(2025, 10, 22), Decimal('9549158.301143'), Decimal('6699.399902'), Decimal('4921.900000'))
(datetime.date(2025, 10, 23), Decimal('9442499.946296'), Decimal('6738.439941'), Decimal('5182.520000'))
(datetime.date(2025, 10, 24), Decimal('9659976.397608'), Decimal('6791.689941'), Decimal('5168.410000'))
(datetime.date(2025, 10, 27), Decimal('10055171.794297'), Decimal('6875.160156'), Decimal('5156.790000'))
(datetime.date(2025, 10, 28), Decimal('10073474.454011'), Decimal('6890.890137'), Decimal('5060.510000'))
(datetime.date(2025, 10, 29), Decimal('9965129.220872'), Decimal('6890.589844'), Decimal('5084.580000'))
(datetime.date(2025, 10, 30), Decimal('9722166.865440'), Decimal('6822.339844'), Decimal('5092.880000'))
(datetime.date(2025, 10, 31), Decimal('9593893.171045'), Decimal('6840.200195'), Decimal('5125.250000'))
(datetime.date(2025, 11, 3), Decimal('9824421.072228'), Decimal('6851.970215'), Decimal('5128.570000'))
(datetime.date(2025, 11, 4), Decimal('9450928.858755'), Decimal('6771.549805'), Decimal('5094.540000'))
(datetime.date(2025, 11, 5), Decimal('9018317.599499'), Decimal('6796.290039'), Decimal('5013.200000'))
(datetime.date(2025, 11, 6), Decimal('9199126.082981'), Decimal('6720.319824'), Decimal('4999.920000'))
(datetime.date(2025, 11, 7), Decimal('8984607.813502'), Decimal('6728.799805'), Decimal('5024.820000'))
(datetime.date(2025, 11, 10), Decimal('9283589.006016'), Decimal('6832.430176'), Decimal('5058.020000'))
(datetime.date(2025, 11, 12), Decimal('9108594.696794'), Decimal('6850.919922'), Decimal('4921.900000'))
(datetime.date(2025, 11, 13), Decimal('8994239.327086'), Decimal('6737.490234'), Decimal('4941.820000'))
(datetime.date(2025, 11, 14), Decimal('8857694.854444'), Decimal('6734.109863'), Decimal('5052.210000'))
(datetime.date(2025, 11, 17), Decimal('8373085.239388'), Decimal('6672.410156'), Decimal('5034.780000'))
(datetime.date(2025, 11, 18), Decimal('8157780.455111'), Decimal('6617.319824'), Decimal('5105.330000'))
(datetime.date(2025, 11, 19), Decimal('8219844.429071'), Decimal('6642.160156'), Decimal('5002.410000'))
(datetime.date(2025, 11, 20), Decimal('8084502.705830'), Decimal('6538.759766'), Decimal('4985.810000'))
(datetime.date(2025, 11, 21), Decimal('7685198.360480'), Decimal('6602.990234'), Decimal('4885.380000'))
(datetime.date(2025, 11, 24), Decimal('7778520.446851'), Decimal('6705.120117'), Decimal('4906.130000'))
(datetime.date(2025, 11, 25), Decimal('7865475.253834'), Decimal('6765.879883'), Decimal('4834.750000'))
(datetime.date(2025, 11, 26), Decimal('7783791.323602'), Decimal('6812.609863'), Decimal('4881.230000'))
(datetime.date(2025, 11, 28), Decimal('8157156.351484'), Decimal('6849.089844'), Decimal('4862.140000'))
(datetime.date(2025, 12, 1), Decimal('8078246.317718'), Decimal('6812.629883'), Decimal('4936.010000'))
(datetime.date(2025, 12, 2), Decimal('7731939.315083'), Decimal('6829.370117'), Decimal('4881.230000'))
(datetime.date(2025, 12, 3), Decimal('8213485.439947'), Decimal('6849.720215'), Decimal('4904.470000'))
(datetime.date(2025, 12, 4), Decimal('8441734.894690'), Decimal('6857.120117'), Decimal('4965.060000'))
(datetime.date(2025, 12, 5), Decimal('8277612.193785'), Decimal('6870.399902'), Decimal('4999.090000'))
(datetime.date(2025, 12, 8), Decimal('8110183.521497'), Decimal('6846.509766'), Decimal('4900.320000'))
(datetime.date(2025, 12, 9), Decimal('8167418.756507'), Decimal('6840.509766'), Decimal('4847.200000'))
(datetime.date(2025, 12, 10), Decimal('8337407.116606'), Decimal('6886.680176'), Decimal('4869.610000'))
(datetime.date(2025, 12, 11), Decimal('8261440.281356'), Decimal('6901.000000'), Decimal('4794.080000'))
(datetime.date(2025, 12, 12), Decimal('8347818.307928'), Decimal('6827.410156'), Decimal('4781.630000'))
(datetime.date(2025, 12, 15), Decimal('7992348.231966'), Decimal('6816.509766'), Decimal('4728.510000'))
(datetime.date(2025, 12, 16), Decimal('7844409.288927'), Decimal('6800.259766'), Decimal('4601.520000'))
(datetime.date(2025, 12, 17), Decimal('7987315.985985'), Decimal('6721.430176'), Decimal('4653.810000'))
(datetime.date(2025, 12, 18), Decimal('7781471.915537'), Decimal('6774.759766'), Decimal('4666.260000'))
(datetime.date(2025, 12, 19), Decimal('7712879.171309'), Decimal('6834.500000'), Decimal('4714.400000'))
(datetime.date(2025, 12, 22), Decimal('7933999.654740'), Decimal('6878.490234'), Decimal('4828.940000'))
(datetime.date(2025, 12, 23), Decimal('7929162.759663'), Decimal('6909.790039'), Decimal('4859.650000'))
(datetime.date(2025, 12, 24), Decimal('7820620.968822'), Decimal('6932.049805'), Decimal('4873.760000'))
(datetime.date(2025, 12, 26), Decimal('7860175.221035'), Decimal('6929.939941'), Decimal('4697.800000'))
(datetime.date(2025, 12, 29), Decimal('7887770.596681'), Decimal('6905.740234'), Decimal('4804.870000'))
(datetime.date(2025, 12, 30), Decimal('7835388.056690'), Decimal('6896.240234'), Decimal('4796.570000'))
(datetime.date(2025, 12, 31), Decimal('7936951.056509'), Decimal('6845.500000'), Decimal('4752.580000'))
(datetime.date(2026, 1, 2), Decimal('7982611.090932'), Decimal('6858.470215'), Decimal('4748.430000'))
(datetime.date(2026, 1, 5), Decimal('8224912.970330'), Decimal('6902.049805'), Decimal('4822.300000'))
(datetime.date(2026, 1, 6), Decimal('8475311.204337'), Decimal('6944.819824'), Decimal('4728.510000'))
(datetime.date(2026, 1, 7), Decimal('8443838.294347'), Decimal('6920.930176'), Decimal('4648.830000'))
(datetime.date(2026, 1, 8), Decimal('8200790.873529'), Decimal('6921.459961'), Decimal('4792.420000'))
(datetime.date(2026, 1, 9), Decimal('8179932.125614'), Decimal('6966.279785'), Decimal('4893.680000'))
(datetime.date(2026, 1, 12), Decimal('8196362.955223'), Decimal('6977.270020'), Decimal('4929.370000'))
(datetime.date(2026, 1, 13), Decimal('8214254.506812'), Decimal('6963.740234'), Decimal('5050.550000'))
(datetime.date(2026, 1, 14), Decimal('8600260.479528'), Decimal('6926.600098'), Decimal('5132.720000'))
(datetime.date(2026, 1, 15), Decimal('8754772.557780'), Decimal('6944.470215'), Decimal('4907.790000'))
(datetime.date(2026, 1, 16), Decimal('8637202.771129'), Decimal('6940.009766'), Decimal('4930.200000'))
(datetime.date(2026, 1, 20), Decimal('8414003.970645'), Decimal('6796.859863'), Decimal('5004.900000'))
(datetime.date(2026, 1, 21), Decimal('8046939.830277'), Decimal('6875.620117'), Decimal('5011.540000'))

In [ ]:
#📊 Streamlit App Structure

In [3]:
!pip install streamlit

Requirement already satisfied: streamlit in D:\guvi\Lib\site-packages (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in D:\guvi\Lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in D:\guvi\Lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in D:\guvi\Lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in D:\guvi\Lib\site-packages (from streamlit) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in D:\guvi\Lib\site-packages (from streamlit) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in D:\guvi\Lib\site-packages (from streamlit) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in D:\guvi\Lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in D:\guvi\Lib\site-packages (from streamlit) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in D:\guvi\Lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in D:\guvi\Lib\site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in D:\guvi\Lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in D:\guvi\Lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in D:\guvi\Lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in D:\guvi\Lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in D:\guvi\Lib\site-packages (from streamlit) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in D:\guvi\Lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in D:\guvi\Lib\site-packages (from streamlit) (6.5.1)
Requirement already satisfied: jinja2 in D:\guvi\Lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in D:\guvi\Lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in D:\guvi\Lib\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)
Requirement already satisfied: colorama in D:\guvi\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in D:\guvi\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in D:\guvi\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\guvi\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in D:\guvi\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in D:\guvi\Lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in D:\guvi\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in D:\guvi\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in D:\guvi\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in D:\guvi\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.1.4)
Requirement already satisfied: attrs>=22.2.0 in D:\guvi\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in D:\guvi\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in D:\guvi\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in D:\guvi\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: six>=1.5 in D:\guvi\Lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in D:\guvi\Lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)

In [2]:
import streamlit as st
!pip install streamlit-option-menu
from streamlit_option_menu import option_menu
import pandas as pd

Requirement already satisfied: streamlit-option-menu in D:\guvi\Lib\site-packages (0.4.0)
Requirement already satisfied: streamlit>=1.36 in D:\guvi\Lib\site-packages (from streamlit-option-menu) (1.45.1)
Requirement already satisfied: altair<6,>=4.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (8.1.8)
Requirement already satisfied: numpy<3,>=1.23 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.1.3)
Requirement already satisfied: packaging<25,>=20 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (24.2)
Requirement already satisfied: pandas<3,>=1.4.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (11.1.0)
Requirement already satisfied: protobuf<7,>=3.20 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (2.32.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (4.0.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (3.1.43)
Requirement already satisfied: tornado<7,>=6.0.3 in D:\guvi\Lib\site-packages (from streamlit>=1.36->streamlit-option-menu) (6.5.1)
Requirement already satisfied: jinja2 in D:\guvi\Lib\site-packages (from altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in D:\guvi\Lib\site-packages (from altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in D:\guvi\Lib\site-packages (from altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (1.31.0)
Requirement already satisfied: colorama in D:\guvi\Lib\site-packages (from click<9,>=7.0->streamlit>=1.36->streamlit-option-menu) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in D:\guvi\Lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in D:\guvi\Lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.36->streamlit-option-menu) (4.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\guvi\Lib\site-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in D:\guvi\Lib\site-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in D:\guvi\Lib\site-packages (from pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (2025.2)
Requirement already satisfied: charset-normalizer<4,>=2 in D:\guvi\Lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in D:\guvi\Lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in D:\guvi\Lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in D:\guvi\Lib\site-packages (from requests<3,>=2.27->streamlit>=1.36->streamlit-option-menu) (2026.1.4)
Requirement already satisfied: attrs>=22.2.0 in D:\guvi\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in D:\guvi\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in D:\guvi\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in D:\guvi\Lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (0.22.3)
Requirement already satisfied: six>=1.5 in D:\guvi\Lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit>=1.36->streamlit-option-menu) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in D:\guvi\Lib\site-packages (from jinja2->altair<6,>=4.0->streamlit>=1.36->streamlit-option-menu) (3.0.2)